svix/svix-webhooks

- python/.gitignore
- python/.openapi-generator-ignore
cleans up generated files, makes it a bit easier to see what changes you intend to make
> py: dont generate docs & tests, ignore version info

- ChangeLog.md
- javascript/package.json
- python/setup.py
Also releasing the python and js packages.
> Bump version and update changelog.

- ChangeLog.md
- go/eventtype.go
- javascript/package.json
- python/setup.py
I accidentally made the `List` command for the event-type api private 🙈
> go: export event-type list command

- .github/workflows/go-lint.yml
> go: add golangci linting

- ChangeLog.md
- go/endpoint.go
> go: properly set endpoint in on create

- go/webhook.go
- go/webhook_test.go
based on @tasn comments on the PHP & Ruby PRs.
> go: use secure hash compare & add webhook tests

- .github/workflows/other-lint.yml
- composer.json
- go/webhook.go
- go/webhook_test.go
- javascript/jest.config.js
- javascript/package.json
- javascript/src/index.ts
- javascript/src/webhook.test.ts
- javascript/tsconfig.json
- javascript/yarn.lock
- php/src/Exception/WebhookException.php
- php/src/Webhook.php
- php/tests/WebhookTest.php
- python/README.md
- python/svix/receiver.py
- python/tests/test_receiver.py
- ruby/spec/webhook_spec.rb
- ruby/src/svix/webhook.rb
Each library has been done in a separate commit, but let me know if you'd like me to break them up into individual PRs.
Closes #43 
Closes #44
> Enforce timestamp tolerance across libraries

- java/README.md
> Change gradle installation instructions to use 'implementation'

- python/svix/api.py
@tasn: noticed this when I was testing the scripts you wrote in the docs.
> python: fix bug in endpoint create function

- go/application.go
- go/authentication.go
- go/endpoint.go
- go/errors.go
- go/eventtype.go
- go/message.go
- go/messageattempt.go
> go: Add additional guardrail to resp usage

- .github/workflows/javascript-release.yml
Frank: I think it's good, and I setup the env, but let's see how it works in the next release.
> JS: add a release action.

- .github/workflows/python-release.yml
Frank, please check if it works. I added everything that's needed.
> Python: add a release action.

- ChangeLog.md
- java/README.md
- java/gradle.properties
- javascript/package.json
- python/setup.py
- ruby/Gemfile.lock
- ruby/src/svix/version.rb
Will merge and make a release after #87
> Bump version & update changelog

- go/webhook.go
- go/webhook_test.go
- java/lib/src/main/java/com/svix/Webhook.java
- java/lib/src/main/java/com/svix/exceptions/WebhookSigningException.java
- java/lib/src/test/java/com/svix/WebhookTest.java
- javascript/src/index.ts
- javascript/src/webhook.test.ts
- php/src/Exception/WebhookSigningException.php
- php/src/Webhook.php
- php/tests/WebhookTest.php
- python/svix/webhooks.py
- python/tests/test_webhooks.py
- ruby/spec/webhook_spec.rb
- ruby/src/svix/errors.rb
- ruby/src/svix/webhook.rb
> Add signing functions

- csharp/.gitignore
- csharp/README.md
- csharp/Svix.Tests/Svix.Tests.csproj
- csharp/Svix.Tests/WebhookTest.cs
- csharp/Svix/Exceptions/WebhookVerificationException.cs
- csharp/Svix/Svix.csproj
- csharp/Svix/Utils.cs
- csharp/Svix/Webhook.cs
- csharp/svix.sln
Closes #83
Assuming we should get @svix-yair to sign off on this one.
> Csharp: Initial Lib & Webhook Verification

- go/svix.go
> Go: Add ability to override HTTP client & set default timeout

- go/eventtype.go
- go/internal/openapi/api_event_type.go
- go/internal/openapi/model_event_type_in.go
- go/internal/openapi/model_event_type_out.go
- go/internal/openapi/model_event_type_update.go
- go/internal/openapi/model_message_status.go
- java/lib/src/main/java/com/svix/EventType.java
- java/lib/src/main/java/com/svix/EventTypeListOptions.java
- javascript/src/index.ts
- javascript/src/openapi/models/MessageStatus.ts
- openapi.json
- python/svix/api.py
adds new message status & withContent to EventType
> Update OpenAPI Schema

- python/svix/api.py
> Python: dont use implict exports, addresses new pyright rule

- package-lock.json
- package.json
- tools/bump_version.js
> Add bump version script

- go/webhook.go
- go/webhook_test.go
Will enable a `--no-enforce-timestamp` flag for the cli's `verify` command.
If there is a compelling use case for this outside of the command line tool we can consider porting this to the the other libraries.
> go: add function to verify ignoring timestamp enforcement

- java/lib/src/main/java/com/svix/Application.java
- java/lib/src/main/java/com/svix/Authentication.java
- java/lib/src/main/java/com/svix/Endpoint.java
- java/lib/src/main/java/com/svix/EventType.java
- java/lib/src/main/java/com/svix/Integration.java
- java/lib/src/main/java/com/svix/Message.java
- java/lib/src/main/java/com/svix/MessageAttempt.java
- kotlin/lib/src/main/kotlin/Application.kt
- kotlin/lib/src/main/kotlin/Authentication.kt
- kotlin/lib/src/main/kotlin/Endpoint.kt
- kotlin/lib/src/main/kotlin/EventType.kt
- kotlin/lib/src/main/kotlin/Integration.kt
- kotlin/lib/src/main/kotlin/Message.kt
- kotlin/lib/src/main/kotlin/MessageAttempt.kt
#231, broke the inputs for java & kotlin, unfortunately I didn't realize this until running tests while prepping the latest release, this fixes the expected inputs for idempotency key & channel filtering.
> Fix input values for Java & Kotlin

- go/internal/openapi/api_message.go
- go/internal/openapi/api_message_attempt.go
- go/internal/openapi/model_list_response_double_endpoint_message_out_.go
- go/internal/openapi/model_list_response_double_message_attempt_endpoint_out_.go
- go/internal/openapi/model_list_response_double_message_attempt_out_.go
- go/internal/openapi/model_list_response_double_message_out_.go
- go/internal/openapi/model_list_response_endpoint_message_out_.go
- go/internal/openapi/model_list_response_message_attempt_out_.go
- go/internal/openapi/model_list_response_message_out_.go
- go/message.go
- go/messageattempt.go
- java/lib/src/main/java/com/svix/ListOptionsDouble.java
- java/lib/src/main/java/com/svix/Message.java
- java/lib/src/main/java/com/svix/MessageAttempt.java
- java/lib/src/main/java/com/svix/MessageAttemptListOptions.java
- java/lib/src/main/java/com/svix/MessageListOptions.java
- javascript/src/index.ts
- kotlin/lib/src/main/kotlin/ListOptionsDouble.kt
- kotlin/lib/src/main/kotlin/Message.kt
- kotlin/lib/src/main/kotlin/MessageAttempt.kt
- kotlin/lib/src/main/kotlin/MessageAttemptListOptions.kt
- kotlin/lib/src/main/kotlin/MessageListOptions.kt
- openapi.json
- python/svix/api.py
- ruby/lib/svix/message_attempt_api.rb
Match the libs to the spec changes.
> Libs: Add support for reverse iteration (`prev_iterator`) & after param in list commands

- server/svix-server/src/worker.rs
While much of the CRUD of setting customs headers per endpoint has already been done, they have not actually been applied to any of the messages thus far.
Simply utilizes the header values already in memory and adds them to relevant webhook events.
> Support custom headers for webhooks in worker threads

- go/application.go
- java/lib/src/main/java/com/svix/Application.java
- javascript/src/index.ts
- kotlin/lib/src/main/kotlin/Application.kt
- ruby/lib/svix/application_api.rb
Based on previous changes to Python, now adding support to the other
libraries for get-or-create
Fixes #224 
- All languages: Use the get_or_create binding
> Libs: Add GetOrCreate function for Application API

- server/svix-server/Cargo.toml
- server/svix-server/src/main.rs
Upgrade axum / remove deprecated calls
> server: upgrade axum/remove deprecrated calls

- go/internal/openapi/api_message_attempt.go
- go/messageattempt.go
- java/lib/src/main/java/com/svix/MessageAttempt.java
- kotlin/lib/src/main/kotlin/MessageAttempt.kt
Follow up to #301, adds support in go, java & kotlin.
> Libs: Use Regenerate templates

- server/svix-server/src/main.rs
- server/svix-server/src/test_util.rs
- server/svix-server/src/v1/endpoints/endpoint/crud.rs
- server/svix-server/src/v1/endpoints/endpoint/mod.rs
- server/svix-server/src/v1/endpoints/message.rs
- server/svix-server/src/v1/utils.rs
A simple create/read/list test for the message endpoints and utility functions for testing the dispatch of messages. To be expanded on.
> Add basic message dispatch tests

- server/svix-server/src/v1/endpoints/attempt.rs
Adds endpoints for "list attempts by message", "list attempted destinations",  and "list attempts for endpoint".
> Implement missing endpoints for the attempt API

- server/svix-server/src/v1/endpoints/application.rs
- server/svix-server/src/v1/endpoints/endpoint/mod.rs
- server/svix-server/src/v1/endpoints/message.rs
Reach full test coverage of validation code.
Add missing tests of payload validation logic.
> Add payload validation tests

- .gitignore
Ignore VSCode data via .gitignore
> Ignore VSCode data

- server/svix-server/src/v1/endpoints/attempt.rs
- server/svix-server/src/v1/endpoints/endpoint/mod.rs
- server/svix-server/tests/e2e_endpoint.rs
- server/svix-server/tests/utils/common_calls.rs
Adding additional end-to-end tests to bring rust tests to parity with python test suite.
> Tests: Add additional endpoint integration tests

- server/svix-server/tests/e2e_application.rs
- server/svix-server/tests/e2e_endpoint.rs
- server/svix-server/tests/e2e_event_type.rs
- server/svix-server/tests/e2e_message.rs
- server/svix-server/tests/utils/common_calls.rs
> Add missing trailing slash to two more test utils.

- server/svix-server/Cargo.toml
- server/svix-server/src/lib.rs
- server/svix-server/src/webhook.rs
Add basic Rust Webhook implementation
> Rust Webhook Signature

- server/svix-server/src/webhook.rs
- server/svix-server/tests/e2e_endpoint.rs
- server/svix-server/tests/utils/mod.rs
Test to validate that endpoint key rotation works as expected.
> Endpoint key-rotation integration test

- server/svix-server/src/core/types.rs
Don't allow users to add certain headers to endpoints.
> validate against forbidden header keys & prefixes

- server/run-tests.sh
- server/svix-server/src/core/cache/redis.rs
- server/svix-server/src/lib.rs
- server/svix-server/src/queue/redis.rs
- server/svix-server/src/redis/mod.rs
Addresses additional comments from #392.
> Multiple Commits Addressing Prior Comments

- server/svix-server/src/queue/redis.rs
This prevents messages from being re-queued with the same ID, which can cause messages to be re-queued multiple times.
> Rust: Ensure Redis queue message IDs are refreshed when re-queuing

- server/svix-server/src/queue/redis.rs
Use test queues instead of actual queues to avoid interfering with
other tests potentially using them.
> Rust: Improve redis queue migration tests

- server/svix-server/src/v1/endpoints/attempt.rs
- server/svix-server/tests/e2e_attempt.rs
I hope I didn't miss anywhere else this may be an issue at. Though
anyhow, it's important we always get the correct type (idoruid) so
that we support fetching by both.
> Always use ID or UID when accepting apps/endpoints in the API.

- server/svix-server/src/v1/endpoints/attempt.rs
I opened #408 so that we add tests to properly ensure it, but until then... :)
> Fix iterators for two routes for which they were broken

- server/svix-server/src/v1/endpoints/application.rs
- server/svix-server/tests/e2e_application.rs
The API supports passing get_if_exists to the application creation API
endpoint to toggle "get-or-create" mode.
This was already supported in the hosted version but we forgot to
backport it to this repo.
Fixes #427
> Application: add missing get-or-create to create endpoint.

- server/svix-server/Cargo.toml
- server/svix-server/src/error.rs
- server/svix-server/src/lib.rs
- server/svix-server/src/queue/redis.rs
- server/svix-server/src/redis/mod.rs
Replaces the previous list-based approached with Redis streams which are meant to model queue structures.
> Rewrite Redis-based queue to use Streams functionality

- server/svix-server/src/queue/redis.rs
This PR sets up a queue migration for the v2 processing queue and reinserts the members directly in the v3 main queue.
While it would have been preferable to migrate to the pending list of the main queue, this did not seem possible without introducing race conditions with other consumers from inserting it in the main queue first.
> Write migration for the legacy processing queue to stream-based queue

- .github/workflows/codeball.yml
It looks cool, and it's meant to be non-intrusive (just as an extra
indicator).
Source: https://github.com/sturdy-dev/codeball-action
> Let's try out the codeball automatic code reviewer.

- server/svix-server/tests/queue.rs
Previously only many producers/consumers with non-delayed messages was tested. This simply repeats that test, but with a 500ms delay on every message to guarantee they go through the delayed queue without conflict.
> Add test for many consumers with delayed messages

- server/svix-server/src/queue/redis.rs
To ensure no data added by an outdated server while a newer instance of the server is running is unhandled, this runs migrations in a loop with exponential delay up to 24 hours.
> Run migrations in a loop with exponential delay

- javascript/src/index.ts
- javascript/src/webhook.test.ts
- python/svix/webhooks.py
Following a discussion on slack:
https://svixcommunity.slack.com/archives/C031WPPNTUZ/p1652203539944799\?thread_ts\=1652202869.364919\&cid\=C031WPPNTUZ
> JavaScript/Python: handle obviously malformed secrets

- server/svix-server/src/core/types.rs
- server/svix-server/src/v1/endpoints/endpoint/mod.rs
Adds the endpoint stats endpoint which returns metrics on the status of messages for that endpoint.
> Add endpoint stats endpoint

- server/svix-server/src/cfg.rs
- server/svix-server/src/v1/endpoints/auth.rs
Creates a configuration variable for the region in which the dashboard access region can be changed.
> Add changing region in dashboard access endpoint

- server/svix-server/config.default.toml
- server/svix-server/src/cfg.rs
- server/svix-server/src/v1/endpoints/endpoint/crud.rs
- server/svix-server/tests/e2e_endpoint.rs
> Server: add a configuration to only allow HTTPS

- server/svix-server/src/main.rs
This lets people developing locally (or in general) the ability to
generate different tokens for different org_ids (e.g. for operational
webhooks) easily, without having to do JWT signing themselves.
Related: #508
> Server: support passing an org_id to the JWT generate command.

- server/svix-server/src/worker.rs
We were generating a timestamp at the beginning of the function which we
were using for generating the header timestamp. Though we weren't using
this timestamp for neither the Ksuid nor the created_at of attempt.
Causing them to have different values than what we expect them to be.
This is a fix for this occurrence, though the real problem is that we
are quite fragile about this. We should have a good way for generating
it that is not as easy to get wrong as this one.
I think the REAL problem though, is that we have the timestamp in two
places, the ksuid and the created_at field. Which we should definitely
fix.
> Server: use correct timestamp for attempt's id and created

- .github/workflows/server-ci.yml
I forgot doing it in 9ba6df04e5f294bc0638650490ec503e304411ea
> Server CI: ensure lockfile is frozen and separate build stage.

- server/svix-server/src/worker.rs
It makes the code slightly cleaner and more testable (as the behaviors
are separate and unrelated), though also we need it for an upcoming PR.
> Server: split signature and header generation.

- server/svix-server/src/error.rs
Log internal server errors at error level,
others at debug.
> Server: Improve HTTP response logging

- server/svix-server/src/core/cache/memory.rs
- server/svix-server/src/core/cache/mod.rs
- server/svix-server/src/core/cache/none.rs
- server/svix-server/src/core/cache/redis.rs
- server/svix-server/src/core/mod.rs
- server/svix-server/src/core/run_with_retries.rs
Begins to add retry functionality to mitigate intermittent Redis failures.
> Add retry functionality to Redis cache

- server/svix-server/config.default.toml
- server/svix-server/src/cfg.rs
- server/svix-server/src/worker.rs
- server/svix-server/tests/worker.rs
Makes some requested changes to the endpoint disabling code.
Follow up to https://github.com/svix/svix-webhooks/pull/566
> Alter endpoint disabling code

- server/svix-server/src/queue/redis.rs
Prior to these changes, there was an error where pending tasks being reinserted
into the queue were ACKed before the reinsertion meaning an improperly timed
crash could lead to lost message tasks. These changes reorder the ACKing and
reinsertion and perform them in a Redis pipeline such as to reduce the chance of
data loss on a server crash.
> Eliminate period in which dispatches could fail during improperly timed crashes

- server/svix-server/src/queue/redis.rs
Before these changes the delayed queue processing and pending queue processing were done in one function, in one loop, on the same clock. These changes split these two background tasks to separate loops with separate clocks.
Additionally these changes remove an unnecessary Tokio task whose only use was to spawn more tasks.
> Simplify and split the background tasks for the Redis queue

- server/svix-server/src/queue/redis.rs
Introduces a lock on the delayed queue processing background task to allow
concurrent workers.
> Improve delayed queue processing to support concurrent workers

- server/svix-server/src/queue/redis.rs
Simply uses the more concise `XAUTOCLAIM` over two commands with identical functionality.
Manually tested to work with Redis 7.
> Use XAUTOCLAIM over XPENDING followed by XCLAIM

- server/svix-server/src/queue/redis.rs
These changes eliminate some `unwrap`s and `expect`s in the Redis queue code where possible.
> Improve error handling in the Redis queue

- server/svix-server/src/error.rs
> Typo in error.rs

- go/internal/openapi/api_authentication.go
- openapi.json
We recently merged #605, which enables upserting records on our PUT methods. Since the responses for the affected endpoints can now be 200 _or_ 201, this PR updates our libraries to reflect that.
> Update libraries to support upsert PUT methods

- server/svix-server/src/v1/endpoints/message.rs
Message payload should be a valid JSON object
> Add Message payload validation

- server/svix-server/src/core/otel_spans.rs
Prior request IDs were only reported when a specific header value was sent in the request. These changes alter the code so a unique KsuidMs is generated per request and used as a request ID when this header value is not set.
> Alter request ID field in HTTP request logs to use unique KsuidMs

- server/svix-server/src/worker.rs
A followup to https://github.com/svix/svix-webhooks/pull/619 introducing unique IDs per worker task in addition to just API requests. This is a random KsuidMs added per task spawned by the worker.
Additionally adds the `Copy` derive to the `WorkerContext` struct.
> Add unique IDs per worker task for tracing

- csharp/Svix/Abstractions/IEndpoint.cs
- csharp/Svix/Endpoint.cs
- go/endpoint.go
- java/lib/src/main/java/com/svix/Endpoint.java
- javascript/src/index.ts
- kotlin/lib/src/main/kotlin/Endpoint.kt
- python/svix/api.py
- ruby/lib/svix/endpoint_api.rb
- rust/src/api.rs
We have had endpoint stats functionality internally for some time now, this PR publishes the functionality in our libraries.
Closes #628.
> Expose endpoint stats function in libraries

- server/svix-server/src/core/otel_spans.rs
To aid in debugging, this change adds the idempotency key to any HTTP request's span given one is provided.
> Include idempotency key in request spans

- server/Cargo.lock
> Server: update all dependencies.

- server/Dockerfile
> Server: update Rust vesrion in Docker.

- server/svix-server/src/core/otel_spans.rs
This fixes a bug where the `x-request-id` header is not used and corrects the functionality to support the `svix-req-id` header when creating the spans for each request to the API server.
`x-request-id` is used before `svix-req-id`, and if both are unset, then the request ID will be a randomly generated `KsuidMs`.
> Correct request ID handling in tracing spans

- go/internal/openapi/model_environment_settings_out.go
- go/internal/openapi/model_settings_in.go
- go/internal/openapi/model_settings_out.go
- openapi.json
We need to keep our openapi.json schema up-to-date.
> API spec update

- server/svix-server/src/core/idempotency.rs
- server/svix-server/src/core/otel_spans.rs
- server/svix-server/src/queue/redis.rs
This fixes a bunch of Clippy errors that show up in the beta CI job. [Example of a failure.](https://github.com/svix/svix-webhooks/actions/runs/3136424848/jobs/5093319099#step:8:727)
Clear up Clippy errors for future PRs.
Just implements the suggested clippy fixes. That's pretty much it.
> Fix Clippy Errors

- server/svix-server/src/core/security.rs
Small changes to security module to support downstream
refactoring.
> Further reorganization of security module

- server/svix-server/src/error.rs
This PR simply adds support for errors from our Cache module
in the `ctx!` error handling macro.
> Support cache errors in the ctx! macro

- server/svix-server/src/queue/redis.rs
Before this change, it was discovered that `QueueTasks` were only ACKed, not deleted from the queue after dispatch. While this did not alter functionality at all, it would lead to infinitely increasing memory use with each `QueueTask`.
This was due to a confusing behavior in Redis, where an `XACK` would remove the item from the list of items returned, but not actually free the memory.
> Ensure QueueTasks are deleted after acknowledgement

- kotlin/lib/src/main/kotlin/Application.kt
- kotlin/lib/src/main/kotlin/Authentication.kt
- kotlin/lib/src/main/kotlin/Endpoint.kt
- kotlin/lib/src/main/kotlin/EventType.kt
- kotlin/lib/src/main/kotlin/Integration.kt
- kotlin/lib/src/main/kotlin/Message.kt
- kotlin/lib/src/main/kotlin/MessageAttempt.kt
- kotlin/lib/src/main/kotlin/SvixOptions.kt
- kotlin/templates/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
Enable configuration of the initial delays for
retries as well as the maximum number of retries
in the event of a server-side API failure.
> Kotlin: Additional Configuration Parameters

- server/svix-server/src/worker.rs
It was noticed that there was an `expect` call on a fallible method to retrieve a response body from a given response to webhook dispatch. While it is rare for this method to fail, it is possible that a panic occurred before these changes.
With these changes, it now records such failures as if the whole request was a failure in that a failed message attempt is recorded with the error message as the response and a reported status code of 0.
> Handle failure to read a response body after dispatch

- go/internal/openapi/api_message_attempt.go
- go/internal/openapi/model_recover_in.go
- go/internal/openapi/model_replay_in.go
- openapi.json
We need to keep our libraries up-to-date.
> Update OpenAPI spec

- server/svix-server/src/core/operational_webhooks.rs
- server/svix-server/src/v1/endpoints/auth.rs
- server/svix-server/src/v1/endpoints/endpoint/mod.rs
Fix clippy issues occurring with new
version of Rust.
> Server: Fix Clippy Issues

- server/svix-server/src/db/mod.rs
Improve function to accept needed parameters
instead of the entire Configuration struct.
> Server: Improve db `connect` function

- server/svix-server/src/v1/endpoints/endpoint/mod.rs
Per spec, HTTP headers are case insensitive in HTTP 1.1 and all lower case in HTTP 2.0. This means that sensitive headers can come in different casing. Authorization, authorization, and AUTHORIZATION, should all be considered sensitive, which wasn't the case before this change.
> BE: fix bug with case-sensitiveness of sensitive endpoint headers.

- server/docker-compose.yml
Local development was funky as thnigs weren't starting in the right order.
> Server: fix docker-compose to have the correct deps.

- server/svix-server/src/core/cache/memory.rs
- server/svix-server/src/core/cache/redis.rs
- server/svix-server/src/core/idempotency.rs
- server/svix-server/src/core/otel_spans.rs
- server/svix-server/src/core/security.rs
- server/svix-server/src/core/types/mod.rs
- server/svix-server/src/db/mod.rs
- server/svix-server/src/error.rs
- server/svix-server/src/lib.rs
- server/svix-server/src/main.rs
- server/svix-server/src/queue/redis.rs
- server/svix-server/src/v1/endpoints/endpoint/crud.rs
- server/svix-server/src/v1/utils/mod.rs
- server/svix-server/src/wait_for.rs
- server/svix-server/src/worker.rs
- server/svix-server/tests/e2e_application.rs
- server/svix-server/tests/e2e_attempt.rs
- server/svix-server/tests/e2e_auth.rs
- server/svix-server/tests/e2e_endpoint.rs
- server/svix-server/tests/queue.rs
- server/svix-server/tests/utils/common_calls.rs
- server/svix-server/tests/utils/mod.rs
- server/svix-server/tests/worker.rs
Beta clippy lints currently fail. This blocks local dev.
```
rustup install toolchain beta
cargo +beta clippy --fix --allow-dirty
```
> Fix Clippy Beta lints (WIP)

- javascript/package.json
- javascript/src/index.ts
- javascript/src/timing_safe_equal.ts
- javascript/yarn.lock
Fix broken JavaScript string compare
Used function from the Deno standard Library
> Fix TS string compare

- server/svix-server/src/worker.rs
It was discovered that, when a connection to the queue breaks, that the server would not shutdown gracefully on ctrl+c. This corrects this by ensuring that the `SHUTTING_DOWN` atomic bool is loaded and read  before receiving from the queue in the `worker_loop` instead of only after the queue is read from successfully.
> Ensure server can shut down gracefully if queue connection breaks

- javascript/package.json
- javascript/src/index.ts
- javascript/src/timing_safe_equal.ts
- javascript/yarn.lock
- server/svix-server/src/core/operational_webhooks.rs
- server/svix-server/src/core/permissions.rs
- server/svix-server/src/db/models/endpoint.rs
- server/svix-server/src/db/models/endpointmetadata.rs
- server/svix-server/src/v1/endpoints/attempt.rs
- server/svix-server/src/v1/endpoints/endpoint/crud.rs
- server/svix-server/src/v1/endpoints/endpoint/mod.rs
- server/svix-server/src/v1/endpoints/event_type.rs
- server/svix-server/src/worker.rs
- server/svix-server/tests/e2e_endpoint.rs
- server/svix-server/tests/e2e_operational_webhooks.rs
- server/svix-server/tests/worker.rs
> Merge upstream 27dbb4a

- rust/src/api.rs
Addresses https://github.com/svix/svix-webhooks/issues/746
> Make ListOptions and PostOptions fields  public

- server/svix-server/src/wait_for.rs
It's better to retry the connection attempt after a few seconds than waiting for the entire duration of `wait_for_seconds`. In cloud and containerized environments it's not uncommon to start running before the network stack has been brought up, causing the first connection attempt to hang until the full `wait_for` duration has been exhausted, even though retrying after a few seconds would have resulted in a successful connection.
Wrap connection attempt in a `tokio::time::timeout`.
Resolves #781
> Make `wait_for` timeout early and retry

- server/svix-server/src/cfg.rs
- server/svix-server/tests/e2e_attempt.rs
- server/svix-server/tests/e2e_endpoint.rs
- server/svix-server/tests/e2e_operational_webhooks.rs
We have new clippy failures. This is blocking new PRs.
Locally `rustup update`, then
```
cargo +beta clippy --all-targets --all-features --fix --allow-dirty
cargo fmt
```
> Run clippy beta --fix

- server/svix-server/src/v1/endpoints/endpoint/mod.rs
- server/svix-server/tests/e2e_endpoint.rs
For https://github.com/svix/svix-webhooks/issues/756, we want to give folks the ability to control the lookback period to get endpoint stats for. The original issue suggested "before/after", but most of our newer endpoints have used "since/until", so that's what we went with here.
Just adds the new query params. This endpoint also didn't have any E2E tests, so I went ahead and added some. They aren't perfect integration tests, since we create the messagedestination records manually. But it at least tests the query being run (and a true integration test would be much flakier since we can't really control the state of messagedestinations from outside the worker).
> Add since/until query params to endpoint stats

- go/internal/openapi/model_list_response_application_out_.go
- openapi.json
Listing applications supports prev_iter now.
> Update OpenAPI with application list changes

- csharp/Svix/Application.cs
- go/application.go
- go/internal/openapi/api_application.go
- go/internal/openapi/model_list_response_event_type_out_.go
- java/lib/src/main/java/com/svix/Application.java
- java/lib/src/main/java/com/svix/ApplicationListOptions.java
- javascript/src/index.ts
- kotlin/lib/src/main/kotlin/Application.kt
- kotlin/lib/src/main/kotlin/ApplicationListOptions.kt
- openapi.json
- python/svix/api.py
- rust/src/api.rs
The server-side support for these lib changes is already done, this is just bringing libs up to speed.
> Add app and event type list options to libs

- server/Cargo.lock
Fix https://github.com/svix/svix-webhooks/security/dependabot/25
Run cargo update
> Run Cargo Update

- server/Cargo.lock
Fix security lints.
`cargo update`
> Cargo update

- server/svix-server/src/worker.rs
Because message payloads expire on a configurable
interval, we should not propagate an error when one 
is missing during worker message retrieval. Instead
log a warning and indicate the potential reason.
> Server: Do not throw error on missing payload

- server/run-tests.sh
Update test script to support passing additional args,
e.g., an individual test name when running tests.
> Server: Update test script

- csharp/Svix/Abstractions/IBackgroundTask.cs
- csharp/Svix/BackgroundTask.cs
- csharp/Svix/Models/BackgroundTaskListOptions.cs
- go/backgroundtask.go
- java/lib/src/main/java/com/svix/BackgroundTask.java
- java/lib/src/main/java/com/svix/BackgroundTaskListOptions.java
- javascript/src/index.ts
- kotlin/lib/src/main/kotlin/BackgroundTask.kt
- kotlin/lib/src/main/kotlin/BackgroundTaskListOptions.kt
- python/svix/api.py
- ruby/lib/svix/background_tasks_api.rb
- rust/src/api.rs
This updates the libs to support fetching/listing BackgroundTasks. These endpoints were added a while ago, but the libs were never updated.
Update the libs.
> Add BackgroundTask feature to libs

- server/svix-server/src/worker.rs
This is a functional NOOP refactor the worker, that largely aims to
- Remove uses of `unreachable!` macro
- Remove unnecessary messagedestination fetch attempt in dispatch function
- Just generally simplify things, remove code, etc.
- This mostly refactors `process_queue_task_inner` so that the task type is `match`ed on only once. Overall this cuts down on code duplication too.
> Simplify process_task_inner in worker

- bridge/svix-bridge/src/webhook_receiver/tests.rs
Cases added for:
- queue publish failure
- bad shaped json body
- non-json body
> add tests to show the different http statuses given by receiver

- server/docker-compose.yml
- server/testing-docker-compose.yml
We should enjoy the many benefits that Redis 7 has to offer.
> Update to Redis 7

- server/openapi.json
- server/svix-server/src/db/models/messageattempt.rs
- server/svix-server/src/v1/endpoints/attempt.rs
- server/svix-server/src/worker.rs
This adds support for listing attempt headers given a message and attempt id.
> Server: Add list-attempt-headers endpoint

- server/openapi.json
- server/svix-server/src/v1/endpoints/environment_settings.rs
- server/svix-server/src/v1/endpoints/mod.rs
- server/svix-server/src/v1/mod.rs
Verified with a manual curl:
```
curl -sS http://localhost:8071/api/v1/environment/settings/ | jq
{
"customColor": null,
"customLogoUrl": null,
"customFontFamily": null,
"customThemeOverride": null,
"enableChannels": false,
"enableIntegrationManagement": false,
"enableTransformations": false,
"colorPaletteLight": null,
"colorPaletteDark": null
}
```
> add `/environment/settings/` endpoint

- javascript/src/index.ts
I missed that in the previous PR (#978) and this was brought up by a customer.
> JavaScript: Fix verification function to allow Buffer

- csharp/Svix/Abstractions/IApplication.cs
- csharp/Svix/Abstractions/IEndpoint.cs
- csharp/Svix/Abstractions/IEventType.cs
- csharp/Svix/Application.cs
- csharp/Svix/Endpoint.cs
- csharp/Svix/EventType.cs
- go/application.go
- go/endpoint.go
- go/eventtype.go
- go/internal/openapi/api_application.go
- go/internal/openapi/api_endpoint.go
- go/internal/openapi/api_event_type.go
- java/lib/src/main/java/com/svix/Application.java
- java/lib/src/main/java/com/svix/Endpoint.java
- java/lib/src/main/java/com/svix/EventType.java
- javascript/src/index.ts
- kotlin/lib/src/main/kotlin/Application.kt
- kotlin/lib/src/main/kotlin/Endpoint.kt
- kotlin/lib/src/main/kotlin/EventType.kt
- openapi.json
- python/svix/api.py
- ruby/lib/svix/application_api.rb
- ruby/lib/svix/endpoint_api.rb
- ruby/lib/svix/event_type_api.rb
- rust/src/api.rs
This implements the `patch` functions for application, endpoint and
event type.
Fixes #608
> Libs: implement the `patch` endpoints for partial updates

- server/svix-server/src/core/idempotency.rs
This test repeatedly fails, but not always. A real frustration!
Rephrasing the assertions may help. Instead of using fixed deadlines, assert based on relative durations between the first and second.
> Server: deflake test_lock

- server/svix-server/src/core/webhook_http_client.rs
- server/svix-server/src/db/mod.rs
- server/svix-server/src/db/models/eventtype.rs
Address clippy errors occurring on beta
> Server: Appease clippy

- go/svix.go
why:
- to distinguish between `""` and `nil`
solves #1019
> `NullableString()` now takes a pointer argument

- server/Cargo.lock
- server/svix-server/Cargo.toml
Keep things up to date.
I originally hoped these would fix a couple of SVEs, but I don't think it does.
Run cargo-update.
> Update `chrono` and run Cargo update

- server/svix-server/src/main.rs
Moving the main `run()` invocation into the command match block allows us to gracefully shutdown the tracer provider no matter which path is taken. It also makes it clearer that no fall-through is intended; either a command is run or the server starts.
> Rearrange main to allow graceful trace provider shutdown in all paths

- go/application.go
- go/authentication.go
- go/backgroundtask.go
- go/endpoint.go
- go/eventtype.go
- go/integration.go
- go/message.go
- go/messageattempt.go
Close https://github.com/svix/svix-webhooks/issues/1043
> go: export internal types as alias

- bridge/Dockerfile
- server/Dockerfile
> Update Docker image

- go/internal/openapi/model_template_in.go
- go/internal/openapi/model_template_out.go
- go/internal/openapi/model_template_patch.go
- go/internal/openapi/model_template_update.go
- openapi.json
Update OpenAPI spec and regenerate libs
> Update OpenAPI spec and regenerate libs

- go/internal/openapi/model_event_type_import_open_api_in.go
- go/internal/openapi/model_template_in.go
- go/internal/openapi/model_template_patch.go
- go/internal/openapi/model_template_update.go
- go/internal/openapi/model_transformation_template_kind.go
- openapi.json
Specifically, this is to support the new "specRaw" event type import.
> Libs: bump spec

- bridge/Cargo.lock
We had a yanked version in the lockfile, waking up cargo-deny.
> Bridge: bump ahash

- server/svix-server/src/expired_message_cleaner.rs
Simplifies some of the timing code on the expired message cleaner. No more 2 level check for slow vs idle. Just sleep big when the expired row count is less than the batch size.
> Server: expired message cleaner cleanup

- README.md
Added badges to show download volumes on npm, pypi, and docker.
> Add download badges to ReadMe

- bridge/Cargo.lock
- bridge/svix-bridge-plugin-queue/Cargo.toml
- bridge/svix-bridge/Cargo.toml
- bridge/svix-bridge/src/main.rs
- server/Cargo.lock
- server/svix-server/Cargo.toml
- server/svix-server/src/core/cryptography.rs
- server/svix-server/src/main.rs
- server/svix-server/src/queue/mod.rs
- server/svix-server/src/redis/mod.rs
- server/svix-server/src/worker.rs
- server/svix-server_derive/Cargo.toml
Lots of dependencies are outdated and some unused, this PR fixes the easy ones.
Remove unused, upgrade many old dependencies.
> Upgrade / remove dependencies

- server/Cargo.lock
- server/svix-server/Cargo.toml
- server/svix-server/src/queue/mod.rs
- server/svix-server/src/queue/rabbitmq.rs
~~Security audit CI job will be fixed by #1205 .~~
> Replace own RabbitMQ queue implementation by omniqueue

- .github/workflows/other-lint.yml
- kotlin/lib/src/main/kotlin/SvixOptions.kt
This reverts commit a30ab8870114b5985df53fd5f65eeff85d36a163.
Now we just need to figure out how to make it run _all_ checks to find what things break, and fix them...
> Reapply "ci: Upgrade super-linter"

- .github/workflows/typos.yml
- .typos.toml
- ChangeLog.md
- csharp/Svix.Tests/WebhookTest.cs
- java/templates/libraries/okhttp-gson/ApiClient.mustache
- rust/README.md
- server/README.md
- server/openapi.json
- server/svix-server/src/cfg.rs
- server/svix-server/src/core/idempotency.rs
- server/svix-server/src/core/otel_spans.rs
- server/svix-server/src/core/webhook_http_client.rs
- server/svix-server/src/db/mod.rs
- server/svix-server/src/error.rs
- server/svix-server/src/lib.rs
- server/svix-server/src/queue/redis.rs
- server/svix-server/src/redis/mod.rs
- server/svix-server/src/v1/utils/patch.rs
- server/svix-server/tests/it/e2e_message.rs
- server/svix-server/tests/it/utils/mod.rs
- server/svix-server/tests/it/worker.rs
… and fix a bunch that were present.
> Check for typos in CI

- .github/workflows/bridge-security.yml
- .github/workflows/server-security.yml
- bridge/Cargo.lock
- bridge/testing-docker-compose.yml
CI failed in #1237, fix seemed worth a separate PR.
> bridge: Fix CI

- server/svix-server/src/queue/mod.rs
- server/svix-server/src/queue/rabbitmq.rs
- server/svix-server/src/queue/redis.rs
- server/svix-server/tests/it/db.rs
- server/svix-server/tests/it/e2e_application.rs
- server/svix-server/tests/it/e2e_attempt.rs
- server/svix-server/tests/it/e2e_auth.rs
- server/svix-server/tests/it/e2e_endpoint.rs
- server/svix-server/tests/it/e2e_event_type.rs
- server/svix-server/tests/it/e2e_message.rs
- server/svix-server/tests/it/e2e_operational_webhooks.rs
- server/svix-server/tests/it/integ_webhook_http_client.rs
- server/svix-server/tests/it/utils/common_calls.rs
- server/svix-server/tests/it/utils/mod.rs
It's as boring as it looks.
Later PRs will reformat more and also update CI accordingly.
> server: Reformat some imports

- .github/workflows/bridge-ci.yml
- .github/workflows/rust-lint.yml
- .github/workflows/server-ci.yml
- bridge/run-tests.sh
- server/run-tests.sh
… if available.
Makes tests execute faster.
> Use cargo-nextest instead of regular cargo test

- .github/workflows/bridge-ci.yml
- bridge/.rustfmt.toml
- bridge/svix-bridge-plugin-queue/src/config.rs
- bridge/svix-bridge-plugin-queue/src/gcp_pubsub/mod.rs
- bridge/svix-bridge-plugin-queue/src/lib.rs
- bridge/svix-bridge-plugin-queue/src/rabbitmq/mod.rs
- bridge/svix-bridge-plugin-queue/src/receiver_output/mod.rs
- bridge/svix-bridge-plugin-queue/src/redis/mod.rs
- bridge/svix-bridge-plugin-queue/src/sender_input/mod.rs
- bridge/svix-bridge-plugin-queue/src/sqs/mod.rs
- bridge/svix-bridge-plugin-queue/tests/it/gcp_pubsub_consumer.rs
- bridge/svix-bridge-plugin-queue/tests/it/rabbitmq_consumer.rs
- bridge/svix-bridge-plugin-queue/tests/it/redis_stream_consumer.rs
- bridge/svix-bridge-plugin-queue/tests/it/sqs_consumer.rs
- bridge/svix-bridge-types/src/lib.rs
- bridge/svix-bridge/src/allocator.rs
- bridge/svix-bridge/src/config/mod.rs
- bridge/svix-bridge/src/config/tests.rs
- bridge/svix-bridge/src/main.rs
- bridge/svix-bridge/src/runtime/mod.rs
- bridge/svix-bridge/src/runtime/tests.rs
- bridge/svix-bridge/src/webhook_receiver/config.rs
- bridge/svix-bridge/src/webhook_receiver/mod.rs
- bridge/svix-bridge/src/webhook_receiver/tests.rs
- bridge/svix-bridge/src/webhook_receiver/types.rs
- bridge/svix-bridge/src/webhook_receiver/verification.rs
More consistency in formatting for better readability. See also #1268 and #1278 for previous PRs around this.
> bridge: Reformat imports using nightly

- README.md
README has been updated with appropriate notes on redis eviction
considerations.
> Update README with redis eviction notes

- openapi.json
New features require new parameters exposed in the libs.
> Spec: update for new `/events` param, `after`

- server/svix-server/src/core/otel_spans.rs
> Clean up tracing spans for HTTP requests

- server/svix-server/src/queue/redis.rs
Unwraps in non-test code are a bad idea. These two were the only ones left that #551 would have fixed.
> server: Remove unwraps in redis queue module

- server/svix-server/src/worker.rs
> Improve error message

- bridge/Cargo.lock
… to replace yanked httparse version.
> Bump locked dependencies again

- bridge/svix-bridge-plugin-kafka/src/input.rs
> Update comments in KafkaConsumer

- .github/workflows/php-ci.yml
> ci: Update GitHub actions revs for php-ci

- server/svix-server/src/core/cache/memory.rs
- server/svix-server/src/core/cache/redis.rs
- server/svix-server/tests/it/redis_queue.rs
Fixes the CI failure in #1376.
> server: Fix new compiler / clippy warnings

- go/internal/openapi/model_message_attempt_endpoint_out.go
- go/internal/openapi/model_message_attempt_out.go
- openapi.json
Adding the new response duration ms field to attempts.
> Libs: update spec

- bridge/.clippy.toml
- bridge/Cargo.toml
- bridge/svix-bridge-plugin-kafka/Cargo.toml
- bridge/svix-bridge-plugin-kafka/src/input.rs
- bridge/svix-bridge-plugin-kafka/tests/it/kafka_consumer.rs
- bridge/svix-bridge-plugin-queue/Cargo.toml
- bridge/svix-bridge-plugin-queue/src/config.rs
- bridge/svix-bridge-plugin-queue/src/gcp_pubsub/mod.rs
- bridge/svix-bridge-plugin-queue/src/lib.rs
- bridge/svix-bridge-plugin-queue/src/receiver_output/mod.rs
- bridge/svix-bridge-plugin-queue/src/sender_input/mod.rs
- bridge/svix-bridge-plugin-queue/tests/it/gcp_pubsub_consumer.rs
- bridge/svix-bridge-plugin-queue/tests/it/rabbitmq_consumer.rs
- bridge/svix-bridge-plugin-queue/tests/it/rabbitmq_receiver.rs
- bridge/svix-bridge-plugin-queue/tests/it/redis_stream_consumer.rs
- bridge/svix-bridge-plugin-queue/tests/it/sqs_consumer.rs
- bridge/svix-bridge-types/Cargo.toml
- bridge/svix-bridge-types/src/lib.rs
- bridge/svix-bridge/Cargo.toml
- bridge/svix-bridge/src/config/mod.rs
- bridge/svix-bridge/src/runtime/mod.rs
- bridge/svix-bridge/src/webhook_receiver/mod.rs
- bridge/svix-bridge/src/webhook_receiver/tests.rs
- server/.clippy.toml
- server/Cargo.toml
- server/svix-server/src/core/cache/mod.rs
- server/svix-server/src/core/webhook_http_client.rs
- server/svix-server/src/queue/redis.rs
- Make useful lints show up in more places (first and last commit)
- Disable a particular lint that has an annoying false positive case
> Improve clippy helpfulness

- python/svix/api.py
The server fails to parse timestamps without any timezone.
This diff treats any timestamp without a TZ set as if it's in UTC.
Folks who want to pass a local time need to be sure to set the relevant TZ themselves else we'll wind up treating it as UTC without shifting the various components.
> Libs(Python): ensure datetimes have a TZ

- server/svix-server/src/core/types/mod.rs
- server/svix-server/src/v1/endpoints/application.rs
- server/svix-server/src/v1/endpoints/attempt.rs
- server/svix-server/src/v1/endpoints/endpoint/crud.rs
- server/svix-server/src/v1/endpoints/event_type.rs
- server/svix-server/src/v1/endpoints/message.rs
- server/svix-server/src/v1/utils/mod.rs
- server/svix-server/tests/it/e2e_attempt.rs
Part of https://github.com/svix/monorepo-private/issues/8864.
> server: Support filtering by before and after at the same time

- server/svix-server/src/queue/redis.rs
- server/svix-server/tests/it/redis_queue.rs
`select!` over `sleep` and another future is a lot more code than `timeout`.
Use `timeout` where applicable.
Closes https://github.com/svix/monorepo-private/issues/8417.
> server: Use tokio::time::timeout where applicable

- .github/workflows/bridge-release.yml
- .github/workflows/csharp-release.yml
- .github/workflows/java-release.yml
- .github/workflows/javascript-release.yml
- .github/workflows/kotlin-release.yml
- .github/workflows/php-release.yml
- .github/workflows/python-release.yml
- .github/workflows/ruby-release.yml
- .github/workflows/rust-release.yml
- .github/workflows/server-release.yml
- .github/workflows/update-postman.yml
This should fix some of the missing credentials issues.
> Add `release` environment to release jobs

- .github/workflows/python-lint.yml
- .github/workflows/python-release.yml
Two Python-related actions were outdated and generating deprecation warnings.
Upgrade to the latest versions.
> ci: Upgrade actions/setup-python

- server/svix-server/src/core/types/mod.rs
> Increase max endpoint rotations

- server/Dockerfile
This should fix failing tests.
> Update Dockerfile to Rust 1.79

- ruby/Gemfile.lock
- ruby/README.md
- ruby/svix.gemspec
- ruby/templates/api_client_typhoeus_partial.mustache
> soft-require typhoeus

- .github/workflows/csharp-lint.yml
- .github/workflows/csharp-release.yml
- .github/workflows/javascript-lint.yml
- .github/workflows/javascript-release.yml
- .github/workflows/kotlin-lint.yml
- .github/workflows/ruby-lint.yml
When looking into https://github.com/svix/monorepo-private/issues/9262, I found that we were not testing workflow updates properly.
Have the workflow run when the workflow definition changes.
> ci: Run lint jobs when the workflow definition changes

- rust/src/api.rs
It's convenient to be able to create multiple instances of the same client to pass them around different parts of the program.
Implement `Clone` for the `Svix` client. Wrap the inner `Configuration` in an `Arc` to make cloning cheap.
Supersedes #777.
> Implement Clone for Svix client

- bridge/Dockerfile
> bridge: update ca-certificates

- go/internal/openapi/api_stream.go
- go/internal/openapi/model_app_usage_stats_in.go
- go/internal/openapi/model_app_usage_stats_out.go
- go/internal/openapi/model_list_response_application_out_.go
- go/internal/openapi/model_list_response_application_stats_.go
- go/internal/openapi/model_list_response_background_task_out_.go
- go/internal/openapi/model_list_response_endpoint_message_out_.go
- go/internal/openapi/model_list_response_endpoint_out_.go
- go/internal/openapi/model_list_response_event_type_out_.go
- go/internal/openapi/model_list_response_integration_out_.go
- go/internal/openapi/model_list_response_message_attempt_endpoint_out_.go
- go/internal/openapi/model_list_response_message_attempt_out_.go
- go/internal/openapi/model_list_response_message_endpoint_out_.go
- go/internal/openapi/model_list_response_message_out_.go
- go/internal/openapi/model_list_response_operational_webhook_endpoint_out_.go
- go/internal/openapi/model_list_response_sink_out_.go
- go/internal/openapi/model_list_response_stream_event_type_out_.go
- go/internal/openapi/model_list_response_stream_out_.go
- go/internal/openapi/model_list_response_stream_sink_out_.go
- go/internal/openapi/model_list_response_template_out_.go
- go/internal/openapi/model_sink_http_config.go
- openapi.json
Part of https://github.com/svix/monorepo-private/issues/9393.
> Bump OpenAPI spec and regenerate libs

- server/svix-server/src/lib.rs
- server/svix-server/src/main.rs
- server/svix-server/src/openapi.rs
Remove inconsistencies with private fork, improve readability.
> server: Clean up openapi module

- deny.toml
- server/Cargo.lock
- server/Dockerfile
- server/svix-server/Cargo.toml
> server: Bump dependencies and select idna backend

- README.md
- server/svix-server/config.default.toml
Also improve documentation around tuning the parameters.
> Server: Increase default max pool sizes

- rust/src/model_ext.rs
Useful for the new Svix CLI written in Rust.
> Add FromStr impls for MessageStatus, StatusCodeClass

- svix-cli/README.md
Just a quick tip to help get people going with shell completions.
> CLI: add example for sourcing completions in shell rc

- rust/src/request.rs
Found some obvious improvements while getting refreshed on this to replace more of the current generated code.
> rust: Clean up internal request module

- rust/src/apis/application_api.rs
- rust/src/apis/authentication_api.rs
- rust/src/apis/background_tasks_api.rs
- rust/src/apis/broadcast_api.rs
- rust/src/apis/endpoint_api.rs
- rust/src/apis/environment_api.rs
- rust/src/apis/environment_settings_api.rs
- rust/src/apis/event_type_api.rs
- rust/src/apis/events_api.rs
- rust/src/apis/health_api.rs
- rust/src/apis/inbound_api.rs
- rust/src/apis/integration_api.rs
- rust/src/apis/message_api.rs
- rust/src/apis/message_attempt_api.rs
- rust/src/apis/statistics_api.rs
- rust/src/apis/stream_api.rs
- rust/src/apis/stream_event_types_api.rs
- rust/src/apis/transformation_template_api.rs
- rust/src/apis/webhook_endpoint_api.rs
- rust/src/request.rs
- rust/templates/hyper/api.mustache
This was more code for worse performance, and easily fixed :)
> rust: Remove unnecessary String allocations

- bridge/svix-bridge-plugin-queue/src/sender_input/mod.rs
- rust/Cargo.toml
- rust/src/lib.rs
> Make CI happy

- ChangeLog.md
- go/application.go
- go/application_ext.go
- go/authentication.go
- go/endpoint.go
- go/event_type.go
- go/message_attempt.go
- go/statistics.go
- go/svix.go
Closes https://github.com/svix/monorepo-private/issues/9576.
> go: Replace most of the lib with generated code

- server/svix-server/src/static/docs.html
> Work around visual bug in redoc

- ChangeLog.md
- go/event_type.go
- go/message.go
- go/message_attempt.go
- go/operational_webhook_endpoint.go
> go: Pull in some more changes from codegen

- python/svix/api/message.py
- python/svix/api/message_attempt.py
- python/svix/models/app_portal_access_in.py
One small change from the generator, one small change from the spec.
> python: Update generated code

- .dockerignore
- .github/workflows/cli-docker-release.yml
- svix-cli/Dockerfile
It could be useful in some environments.
> Svix CLI: release the CLI as a docker image.

- rust/src/api/client.rs
- rust/src/api/mod.rs
- svix-cli/src/cmds/api/endpoint.rs
- svix-cli/src/cmds/api/integration.rs
- svix-cli/src/cmds/api/message.rs
- svix-cli/src/cmds/api/message_attempt.rs
… to prepare for generating api/mod.rs.
> rust: Move Svix, SvixOptions into a separate module

- csharp/Svix/SvixClient.cs
- csharp/Svix/Version.cs
- tools/bump_version.js
> Correct the version.go path in bump_version.js

- .github/workflows/bridge-release.yml
- .github/workflows/cli-docker-release.yml
- .github/workflows/server-release.yml
We don't trigger this job on release so need a different way of getting the tags. This should work.
> Fix docker tags

- .github/workflows/bridge-release.yml
- .github/workflows/cli-docker-release.yml
- .github/workflows/server-release.yml
* Ensure docker tags are getting exported properly and that the full commmit history is checked out so that we get the tags as well.
* Fix artifact names in bridge release
> More Docker release fixes

- rust/src/api/client.rs
- server/svix-server/src/queue/redis.rs
https://rust-lang.github.io/rust-clippy/master/index.html#double_ended_iterator_last
https://rust-lang.github.io/rust-clippy/master/index.html#doc_overindented_list_items
> rust: Make clippy happy

- kotlin/deploy.gradle
> kotlin: Add dependsOn for `generateMetadataFileForMavenPublication`

- kotlin/deploy.gradle
> kotlin: Fix build again

- java/build.gradle
> java: Can't use `+` in version string

- ruby/lib/svix/application_api.rb
- ruby/lib/svix/errors.rb
- ruby/lib/svix/message_api.rb
- ruby/lib/svix/message_attempt_api.rb
- ruby/lib/svix/svix.rb
- ruby/lib/svix/util.rb
- ruby/lib/svix/webhook.rb
- ruby/spec/kitchen_sink_spec.rb
- ruby/spec/message_api_spec.rb
- ruby/spec/webhook_spec.rb
All of these changes are from
```bash
rubyfmt lib/ -i
rubyfmt spec/ -i
```
> Run formatter on Ruby lib

- regen_openapi.sh
- rust/src/api/mod.rs
- svix-cli/src/cmds/api/application.rs
- svix-cli/src/cmds/api/authentication.rs
- svix-cli/src/cmds/api/endpoint.rs
- svix-cli/src/cmds/api/event_type.rs
- svix-cli/src/cmds/api/integration.rs
- svix-cli/src/cmds/api/message.rs
- svix-cli/src/cmds/api/message_attempt.rs
- svix-cli/templates/api_resource.rs.jinja
The codegen template added here has some slight modifications to the one we were using before, as can be seen from the diff of src/cmds/api.
> cli: Add codegen template and regenerate

- openapitools.json
- package.json
- regen_openapi.sh
- yarn.lock
> Remove remaining references to OpenAPI generator

- java/lib/src/main/java/com/svix/api/IngestEndpoint.java
- java/lib/src/main/java/com/svix/api/IngestEndpointCreateOptions.java
- java/lib/src/main/java/com/svix/api/IngestEndpointListOptions.java
- java/lib/src/main/java/com/svix/api/IngestEndpointRotateSecretOptions.java
- java/lib/src/main/java/com/svix/api/Message.java
- java/lib/src/main/java/com/svix/models/ExpungeAllContentsOut.java
- java/lib/src/main/java/com/svix/models/IngestEndpointHeadersIn.java
- java/lib/src/main/java/com/svix/models/IngestEndpointHeadersOut.java
- java/lib/src/main/java/com/svix/models/IngestEndpointIn.java
- java/lib/src/main/java/com/svix/models/IngestEndpointOut.java
- java/lib/src/main/java/com/svix/models/IngestEndpointSecretIn.java
- java/lib/src/main/java/com/svix/models/IngestEndpointSecretOut.java
- java/lib/src/main/java/com/svix/models/IngestEndpointUpdate.java
- java/lib/src/main/java/com/svix/models/ListResponseIngestEndpointOut.java
- java/templates/api_extra/application_create.java
- java/templates/api_extra/message.java
- java/templates/api_resource.java.jinja
- java/templates/component_type.java.jinja
- java/templates/operation_options.java.jinja
- java/templates/types/integer_enum.java.jinja
- java/templates/types/string_enum.java.jinja
- java/templates/types/struct.java.jinja
- regen_openapi.sh
Pull in Java templates from the `openapi-codegen` repo
Also pull in latest changes from `lib-openapi.json`
For now `regen_openapi.sh` for Java is disabled in CI
> java: Pull in change from latest codegen

- java/lib/src/main/java/com/svix/api/Message.java
- java/lib/src/test/com/svix/test/WiremockTests.java
- java/lib/src/test/resources/__files/ExpectedMsgCreateBody.json
- java/lib/src/test/resources/__files/ExpectedMsgCreateBody2.json
- java/lib/src/test/resources/__files/ExpectedMsgCreateBodyWithHeaders.json
- java/templates/api_extra/message.java
- java/templates/api_extra/message_create_body.java
- java/templates/api_resource.java.jinja
- kotlin/lib/src/main/kotlin/Message.kt
- kotlin/lib/src/main/kotlin/SvixHttpClient.kt
- kotlin/lib/src/test/com/svix/kotlin/BasicTest.kt
- kotlin/lib/src/test/com/svix/kotlin/WiremockTests.kt
- kotlin/templates/api_extra/message.kt
- kotlin/templates/api_extra/message_create_body.kt
- kotlin/templates/api_resource.kt.jinja
Fixes regression introduced in https://github.com/svix/svix-webhooks/pull/1783
> java/kotlin: Send empty struct instead of empty string

- regen_openapi.py
> Exit from regen script if any subprocess fails

- codegen.toml
- rust/src/models/mod.rs
- rust/templates/component_type_summary.rs.jinja
We're adding a bunch of stuff soon, don't want to update `mod.rs` by hand.
> rust: Add template for models/mod.rs

- rust/src/models/ingest_source_in.rs
- rust/src/models/ingest_source_out.rs
- rust/src/models/mod.rs
- rust/templates/component_type_summary.rs.jinja
- rust/templates/types/struct_enum.rs.jinja
- rust/tests/it/model_serialization.rs
Follow-up to https://github.com/svix/svix-webhooks/pull/1754, https://github.com/svix/svix-webhooks/pull/1797.
> rust: Some fixes for the new Ingest Source API

- csharp/Svix/Environment.cs
- csharp/Svix/Message.cs
- java/lib/src/main/java/com/svix/api/Environment.java
- java/lib/src/main/java/com/svix/api/Message.java
- javascript/src/api/environment.ts
- javascript/src/api/message.ts
- javascript/src/api_internal/eventsPublic.ts
- javascript/src/models/pollingEndpointConsumerSeekIn.ts
- javascript/src/models/pollingEndpointConsumerSeekOut.ts
- javascript/src/models/pollingEndpointMessageOut.ts
- javascript/src/models/pollingEndpointOut.ts
- kotlin/lib/src/main/kotlin/Environment.kt
- kotlin/lib/src/main/kotlin/Message.kt
- lib-openapi.json
- python/svix/api/message.py
- rust/src/api/environment.rs
- rust/src/api/message.rs
- svix-cli/src/cmds/api/environment.rs
- svix-cli/src/cmds/api/message.rs
… for documentation improvements.
> Update lib-openapi.json and regenerate libs

- java/.gitignore
- kotlin/.gitignore
We no longer have java/lib/generated and kotlin/lib/generated.
> Update gitignore files

- codegen.toml
- csharp/Svix/OperationalWebhook.cs
- csharp/Svix/SvixClient.cs
- csharp/templates/api_resource.cs.jinja
Part of https://github.com/svix/monorepo-private/issues/10043.
> csharp: Add support for sub-resources

- codegen.toml
- java/lib/src/main/java/com/svix/Svix.java
- java/lib/src/main/java/com/svix/api/OperationalWebhook.java
- java/templates/api_resource.java.jinja
Part of https://github.com/svix/monorepo-private/issues/10043.
> java: Update template to support sub-resources

- codegen.toml
- javascript/src/api/operationalWebhook.ts
- javascript/src/api_internal/beta.ts
- javascript/src/api_internal/betaConnector.ts
- javascript/src/api_internal/message.ts
- javascript/src/api_internal/stream.ts
- javascript/src/index.ts
- javascript/templates/api_resource.ts.jinja
Part of https://github.com/svix/monorepo-private/issues/10043.
> js: Update api_resource template to support sub-resources

- codegen.toml
- go/application.go
- go/authentication.go
- go/background_task.go
- go/endpoint.go
- go/environment.go
- go/event_type.go
- go/integration.go
- go/message.go
- go/message_attempt.go
- go/operational_webhook.go
- go/operational_webhook_endpoint.go
- go/statistics.go
- go/svix.go
- openapi-templates/go/api_resource.go.jinja
Part of https://github.com/svix/monorepo-private/issues/10043.
> go: Add support for sub-resources

- codegen.toml
- ruby/lib/svix.rb
- ruby/lib/svix/api/ingest.rb
- ruby/lib/svix/api/operational_webhook.rb
- ruby/lib/svix/svix.rb
- ruby/templates/api_resource.rb.jinja
- ruby/templates/summary.rb.jinja
Closes https://github.com/svix/monorepo-private/issues/10043.
> ruby: Update api_resource template to support sub-resources

- go/events_public.go
- go/models.go
- go/models/polling_endpoint_consumer_seek_in.go
- go/models/polling_endpoint_consumer_seek_out.go
- go/models/polling_endpoint_message_out.go
- go/models/polling_endpoint_out.go
> go: Pull in changes form latest codegen

- codegen.toml
- csharp/Svix/Ingest.cs
- csharp/Svix/IngestEndpoint.cs
- csharp/Svix/SvixClient.cs
- go/ingest.go
- go/ingest_endpoint.go
- go/ingest_source.go
- go/svix.go
- java/lib/src/main/java/com/svix/Svix.java
- java/lib/src/main/java/com/svix/api/Ingest.java
- javascript/src/api/ingest.ts
- javascript/src/api/ingestSource.ts
- javascript/src/index.ts
- javascript/src/mockttp.test.ts
- kotlin/lib/src/main/kotlin/Ingest.kt
- kotlin/lib/src/main/kotlin/Svix.kt
- python/svix/api/ingest.py
- python/svix/api/svix.py
CLI support will be a separate PR because it requires slightly more work.
All the new files are generated (as indicated by comments), but changes to existing files were made by hand.
> Add Ingest API to all libs

- .github/workflows/bridge-ci.yml
- bridge/svix-bridge/src/config/mod.rs
- bridge/svix-bridge/src/main.rs
- bridge/svix-bridge/src/webhook_receiver/mod.rs
Work around https://github.com/actions/runner-images/issues/11926.
> ci: Work around upstream breakage

- server/Cargo.lock
- server/Cargo.toml
- server/svix-server/Cargo.toml
- server/svix-server_derive/Cargo.toml
- tools/bump_version.js
… and use the same version for the derive crate.
> Set server version via workspace manifest

- .github/workflows/cli-lint.yml
- .github/workflows/cli-security.yml
- .github/workflows/csharp-lint.yml
- .github/workflows/go-ci.yml
- .github/workflows/go-lint.yml
- .github/workflows/java-lint.yml
- .github/workflows/javascript-lint.yml
- .github/workflows/kotlin-lint.yml
- .github/workflows/ruby-lint.yml
- .github/workflows/rust-lint.yml
Some of these CI workflows were not triggered on a push to main
> Add CI for libs to push on main

- server/Dockerfile
Easier to maintain than the previous hack :)
> Use cargo-chef for better Docker layer caching

- codegen-templates/javascript/types/struct_enum.ts.jinja
- javascript/src/models/ingestSourceIn.ts
- javascript/src/models/ingestSourceOut.ts
This will allow us to add the sink type struct enums, without tsc yelling at us
> Add fix for JS struct enums

- codegen-templates/javascript/summary.ts.jinja
- codegen.toml
Pulls in some changes from monorepo, and modifies the summary template.
The `src/index.ts` is now fully generated.
I will open a PR in monorepo to sync (again) the changes I make here to the template.
> js: Generate the index.ts

- README.md
closes: https://github.com/svix/monorepo-private/issues/10373
> Add terraform to readme

- codegen.toml
- csharp/Svix/Models/IngestSourceIn.cs
- csharp/Svix/Models/IngestSourceOut.cs
- go/internalapi/management.go
- go/internalapi/management_authentication.go
- go/internalapi/management_environment_settings.go
- go/models/api_token_expire_in.go
- go/models/api_token_in.go
- go/models/api_token_out.go
- go/models/ingest_source_in.go
- go/models/ingest_source_out.go
- go/models/settings_internal_patch.go
- java/lib/src/main/java/com/svix/models/IngestSourceIn.java
- java/lib/src/main/java/com/svix/models/IngestSourceOut.java
- java/lib/src/test/com/svix/test/ModelTests.java
- javascript/src/models/ingestSourceIn.ts
- javascript/src/models/ingestSourceOut.ts
- kotlin/lib/src/main/kotlin/models/IngestSourceIn.kt
- kotlin/lib/src/main/kotlin/models/IngestSourceOut.kt
- lib-openapi.json
- python/svix/models/ingest_source_in.py
- python/svix/models/ingest_source_out.py
- python/tests/test_httpretty.py
- ruby/lib/svix/models/ingest_source_in.rb
- ruby/lib/svix/models/ingest_source_out.rb
- rust/src/models/ingest_source_in.rs
- rust/src/models/ingest_source_out.rs
- rust/tests/it/model_serialization.rs
Also fixed a bunch of tests + added some more routes to the internal go lib
> Bump openapi spec

- codegen-templates/javascript/types/struct_enum.ts.jinja
- javascript/src/models/ingestSourceIn.ts
- javascript/src/models/ingestSourceOut.ts
This will help Lucho with an upcoming frontend thing.
> js: Add generate an empty struct for variants without a config.

- bridge/Cargo.lock
- bridge/svix-bridge.example.receivers.yaml
- bridge/svix-bridge/Cargo.toml
- bridge/svix-bridge/src/config/mod.rs
- bridge/svix-bridge/src/http_output.rs
- bridge/svix-bridge/src/main.rs
Closes https://github.com/svix/monorepo-private/issues/10975.
> Add http receiver output

- java/deploy.gradle
- kotlin/deploy.gradle
These 2 are the new urls needed to publish
Source: https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#configuring-your-plugin
Closes https://github.com/svix/monorepo-private/issues/10782
> Fix java and kotlin publishing

- codegen/lib-openapi.json
- csharp/Svix/Models/EndpointHeadersPatchIn.cs
- go/models/endpoint_headers_patch_in.go
- java/lib/src/main/java/com/svix/models/EndpointHeadersPatchIn.java
- javascript/src/models/endpointHeadersPatchIn.ts
- kotlin/lib/src/main/kotlin/models/EndpointHeadersPatchIn.kt
- python/svix/models/endpoint_headers_patch_in.py
- ruby/lib/svix/models/endpoint_headers_patch_in.rb
- rust/src/models/endpoint_headers_patch_in.rs
Adds `delete_headers` to `EndpointHeadersPatchIn`
> Pull in changes from openapi.json

- bridge/svix-bridge/src/webhook_receiver/mod.rs
This function was overly complex. Found while looking into https://github.com/svix/monorepo-private/issues/11136.
> bridge: Simplify webhook_receiver::route

- javascript/package.json
- javascript/yarn.lock
These dependencies were unused
> ts: Remove unused dependencies
