svix/svix-webhooks

.github/workflows/other-lint.yml
README.md
go.mod
go/application.go
go/authentication.go
go/endpoint.go
go/eventtype.go
go/message.go
go/messageattempt.go
go/svix.go
go/webhook_test.go
javascript/package.json
php/README.md
ruby/svix.gemspec

We'll want a new release before we start telling people to use `github.com/svix/svix-libs` in go as modules are pretty particular about module declarations matching `go get` paths.

Update Links & Go Module Path to New Github Org: Svix

---

ChangeLog.md
javascript/package.json
python/setup.py
ruby/Gemfile.lock
ruby/src/svix/version.rb

We need a new release in order to change the go import path to `github.com/svix/svix-libs`

Bump version & update changelog

---

python/svix/__init__.py

Export WebhookVerificationError in order to allow catching a validation exception.

Python: Export 'WebhookVerificationError'

---

go/webhook_test.go
java/lib/src/main/java/com/svix/Webhook.java
java/lib/src/test/java/com/svix/WebhookTest.java
javascript/src/webhook.test.ts
php/tests/WebhookTest.php
python/tests/test_receiver.py
ruby/spec/webhook_spec.rb

Assuming that multi-sig payloads will always have all of the signature set as a single `svix-signature` header and not multiple ones.
Closes #55

tests: Add Multi Signature Tests

---

java/deploy.gradle

The previous path caused the built jars to be included in the sources jar, increasing the build size and time

Java: Fix sources generation

---

python/svix/api.py

It looks like the openapi-generator code is checking optional fields as required on return types, I haven't had a chance to dive deep into why it is actually happening but I figure we can just disable it for now which "fixes" the problem, I'll open an issue with openapi about it.
Context:
When making any calls that return classes with optional fields it checks them as required and errors out.
for example:
`svix.message.create("app_ID", MessageIn(event_type="test", payload={}))`
throws:
`svix.openapi_client.exceptions.ApiTypeError: Invalid type for variable 'event_id'. Required value type is str and passed type was NoneType at ['received_data']['event_id']`

Python: Disable return type checking

---

java/build.gradle

Should have happened with the 5.2.0 bump was gonna do this in #111, but we should just pull it into a separate PR.

Java: bump dependencies

---

java/lib/src/main/java/com/svix/exceptions/ApiException.java

Not all openapi internal exceptions set the message, which when printing, gives you minimal context unless the user calls `getCode()` or `getResponseBody()`.  One solution is to override the getMessage() function to return the body if the message is missing.
A more 'complete' solution is probably to try and parse the body and set the message to the `error detail`, both are trivial, here I parse the body and try to extract the detail, otherwise we default back to the responseBody.
Before:
```
com.svix.exceptions.ApiException:
```
After
```
com.svix.exceptions.ApiException: Invalid token. (authentication_failed)
```
Fixes #129.

Java: APIException set error message to error detail if possible

---

ruby/lib/svix.rb

Using the latest version of the gem in Ruby 2.7 raises `! Unable to load application: LoadError: cannot load such file -- Base64`
This is because the library needs to be required as 'base64' (no caps)

ruby: Use proper case when requiring 'base64' library

---

package-lock.json
package.json

We're still locked on openapi-generator 5.2.0 so this has no impact on the templates themselves.

deps: Upgrade openapi-generator-cli and it's dependencies

---

ruby/lib/svix/endpoint_api.rb

endpoint_in was supposed to be endpoint_update

ruby: fix endpoint.update parameters

---

go/svix.go
java/lib/src/main/java/com/svix/Svix.java
java/lib/src/main/java/com/svix/SvixOptions.java
javascript/src/index.ts
kotlin/lib/src/main/kotlin/Application.kt
kotlin/lib/src/main/kotlin/Authentication.kt
kotlin/lib/src/main/kotlin/Endpoint.kt
kotlin/lib/src/main/kotlin/EventType.kt
kotlin/lib/src/main/kotlin/Message.kt
kotlin/lib/src/main/kotlin/MessageAttempt.kt
kotlin/lib/src/main/kotlin/SvixOptions.kt
python/svix/api.py
ruby/lib/svix/svix.rb

This is currently used for testing, but will be also used for
multi-region support.

Add a way to set a custom server url for all of the libs.

---

kotlin/templates/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache

Though I'm not sure where the message in https://github.com/svix/svix-libs/issues/191 was seen, this looks to  be the root cause of the leak.

Kotlin close tries to avoid memory leak

---

javascript/package.json
javascript/yarn.lock

Uses a fork of isomporphic-fetch which enables keepalives if using node-fetch.  Should significantly improve performance for subsequent requests in node, with no performance change when running in a browser context.
For changes see: https://github.com/svix-frank/isomorphic-fetch/commit/fa230b6d27d2d6de1861d4edef58ca116eff38bf
Cursory review greatly improves performance:
Before:
```
calling create message...
Call took 404.8625639677048 milliseconds
calling create message...
Call took 300.6274639368057 milliseconds
```
After:
```
calling create message...
Call took 412.2045749425888 milliseconds
calling create message...
Call took 119.86126601696014 milliseconds
```

JS: Enable keepalives if using node-fetch

---

javascript/package.json
javascript/yarn.lock

Should solve name/cache clashes for all users

JS: Use svix-fetch from npm

---

ruby/lib/svix.rb

Ran into an issue with order of imports after upgrading to Monterey

Ruby: Ensure uri is imported at gem initialization

---

python/requirements-dev.txt

Fixes issue with typed-ast being a hard requirement (which is not supported in 3.9)

Python: Update mypy

---

python/svix/api.py

Listing of messages and listing of attempts per endpoint can 
have channel passed in through the options parameter, in the same way
these can already be filtered by limit or event_type

Python: Add filter by channel for message list APIs

---

server/svix-server/Cargo.toml
server/svix-server/migrations/20220218061228_endpoint_headers.down.sql
server/svix-server/migrations/20220218061228_endpoint_headers.up.sql
server/svix-server/src/core/types.rs
server/svix-server/src/db/models/endpoint.rs
server/svix-server/src/v1/endpoints/endpoint.rs

Add GET and PUT routes for retrieving and adding Endpoint Headers
Represent headers as jsonb column in database; support basic validation of header names and values upon creation using functionality in 'http' crate; mask sensitive headers on retrieval.

Implement GET/PUT for Endpoint Headers

---

python/.openapi-generator-ignore

We have a new requirement that doesn't come from the generator
so we shouldn't regenerate this file anymore.

Python: Don't regen requirements.txt

---

README.md

A Redis version 6.2.0 or higher is required to run the server in Redis mode because of the use of the `BLMOVE` operation.
The README has been updated to specify the minimum version.

README: Include minimum Redis version

---

server/svix-server/src/queue/mod.rs
server/svix-server/src/worker.rs

Adds unit testing for `generate_msg_headers` and the in memory implementation of the queue.

Add additional unit testing

---

javascript/src/index.ts

The JS templates erroneously sets the IdempotencyKey to literal string `undefined` if idempotencyKey is undefined.  This is extremely bad behavior, a quick fix is to set it to "" which is ignored by the API.  I will follow up with a fix to the templates shortly.

JS: IdempotencyKey, default to empty string

---

javascript/src/index.ts
javascript/templates/api/api.mustache
regen_openapi.sh

This is a follow up to #273, #273 was a hotfix to set the idempotency key to an empty string if not set which works with our current server implementation but is way to fragile.  This updates the generator templates to properly ignore undefined fields.

Javascript: Update Templates to conditionally set headers only if defined

---

server/svix-server/src/core/types.rs
server/svix-server/src/v1/endpoints/endpoint.rs

Implement PATCH method for updating endpoint headers; update axum extension setup to remove deprecated APIs
Merge new/modified headers with existing

server: PATCH Endpoint Headers

---

.github/workflows/server-ci.yml
server/testing-docker-compose.yml

Launches PostgreSQL and Redis via the  `docker-compose.yml` for the server before running unit tests.

Launch dependencies before server unit tests

---

javascript/src/index.ts

The bump script erroneously updated this message, now that we are past this version it won't happen again.

JS: Fix deprecation version

---

java/README.md
java/build.gradle
java/deploy.gradle
kotlin/README.md
kotlin/build.gradle
kotlin/deploy.gradle

Upgrades our build scripts to support uploading, closing, and releasing the Java and Kotlin libraries via CLI.  This will allow us to deploy these libraries via CI without requiring any manual intervention (Separate PR incoming for the CI portion).

Java/Kotlin: Support Deploying to Maven via CLI

---

.github/workflows/server-ci.yml

This CI check currently just shows up as `check` so you have to click through to see what it is.

CI: Add name to Server CI

---

python/svix/api.py
python/templates/model.py.jinja

This is quite a hack, but essentially all "Payload" models should just be Dict[str, Any]
not fancy classes.  This updates the template to check for specific schema names and sets them to
Dict[str, Any] if the names match.

Python: Fix payload typing

---

python/templates/endpoint_macros.py.jinja
python/templates/endpoint_module.py.jinja
python/templates/model.py.jinja

Unstructured dicts such as `payload` and `headers` should be of type
Dict[str, Any] not empty classes.

Python: Fix typing for non-structured dicts

---

.github/workflows/kotlin-release.yml

We should build against LTS not 17

Kotlin: Build for java 11

---

.github/workflows/java-release.yml

We should be building against 11 which is the minimum we wish to support

Java: Build for java 11

---

server/svix-server/src/test_util.rs
server/svix-server/src/v1/endpoints/application.rs

This fixes the issue that we were getting with input not being
exhausted when the response was not empty.
We made it completely ignore the response and always return an empty
response.

Tests: EmptyResponse -> IgnoredResponse and fix parsing issue

---

.github/workflows/server-ci.yml
server/svix-server/Cargo.toml
server/svix-server/src/error.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs
server/svix-server/src/v1/utils.rs

Restructures the crate's `Error` type to report more information and uses this throughout the server.

Implement a more detailed 422 response body

---

.github/workflows/server-release.yml

Revamps the server release CI to enable `aarch64` builds.

Enable more release targets

---

go/internal/openapi/client.go
go/templates/client.mustache
java/templates/libraries/okhttp-gson/ApiClient.mustache
javascript/src/openapi/http/isomorphic-fetch.ts
javascript/templates/api/api.mustache
kotlin/templates/libraries/jvm-okhttp/infrastructure/ApiClient.kt.mustache
ruby/templates/api_client_typhoeus_partial.mustache

For requests coming from svix-libs, it would add clarity to see a unique id for each request. 
Additionally, when retries are made for a request that returns a 5xx status code, there
should be an indication of how many retries were made before either success or retries
were exhausted. 
I've updated the api_client templates for Javascript, Go, Ruby, Java, and Kotlin. Python was already
updated in a previous release. 
Two headers added: 
- "svix-req-id": random 32-bit integer
- "svix-retry-count" an integer that increases on each retry

Libs: Retry headers

---

.github/workflows/server-release.yml

Simply  attempts to fix errors that occur in previous PR #325

Correct CI errors in release publishing and `aarch64` building from PR #325

---

server/Dockerfile

musl is claimed to have performance issues and random DNS bugs.
It's just not worth the hassle, especially given debian-slim should be
fine.
Ref: https://news.ycombinator.com/item?id=30635160
Fixes #302

Change base Docker image to debian-slim

---

server/svix-server/Cargo.toml
server/svix-server/src/core/message_app.rs
server/svix-server/src/v1/endpoints/message.rs

Simply updates the version and fixes compiler errors associated with the update's breaking changes. Motivated by the changes @tasn made for increased sanitation in macros.

Update SeaORM to 0.6.0

---

server/svix-server/src/core/types.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs

This was causing out tests to fail because we were getting messages out of
order as we were getting them within the same second.
Though regardless of that, we want the extra precision.

Switch to KsuidMs for extra precision.

---

server/svix-server/src/v1/endpoints/attempt.rs

The ID is our PK, not the created at.

List attempted messages: sort by ID, not by CreatedAt.

---

.github/workflows/server-ci.yml
server/svix-server/src/core/types.rs
server/svix-server/src/test_util.rs
server/svix-server/src/v1/endpoints/attempt.rs

Adds the endpoint, associated models, a basic test, and associated test utilities. Additionally changes the queue type for CI tests to in-memory to avoid aborted threads mid-database-transaction.

Add implementation for "List Attempts by Endpoint" endpoint

---

server/svix-server/src/core/types.rs

Implements the `Validate` trait for `IdOrUid`  types  created with the `create_all_id_types` macro.

Implement `Validate` for `IdOrUid` types

---

server/svix-server/src/core/security.rs
server/svix-server/src/main.rs
server/svix-server/src/test_util.rs

This removes some redundancy and is needed for other changes I'm making.

Cleanup: make generate_token accept an org_id.

---

server/README.md
server/svix-server/Cargo.toml
server/svix-server/tests/e2e_application.rs
server/svix-server/tests/e2e_attempt.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/e2e_message.rs

We can just use the built-in cargo integration tests filtering now
that they are separate. No need to have our own.
https://github.com/svix/svix-webhooks/pull/342\#issuecomment-1079540525

Tests: remove the integration_test feature and rely on cargo.

---

server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/utils.rs

Add validation tests for query parameters
Unit tests asserting valid/invalid usages of params.

Server: Add query parameter validation tests

---

server/svix-server/src/core/types.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils.rs

Adds `prev` iterators for the `list_attempts_by_endpoint` and `list_attempts_by_msg` endpoints. To be followed by expanding endpoints covered by this structure and to add  `before` and `after` parameters.

Adds `prev` iterators as query filters for `list_attempts_by_endpoint` and `list_attempts_by_msg`

---

server/svix-server/src/db/models/application.rs
server/svix-server/src/db/models/endpoint.rs
server/svix-server/src/db/models/eventtype.rs
server/svix-server/src/db/models/message.rs
server/svix-server/src/db/models/messageattempt.rs
server/svix-server/src/db/models/messagedestination.rs

We want them to be the same because they actually hold the same
information. We show the created_at, but we use the ID for the sorting.
We should probably get rid of created_at down the line because it's
already encoded in the ID, but at least then, make sure they are
identical.

Db models: use the same timestamp for ID and created_at.

---

server/svix-server/tests/e2e_application.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/e2e_event_type.rs
server/svix-server/tests/utils/common_calls.rs
server/svix-server/tests/utils/mod.rs

While doing it, also improved run_with_retries to return the successful value.

Tests: make a common test for testing list endpoints.

---

server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/utils.rs
server/svix-server/tests/e2e_attempt.rs

Extends the `prev_iterator` implementation to include `before`/`after` query parameters and to apply this functionality to all list operations in the attempt API.

Extend `prev_iterator` implementation

---

server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/tests/e2e_attempt.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/utils/common_calls.rs

Add tests to ensure proper functioning of recover-failed-webhooks endpoint. This will validate that particular failed messages are retried an expected number of times based upon message creation time and the `since` time passed to the endpoint.

Tests: Recover failed webhooks

---

server/svix-server/Cargo.toml
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/mod.rs
server/svix-server/tests/e2e_event_type.rs
server/svix-server/tests/e2e_message.rs

Bump `axum` version to 0.5.1, fix associated compilation errors, and fix errors in tests without trailing slashes.

Bump axum version

---

server/svix-server/tests/utils/mod.rs

Fixes a newly present `clippy` lint in the test utility functions.

Fix clippy lint in several points in tests/utils/mod.rs

---

python/svix/api.py

Set the timeout to 10s, and fixed the type warning when instantiating the client.

Python: set a 15s read timeout.

---

python/svix/api.py

There's no need to return the content in the API calls, we can
just reconstruct it locally.

Python: set with_content to false when making API calls.

---

server/svix-server/src/v1/endpoints/message.rs

I don't know how it got there, but it should have always been a ?.

Remove unwrap in create_message.

---

server/svix-server/src/core/types.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/tests/e2e_endpoint.rs

Ensure that incoming endpoint secrets are validated; this also fixes a possible panic in deserialization when an invalid secret shorter than the key prefix is submitted.

Add EndpointSecret Validation

---

server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/utils.rs

Validate that incoming strings do not contain control sequences.
A custom Validator function was created in utils.rs that checks strings against the regex `r"[\x00-\x08]"`, and implemented on request struct fields of type String.

Validate input strings against control sequences

---

server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/utils/mod.rs

Add tests for filtering by msg channels and endpoint header validation/sending

Add additional endpoint integration tests

---

server/svix-server/tests/utils/mod.rs

Blocking sleep would block the whole execution thread.

Test utils: use tokio sleep, not blocking sleep when retrying.

---

server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/utils/common_calls.rs
server/svix-server/tests/utils/mod.rs

This should improve test stability by validating the number of msg
attempts before recording `since` times rather than simply sleeping
for an assumed-to-be-sufficient duration

Rust: Refactor `test_recovery_expected_retry_counts` integration test

---

server/svix-server/src/core/mod.rs

By default, serde_json serializes into "compact" JSON strings, i.e. strings with no extra spaces - comparable to output from JSON.stringify. This test simply demonstrates that this is the case.

test that serde’s JSON serializations are compact

---

server/svix-server/src/v1/endpoints/health.rs

Patches our /health endpoint to simply return a status code.
Fixes #396.

Patch health endpoint to only return a status code

---

server/svix-server/config.example.toml
server/svix-server/src/cfg.rs

It's faster than redis (duh), and it makes things simpler when using
a redis for the queue as the cache can be ephemeral and the queue
shouldn't be.

Change default cache type to memory and improve its docs.

---

README.md
server/svix-server/config.default.toml
server/svix-server/src/cfg.rs

There's no reason why to have two default configurations when rust
supports embedding files at compile time.
I also added missing documentation regarding the redis queue.

Remove redundant default config and improve its docs

---

server/svix-server/src/lib.rs

The first service added is the last invoked, and we want the logging
service to be called even with the idempotency short-circuits invocation
and doesn't actually process the request in the API.

Idempotency: add the service first to fix logging.

---

server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/utils.rs

We don't currently support a prev iterator in all the routes so
we shouldn't be returning a prev iterator there.

Lists: don't output prev_iterator when not supported.

---

README.md

Just noticed the libs one is wrong and the server one doesn't autoscroll to the readme

Readme: Update links to dev guides

---

.github/workflows/server-ci.yml

We weren't setting the server subdirectory so the caching wasn't
actually working.
This change also removed the multi-step checks in order to make the CI
even faster.
Fixes #329

Server CI: fix caching to actually work

---

server/svix-server/src/worker.rs

If parsing a message attempt's response body as a string fails, then base64 encode the response body bytes, and persist that.

Gracefully handle non-text endpoint response bodies

---

server/svix-server/src/core/types.rs
server/svix-server/tests/e2e_endpoint.rs

Preserves the capitalization of header keys, removes a unit test that enforced lowercasing of keys, and adds an integration test that validates key capitalization is persisted as received.

Preserve header key capitalization

---

csharp/Svix/Abstractions/IEndpoint.cs

C#: fix library compilation (change in endpoint headers)

---

server/svix-server/src/queue/memory.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/worker.rs

This modifies queue receivers to potentially return batches instead
of single messages.

Rust: TaskQueueReceive Receive to ReceiveAll

---

server/svix-server/migrations/20220506181355_remove_updated_at_from_static_entities.down.sql
server/svix-server/migrations/20220506181355_remove_updated_at_from_static_entities.up.sql
server/svix-server/src/db/models/message.rs
server/svix-server/src/db/models/messageattempt.rs

Removes the updated_at timestamp columns from tables where rows are virtually immutable.
Requires migration: `cargo sqlx migrate run`

Remove updated_at from static entities

---

.github/workflows/server-ci.yml
server/svix-server/src/queue/mod.rs

We missed a couple of cargo warnings because of it.

Server CI: treat warnings as errors and fix them.

---

python/setup.py

The problem was that we weren't explicitly setting the charset/encoding
when loading the README and it's different on every platform.
While the default is utf-8 (I think) on Linux and macOS, it's cp1252 on
Windows. The latter wasn't able to load the README which contains emoji
and other fancy stuff.
This fixes it to use utf-8 explicitly on every platform (like we already
did for another file we load here).
This was reported by a customer on Slack.

Python: fix issue with installing package on windows.

---

server/svix-server/src/lib.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs
server/svix-server/tests/queue.rs

With the integration tests, this adds one test which spreads 1000 message tasks across 20 producer, consumer pairs such as to begin to test how the system would respond to multiple worker instances running at once.
With this change, I also introduced an optional prefix to the Redis queue keys such that tests can be better isolated from production environments as this test assumes an empty queue.

Test queue with many consumers

---

server/svix-server/src/lib.rs
server/svix-server/src/queue/mod.rs
server/svix-server/tests/queue.rs

We don't need ownership of the configuration so don't try and take it.
No need to clone it this way (even though it's an arc), and it just
makes how we want to use it more explicit.

Queue: pass the configuration as reference.

---

server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils.rs
server/svix-server/tests/utils/common_calls.rs

Adds soft and hard caps to the limit for pagination. This is configured via a constant in the `v1::utils` module.
With soft caps no error is returned exceeding the cap, but list responses will use the cap instead of an exceeding value. With hard caps a 422 error is returned if the given limit exceeds the cap.

Add soft and hard caps to pagination limits

---

server/svix-server/src/queue/redis.rs

If the Redis connection is interrupted, the background loop over the
delayed queue should gracefully fail instead of exiting. With this change,
it will continue to operate once the Redis connection is healthy again.

Keep Redis queue worker alive after Redis interruption

---

server/Dockerfile
server/svix-server/src/db/mod.rs
server/svix-server/src/main.rs

Adds a new `--run-migrations` option flag that will run any database
migrations before server startup. Includes this flag in the
Dockerfile CMD.
The existing subcommand, `migrate`, is still supported and unchanged;
it will continue to run migrations and then exit.

--run-migrations option flag

---

.github/workflows/codeball.yml

We don't want it to automatically approve and interfere with
our current workflows. I was told it was less intrusive but
I guess it's not the case.

Remove the codeball automatic code reviewer.

---

server/run-tests.sh
server/svix-server/src/lib.rs
server/svix-server/tests/utils/mod.rs

Previously tests could not run in parallel because multiple Redis queues would steal tasks from each other. This adds a unique prefix to test queue keys allowing them to run in parallel.

Enable running tests in parallel

---

.github/workflows/server-release.yml

On a release to GitHub, in CI, it will now push to multiple tags for Docker Hub. This includes the full version number, trimming to MAJOR.MINOR and trimming to just MAJOR.

Release Docker tags with version numbers on GitHub release

---

.github/workflows/rust-release.yml

It was failing because Git wasn't configure appropriately.

CI: Fix Rust library release code

---

server/svix-server/src/main.rs

At some point a check to only enable logging for debug builds snuck into
the code. This means that logging configuration variables were only
being respected in debug builds and not in production.
The issue was reported on Slack:
https://svixcommunity.slack.com/archives/C022THZCJQ3/p1653606219172509

Fix logging configuration in production builds.

---

server/svix-server/Cargo.toml
server/svix-server/src/v1/endpoints/endpoint/mod.rs

Fixes #478 by validating that the scheme for URLs in any EndpointIn received is http or https.

Validate URL scheme is http or https for EndpointIn

---

server/svix-server/Cargo.toml
server/svix-server/config.default.toml
server/svix-server/src/cfg.rs
server/svix-server/tests/e2e_attempt.rs

This was a mistake that we did when initially creating it.
This change tries to first parse it as an array, and if fails, it falls
back to the previous string parsing behavior.
Fixes #480 and #481

Config: parse retry_schedule as an array not string

---

csharp/Svix/Abstractions/ISvixClient.cs

We were not exposing many needed getters, including the ones for getting
the message creator (and many others).
Without them being exposed, you can't actually interact with the API.
This fixes it.
Fixes #485

C#: expose the missing getters for making it useful

---

server/svix-server/src/v1/endpoints/health.rs

Fixes #489 by renaming `Ok` and `Error` variants to `ok` and `error` in serialized output.

Rename HealthStatusVariants to lowercase via serde

---

server/svix-server/src/core/idempotency.rs
server/svix-server/src/core/security.rs
server/svix-server/src/error.rs
server/svix-server/src/main.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/endpoints/mod.rs
server/svix-server/src/v1/mod.rs
server/svix-server/tests/e2e_auth.rs
server/svix-server/tests/utils/mod.rs

Implements the `/auth/dashboard-access/:app_id/` endpoint and associated permissions changes. This makes it so there are tokens valid only for some endpoints. This is meant so that someone using the Svix service may create a token for the owner of an application under their organization to perform limited operations on what falls under the scope of that application.

Implement Dashboard Access Endpoint

---

server/svix-server/src/main.rs

Corrects the JSON log format to add the `EnvFilter` and to flatten events.
Follow up to #496

Make corrections to JSON log format

---

server/svix-server/src/main.rs

Fixes a panic caused by improper `tracing_subscriber` configuration in JSON log mode.

Work around panic caused with JSON logs

---

README.md
server/svix-server/config.default.toml
server/svix-server/src/cfg.rs
server/svix-server/src/core/cache/redis.rs
server/svix-server/src/db/mod.rs
server/svix-server/src/lib.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/redis/mod.rs
server/svix-server/tests/queue.rs

Adds two configuration variables, `db_pool_max_size` and `redis_pool_max_size`.
They both control the maximum connections created in the connection pool for Postgres and Redis respectively.
They default to 20 maximum connections and have a minimum value of 10.
Fixes #490

Add cfg for max pool connections to DBs

---

python/requirements-dev.txt
python/requirements.in/development.txt
python/setup.py

httpx had a CVE: CVE-2021-41945
We were not affected by it because it uses code paths that we don't use,
though being a dependency we were still forcing an old version which is
not good.
We would have updated it before, but openapi-python-client was blocking
us. They just relesaed a version.

Python: update httpx and openapi-python-client.

---

server/svix-server/src/main.rs

A deprecated function was being called in the clap macro due to changes in their API. The issue is described here https://github.com/clap-rs/clap/issues/3822.

Fix clippy warning caused by clap derive macro

---

server/svix-server/src/cfg.rs
server/svix-server/src/v1/endpoints/auth.rs

This shouldn't be used for now, and is only used for internal purposes.
In the future we may want to expose it in the configuration to make it
easy to implement custom application portals.
We just don't want to do it yet to not force us to have the URL structure
a de-facto API.

Server: make the application portal URL configurable.

---

rust/src/error.rs

This fixes a bug in the Rust lib where validation errors are returned on any HTTP status but unprocessable entity and HTTP errors are only returned on unprocessable entity responses by swapping the variants in the conversion from another error type.

Swap validation and HTTP error variants in error conversion code

---

server/svix-server/src/main.rs

It was very confusing before and confused both myself and a customer
when we were trying to figure out why migrations are failing, when
in fact they were not.

Server: clarify the error message to show migrations have ran.

---

README.md
server/svix-server/Cargo.toml
server/svix-server/config.default.toml
server/svix-server/src/cfg.rs
server/svix-server/src/core/message_app.rs
server/svix-server/src/core/mod.rs
server/svix-server/src/core/operational_webhooks.rs
server/svix-server/src/core/security.rs
server/svix-server/src/lib.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/worker.rs
server/svix-server/tests/e2e_operational_webhooks.rs

Sends "operational webhooks" about the status of endpoints and messages as per the models defined here: https://api.svix.com/docs#tag/Webhooks.

Send operational webhooks from worker and endpoint API

---

server/docker-compose.yml

While this file was not originally intended for production use, it can
definitely be used for that. Additionally, production use or not, people
will take inspiration from it, so it's better to be explicit about the
fact that redis should be persisted when used as the queue mechanism.
Fixes #404

Server: enable redis persistence in example docker-compose.

---

server/svix-server/src/core/cache/memory.rs
server/svix-server/src/core/cache/mod.rs
server/svix-server/src/core/cache/none.rs
server/svix-server/src/core/cache/redis.rs

Currently, all values are assumed to be de/serializable as json,
which is not appropriate for all circumstances. This functionality
enables us to store Strings and raw bytes without json de/serialization and
still allowing for type safety of cached data

Server: Add Cache support for getting/setting Strings and raw bytes

---

.github/workflows/server-ci.yml

Because of the git dependency that we have, we need --locked to be
passed, not --frozen. Because we do want to let it access the internet
to check the git repo is fine, but still not actually make any
modifications to the lock file.
This fixes the build in some scenarios.

Server CI: change --frozen to --locked due to git dep

---

server/svix-server/src/core/cache/redis.rs
server/svix-server/src/core/security.rs
server/svix-server/src/core/types.rs
server/svix-server/src/db/models/application.rs
server/svix-server/src/db/models/endpoint.rs
server/svix-server/src/db/models/eventtype.rs
server/svix-server/src/db/models/message.rs
server/svix-server/src/db/models/messageattempt.rs
server/svix-server/src/db/models/messagedestination.rs
server/svix-server/src/error.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/redis/mod.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils.rs
server/svix-server/src/worker.rs
server/svix-server/tests/queue.rs

Currently new Clippy lints in the beta Rust version used in CI are causing runs to fail. This PR fixes these lints.

Fix clippy lints for beta Rust version

---

OpenTelemetry.md
README.md
server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/config.default.toml
server/svix-server/src/cfg.rs
server/svix-server/src/core/mod.rs
server/svix-server/src/core/otel_spans.rs
server/svix-server/src/db/mod.rs
server/svix-server/src/lib.rs
server/svix-server/src/main.rs

This PR integrates OpenTelemetry support and creates middleware for Axum that ensures that the spans created for each request follow OpenTelemetry conventions.
Fixes #344

Implement basic OpenTelemetry support

---

server/svix-server/src/worker.rs

Adds `tracing` spans to the worker inner functions that process individual tasks for the purposes of tracking the timing of dispatch.

Add tracing spans to worker

---

server/Cargo.lock
server/svix-server/Cargo.toml

Adds the "tokio-native-tls-comp" feature flag to our Redis dependency.
Fixes #528.

Support TLS for Redis

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/worker.rs

On retrying the dispatch of a message, add a jitter of plus-minus 20% such that
servers receiving large numbers of webhook events at one moment are less likely
to be overloaded

Implement jitter on message dispatch retries

---

server/svix-server/src/v1/endpoints/message.rs

We support this on api.svix.com due to backwards compatibility, may as
well have it here too.

Server: support accepting msg payload also as "data".

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/core/types.rs
server/svix-server/src/error.rs

The `rand` crate is more high-level, more efficient, faster, and unlike
getrandom, it can't fail.
Fixes #527

Server: use the `rand` crate rather than `getrandom`

---

server/Cargo.lock

We were getting an in `carge deny` because pin-project was yanked, so we
had to update at least that dep. Though took the opportunity to add a
few other deps too.

Server: run `cargo update` to update deps

---

server/svix-server/src/v1/endpoints/attempt.rs

At the moment, when we manually attempt a resend we were just adding a
task to the queue without checking whether the message content even
exists before.
With this change we check before sending, avoiding a confusing error in
the worker.

BE: ensure msg content exists before attempting resend

---

javascript/src/openapi/models/AnyType.ts

It looks like they added a new type in the generation and that we need
to define it.

JS: add a definition for "AnyType" so lib compiles.

---

javascript/src/openapi/models/AnyType.ts
openapi.json
python/templates/model.py.jinja

This is a fix to the change introduced in 05f3f8a5c628a4fe1a1f5655606377e9731dc3fc.
It was an overzealous change where we accidentally changed the null of
the payload where we shouldn't have.
This PR also fixes the Python and JavaScript libs to match this fix.

OpenAPI Schema: don't mark msg payloads as nullable

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/config.default.toml
server/svix-server/src/cfg.rs
server/svix-server/src/core/cryptography.rs
server/svix-server/src/core/mod.rs
server/svix-server/src/core/security.rs
server/svix-server/src/core/types.rs
server/svix-server/src/main.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/endpoint/secrets.rs
server/svix-server/src/worker.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/utils/mod.rs

Webhook secrets are used for signing the webhook messages and they are
stored in the main database and cache. Normally they are stored there in
the clear, which means that people with access to the database could
potentially retrieve them and forge webhook messages.
With this change, we are adding support for an optional secret key that
can be used to encrypt the webhook secrets.
This change is fully backwards compatible when encryption is turned off,
and you can also change from non-encrypted to encrypted whenever you
want and everything will continue to work.
Changing the encryption key, or moving from encrypted to non-encrypted
is not supported, as without the key you won't be able to view endpoint
secrets. We could potentially add a script that migrates the database
from one to the …

Server: add support for encrypting webhook secrets

---

server/svix-server/src/worker.rs

We were not including the error message in the attempt's response which
meant that attempts were missing information on why a request failed.
Was it a timeout? DNS? Impossible to know without this.
This adds it to the attempt response.

Server: include the error message in the attempt's response.

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/lib.rs

We updated tower-http which then complained about bad CORS. So we fixed
the CORS settings and also added the missing CORS cache directive
(max_age).
The main issue was mixing wildcard origin and allow_creds.
It's not actually needed, because we can just explicitly allow the
`Authorization` header which is a better idea anyway because we don't
need creds as we don't support cookie authentication.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
Thanks to @svix-daniel for finding this issue and figuring it out.

Server: update tower-http and fix CORS.

---

.github/workflows/server-ci.yml
server/svix-server/src/main.rs

We need to wait for the db to be ready before attempting to connect to
it. This applies both to the "run migrations" command, and to the run
parameter.

Server: wait-for db before attempting to run migrations

---

server/svix-server/src/queue/memory.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs

Adds simple NACK functionality where messages are reinserted to the back of the
queue with no delay on being marked as not acknowledged.

Implement basic NACK functionality to queue

---

csharp/Svix/Webhook.cs
go/webhook.go
java/lib/src/main/java/com/svix/Webhook.java
javascript/src/index.ts
kotlin/lib/src/main/kotlin/Webhook.kt
php/src/Webhook.php
python/svix/webhooks.py
ruby/lib/svix/webhook.rb
rust/src/webhooks.rs

This PR updates our libraries to optionally take a raw webhook secret.

Update libraries to accept raw webhook secret

---

javascript/src/index.ts

The existing check that `secret`'s is of type string is incorrect. This patches that, allowing Typescript to infer the variable is indeed a string type.

Patch Typescript string check in js library

---

kotlin/lib/src/main/kotlin/Webhook.kt

There were two issues, the first one was that we were using
the primary constructor on the class and it was conflicting
with our secondary ones. The second was that we were trying
to re-assign a val, which we can't do in kotlin.

Kotlin: fix compilation of kotlin lib.

---

.github/workflows/server-ci.yml

Our GitHub Actions CI has been flaky lately with testing failing at running the migrations. This seemingly fixes that by simply starting the dependencies (PostgreSQL and the Redis/Redis cluster) earlier to ensure they have ample time to start.

Reorder stages of server CI

---

README.md

Simply fixes some nonsensical grammar in the README.

Fix incorrect phrasing in README

---

README.md
server/svix-server/src/expired_message_cleaner.rs
server/svix-server/src/lib.rs
server/svix-server/src/queue/memory.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/worker.rs

Adds graceful shutdown to the three main components of the service including
the API server, the worker, and the expired message cleaner.

Add graceful shutdown of service

---

server/svix-server/src/queue/memory.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/worker.rs
server/svix-server/tests/queue.rs

Uses `run_with_retries` on the `send`, `ack`, `nack`, and `receive_all` methods
on the `TaskQueueProducer` and `TaskQueueConsumer` such as to ensure transient
errors do not result in an error response.

Add retries to queue

---

server/svix-server/src/core/cache/mod.rs
server/svix-server/src/core/idempotency.rs
server/svix-server/src/worker.rs

While the `kv_def` macro was there previously, we did not use it in some places
because of the need for custom prefixes. This PR augments the `kv_def` and
`string_kv_def` macros to take an optional string literal to be used as the
`PREFIX_CACHE` constant for the `CacheKey` trait.
Additionally this replaces the two manual implementations of the cache traits
with this new macro syntax.

Add optional cache prefix parameter to kv_def

---

server/svix-server/src/lib.rs

Adds a message stating that the server is shutting down gracefully on receiving SIGTERM/SIGINT.

Add log event on graceful shutdown start

---

deny.toml

An indirect dependency of ours recently included this license with the project. This adds that license to those explicitly allowed in the cargo-deny configuration.

Explicitly allow Unicode-DFS-2016 license in deny.toml

---

go/svix.go

The MessageIn struct has an EventId field of type `openapi.NullableString`. The `openapi.NullableString` is defined in an internal package, so it's impossible to be imported by the end developer.
This PR introduces the `svix.NullableString` public utility to generate an `openapi.NullableString` struct to be used as an `EventId`.

Introduce svix.NullableString utility

---

server/svix-server/src/cfg.rs
server/svix-server/src/lib.rs
server/svix-server/src/queue/mod.rs

Makes miscellaneous improvements to the `ConfigurationInner` validation to provide clearer error messages and avoid validation code scattered elsewhere in the codebase.
The main change is to the Redis DSN validation and the associated helper methods for fetching the key value store backend used by both the queue and the cache.
This also changes the type of the `listen_address` from a `String` to a `SocketAddr` such as to avoid parsing it elsewhere in the code.

Consolidate configuration validation to the cfg module

---

server/svix-server/src/cfg.rs

The default region shouldn't be the EU, but rather self_hosted, so we are
explicit about the region being used rather than claiming to be in the
EU. This was causing issues with the app portal not being able to
detect the token is for a self hosted install.
First step towards fixing #576

Server: set the default region to self_hosted.

---

javascript/package.json
javascript/src/index.ts
javascript/yarn.lock

The TextEncoder API is supported both by Node and by web APIs, so we
should have used it in the first place though we didn't know it was
incomplete.
Essentially the problem is that we used a lib that doesn't support the
full extended utf8 (6 byte) range so it was barfing.
Here's a utf8 sequence that triggers the use (when encoded as string):
```
Uint8Array(21) [
226, 143, 176, 240, 159,
154, 180, 240, 159, 143,
187, 226, 128, 141, 226,
153, 130, 239, 184, 143,
32
]
```
Initially reported on Slack:
https://svixcommunity.slack.com/archives/C022BJ2EBHV/p1659020835781289

JavaScript: change the utf8 encoder to the default node one

---

server/svix-server/config.default.toml
server/svix-server/src/cfg.rs

This adds two configuration values, `redis_dsn` and `cache_dsn` which both will override the default `redis_dsn` when set. This is such that you can use separate Redis instances/clusters for the cache and queue.

Allow overriding redis_dsn for separate queue and cache DSNs

---

ruby/lib/svix/svix.rb

Region detection fails to detect region automatically
Swap the places of the operands around the || operator. That way if the region is detectable using AUTH_TOKEN it will use that, otherwise it will use default url.

Ruby library: fix region detection

---

server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs

Destructures the `self` type into its members inside `ModelIn` implementations where it should be very explicit if a field is to be ignored when updating the database model.

Destructure self in ModelIn impls to avoid forgotten members

---

server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/tests/e2e_application.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/e2e_event_type.rs

This PR enables support for creation of entities during PUT requests if the provided ID did not match an existing record. Affected entities are Application, Endpoint, and Event Type. PUT requests against those entities will now return 200 to indicate the record existed and was modified, or 201 to indicate the record was created.
Closes #603.

Upsert behavior on PUT methods

---

server/svix-server/src/core/types.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils/mod.rs

Previously many of our custom validation errors were passing messages
as error codes, which caused them not to be shown by our current
validation error handling. Fixed this and added method to simplify
proper instantiation of validation errors.

Server: Fix validation errors

---

.github/workflows/rust-lint.yml
.github/workflows/server-ci.yml

rust-lang/rust#100215 on the Rust Beta channel is causing CI builds to fail. This PR temporarily disables CI against the Rust Beta channel, with the expectation that it will be reenabled once the issue has been resolved.

Temporarily disable CI builds against the Rust Beta channel

---

server/svix-server/src/core/message_app.rs
server/svix-server/src/worker.rs

We currently allow expired rotated keys to be used for signing webhooks. This PR filters old_signing_keys based on expiration, so that only unexpired keys can be used for signing.
Fixes #613.

Filter expired keys so they aren't used to sign webhooks

---

.github/workflows/rust-lint.yml
.github/workflows/server-ci.yml
rust/src/webhooks.rs
server/svix-server/src/queue/redis.rs

This PR reverts the changes made in #615, in which we disabled CI builds against Rust Beta due to a bug on that channel.

Reenable CI builds against Rust Beta channel

---

server/svix-server/src/core/cache/redis.rs

This could cause unnecessary panics if a redis connection
error occurs.

Server: Remove unnecessary unwrap in redis cache module

---

python/svix/api.py

Our Python lib had a typo in the European region server URL. This PR
fixes that typo.
Closes #620.

Patch typo in python lib

---

csharp/Svix.Tests/EndpointTests.cs
csharp/Svix.Tests/SvixClientTests.cs
csharp/Svix/SvixClient.cs

This makes the logger optional when creating the SvixClient.
See #624 
Just by removing the null default value on the logger in the constructor makes it behave as I think was intended, that is the logger should be optional.
I also changed a test to make the code compile. I think it is due to the version of openapi-generator has been bumped since the code was checked in.

CSharp lib - make logger optional when Creating SvixClient

---

openapi.json

Updating our docs to include language samples for the new endpoint.getStats method.
Relevant to #628.

Update openapi schema and docs

---

server/svix-server/config.default.toml
server/svix-server/src/cfg.rs
server/svix-server/src/main.rs

Partial fix to the additional request in https://github.com/svix/svix-webhooks/issues/631 which asks for increased logging on PostgreSQL and Redis requests. These changes enables the tracing of SQLx behind a configuration flag.

Allow enabling logging information on PostgreSQL requests

---

server/svix-server/src/core/otel_spans.rs
server/svix-server/src/worker.rs

While we only officially support `info`, `debug`, and `trace` log levels via the configuration, these changes ensure that request and worker spans are entered even if the log level is set to `warn` or `error` via an environment variable override.
Note that, by an error level span, that means that the span is created and entered for every log level, not that it only appears for errors.

Ensure tracing spans are always recorded

---

server/svix-server/src/core/idempotency.rs

It was deemed that a 20 second lock on the `expiry_starting` constant was too long, to the point of potentially causing issue. This change reduces that lock time to 5 seconds.

Update idempotency key lock time from 20s to 5s

---

server/Cargo.lock

The version of `cpufeatures` we depended on was recently updated, and the previous version yanked. This change is simply the result of running `cargo update` to correct this.

Upgrade dependencies of server to avoid yanked version of cpufeatures

---

server/svix-server/src/core/operational_webhooks.rs
server/svix-server/src/core/security.rs
server/svix-server/src/error.rs
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/utils/mod.rs

Ensure that all server-side errors are logged at error level.
Also fix spelling error.

Server: Improve error logging

---

server/svix-server/src/core/cryptography.rs
server/svix-server/src/core/idempotency.rs
server/svix-server/src/core/message_app.rs
server/svix-server/src/core/security.rs
server/svix-server/src/core/types.rs
server/svix-server/src/error.rs
server/svix-server/src/queue/memory.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/headers.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs
server/svix-server/src/v1/endpoints/endpoint/secrets.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/worker.rs

This closes https://github.com/svix/svix-webhooks/issues/574, by adding diagnostic information to the main error type along with some helpful macros.
For internal server errors, we want to visibility into both the underlying error, in addition to where the error originated from. e.g. for code like this
```rust
fn foo() -> crate::error::Result<()> {
let app = Application.fetch(...)?;
app.bar = 12;
app.save()?;
Ok(())
}
```
Just looking at the logs, it can be hard to diagnose whether the underlying db error came from `Application.fetch(...)?` or `app.save()?`.
We want to be able to quickly correlate an error to a specific line, while still keeping error handling relatively boilerplate free.
First, we extend the `error::Error` type with some diagnostic information - literally just the line …

Add file/line information to main error type with macros

---

server/Cargo.lock
server/svix-server/src/core/security.rs

Abstracts the JWT validation and Permissions struct generation logic
in `security.rs` into its own function that can be programmatically
called.
Mostly just whitespace changes / moving code around.

Abstract JWT validation logic into separate function

---

server/svix-server/src/core/security.rs
server/svix-server/src/error.rs

We recently added a `ctx!` macro to help make handling and tracing internal server errors much more straightforward. This PR adds `ctx!` invocations in `security.rs` to a couple of common errors that were being manually transformed.
This also let us axe the `to_internal_server_error` function. `to_internal_server_error` was logging errors, but this was redundant with `error::Error`'s logging in `error.rs` (when it gets turned into a response for axum).
* Cut down boilerplate in `security.rs`
* Add line tracing information to the internal server errors in `security.rs`
* Use the ctx! macro in security.rs
* Implement `Traceable` for the *Rejection types to make `ctx!` work

move security error handling to use ctx macro

---

csharp/Svix/Svix.csproj
csharp/Svix/Webhook.cs

If possible it is always nice to support old Dotnet Framework type of applications (windows only) when publishing a Nuget.
Add support for Netstandard2.0 to project. Now it can be consumed by old Framework 4.7.2 or 4.8 applications.

CSharp-lib: Add netstandard2.0 support

---

.github/linters/.gitleaks.toml

Adds a gitleaks config file so we can whitelist an example key
in our openapi.json spec file.

Add gitleaks config file for CI

---

server/Cargo.lock

Recent Docker releases failed because of a frozen `Cargo.lock` on release. Upon a little investigation it was found that the `Cargo.lock` was slightly out of sync with the `Cargo.toml`. This change will probably fix the Docker releases by ensuring the `Cargo.lock` matches what happens when the current `main` branch is built normally.

Ensure Cargo.lock is up to date with Cargo.toml

---

server/svix-server/src/core/types.rs
server/svix-server/src/db/models/eventtype.rs
server/svix-server/src/error.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/tests/e2e_event_type.rs
server/svix-server/tests/utils/common_calls.rs

The current event-type CRUD is too permissive with the `schema` field. It accepts any json (such as `1`, "foobar", etc.), but it should only accept json objects (such as `{"foo":"bar"}`).
This PR updates the event-type CRUD groups.
In addition, I wanted to support calling `json_wrapper!` outside of types.rs. `types.rs` is already quite large, and I think it makes a bit more sense for types (such as `eventtype::Schema`) to be colocated with other types they interact with.
Finally, I updated the error logging to add trace information for 4xxs. This wasn't strictly necessary, but it made diagnosing the source of 4xxs when testing locally much easier.

Update the event-type CRUD to more strictly enforce Schema type

---

server/svix-server/src/error.rs

While testing, I noticed the following response for unimplemented endpoints
```json
{"code":"not_implemented","detail":"This API endpoint is not yet implented."}
```
That's a typo. Should be "implemented"
Fix the typo.

Fix typo in error message for unimplemented endpoints

---

java/lib/src/main/java/com/svix/Svix.java

The default API client is not safe to reuse;
simply removing the use of it now until we
decide to undertake a more ambitious rewrite
of the default generated API.

Java: Do not use default API Client

---

server/svix-server/src/core/mod.rs
server/svix-server/src/core/permissions.rs
server/svix-server/src/core/security.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/headers.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs
server/svix-server/src/v1/endpoints/endpoint/secrets.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs

This PR refactors `security.rs` and our auth* related axum extractors.
* Cut down on lines-of-code
* Make permission/authorization parsing a bit more intuitive for axum handlers
* Better leverage the type system to restrict axum handlers only to the permission-level information they need.
Some specifics
* Many of our extractors had redundant information, or largely unused fields. This PR removes them
* The `Permissions` struct has been simplified a bit, namely by moving things into an enum (as opposed to using the `type_` enum just as a tag.
* Removed the axum extractor for `Permissions`. We often chain authorization logic on top of the `Permissions`. However, the axum extractor for `Permissions` only authenticates requests, it doesn't authorize them. 
* Fixes a discrepancy between …

Simplify security.rs and authorization logic

---

server/svix-server/src/queue/mod.rs

A followup to #671 which corrects an additional place where stale `QueueTasks` can be left in the Redis queue. This change simply modifies the `nack` method to acknowledge and delete the original task after it's clone has been inserted back into the queue.

Ensure NACKed QueueTasks do not have stale duplicates after reinsertion

---

go/internal/openapi/model_application_in.go
go/internal/openapi/model_application_out.go
go/internal/openapi/model_endpoint_in.go
go/internal/openapi/model_endpoint_out.go
go/internal/openapi/model_endpoint_update.go
go/internal/openapi/model_message_endpoint_out.go
go/internal/openapi/model_settings_in.go
go/internal/openapi/model_settings_out.go
python/templates/model.py.jinja

This fixes the go sdk by running regen_openapi.sh.
The python templates were generating incorrect code. It wasn't accounting for optional fields when constructing responses.
Tested by
* Regenerating the python sdk locally
* Running the server locally with docker-compose and cargo run
* pointing my SDK to the local server
* Creating applications and making sure I didn't get any KeyErrors.
Here's the diff for /python/internal
```
54c54
<         metadata = dict_copy.pop("metadata")
---
>         metadata = dict_copy.pop("metadata", UNSET)
diff -rw svix/internal/openapi_client/models/application_out.py /Users/gabriel/Repos/svix-webhooks/python/svix/internal/openapi_client/models/application_out.py
76c76
<         metadata = dict_copy.pop("metadata")
---
>         metadata = …
```

Fix metadata field in Go and Python SDKs 

---

server/svix-server/tests/e2e_application.rs
server/svix-server/tests/e2e_attempt.rs
server/svix-server/tests/e2e_auth.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/e2e_event_type.rs
server/svix-server/tests/e2e_message.rs
server/svix-server/tests/utils/mod.rs
server/svix-server/tests/worker.rs

Changes the functions for starting a test server to be async
in our e2e test suite.

Change test server spawning to be async

---

server/svix-server/src/queue/redis.rs

As a followup to #671, this change adds logic like the Redis migration functions which clears the queue of acknowledged, stale tasks up to the lowest pending ID. This is run every thirty seconds until there has been a successful trimming of tasks.
The following is a brief explanation of how Redis streams work:
If you `XREADGROUP` it'll be added to the PEL (pending entries list) and thus show up in `XPENDING` until it has been `XACK`ed. But it'll never show up in `XREADGROUP` with that specific consumer group again.
Once `XACK` ed it removes the reference in the PEL, and will show up in neither `XPENDING` or `XREADGROUP`.
It will however remain in the stream and show up via `XREAD` regardless of whether it is `ACK`ed, but we don't do this anywhere. We instead use `XAUTOCLAIM` on items that …

Add queue clearing logic to the Redis migrations

---

server/svix-server/src/db/mod.rs
server/svix-server/src/main.rs
server/svix-server/tests/db.rs

These changes make it possible to completely wipe the PostgreSQL data related to a given organization.
It is invoked like `svix-server  wipe --yes-i-know-what-im-doing org_<id here>`.
While this has been tested to work, the test is ignored such as to reduce the time it takes for CI to run the test suite.
NOTE: Wiping organizations may take a while.

Create subcommand for wiping an organization's data

---

server/svix-server/src/core/security.rs

Improve function to accept a reference to the key directly
instead of the Configuration struct.

Server: Improve `parse_bearer` function

---

server/run-tests.sh
server/svix-server/src/lib.rs
server/svix-server/src/main.rs
server/svix-server/tests/utils/mod.rs

This moves the tracing setup outside of `main.rs` so that tests can use tracing. This emits server logs in failed test runs, which makes diagnosing failed tests much easier, depending on the reason for failing.
There is a small functional change - instead of using `SubscriberInitExt::init`, we now use `SubscriberInitExt::try_init`. init will panic if the subscriber was already setup, whereas try_init will return an `Err(...)`. This doesn't matter in prod, but in tests we end up calling setup_tracing more than once. AFAICT we can safely ignore this error, so we do.

Add tracing to run-tests.sh

---

java/lib/src/main/java/com/svix/Svix.java

Fixes a bug in our Java library that was overwriting any token-based
server resolution to the default Svix server.
Closes #694.

Fix Java library server resolution

---

server/Cargo.lock
server/Dockerfile

This bumps the Rust version 1.65 and runs `cargo update`.
Keep our version of Rust and all dependencies up to date.
Update the dockerfile and run `cargo update`. Don't forget to run `rustup update` locally!

Bump to 1.65 and run cargo update

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/core/types.rs
server/svix-server/src/error.rs

This bumps sea_orm and sqlx to 10.2 and 6.2, respectively. In addition, we clean up some macro hygiene with related type macros that we use for deriving a lot of sea_orm relevant traits.
Aside from the general benefits of upgrading, our current version of sea_orm doesn't support `ON CONFLICT ...` operations, which we need for some upcoming features. So we need to upgrade sea_orm first.
The `DbErr` in sea_orm also exposes the underlying `sqlx::Error` type, so we had to bump the sqlx version as well.
Finally, the macros in `types.rs` weren't fully qualifying their dependencies, which made them difficult to use in the rest of the crate. Since I had to fix a bunch of compile time errors in `types.rs`, I went ahead and fixed the macro hygiene as well.
* Bumped the versions
* Ran `cargo update` …

Bump sea_orm to 10.2 and sqlx to 6.2

---

server/run-tests.sh
server/svix-server/migrations/20221104170041_add_applicationmetadata.down.sql
server/svix-server/migrations/20221104170041_add_applicationmetadata.up.sql
server/svix-server/src/core/permissions.rs
server/svix-server/src/core/types/metadata.rs
server/svix-server/src/core/types/mod.rs
server/svix-server/src/db/mod.rs
server/svix-server/src/db/models/application.rs
server/svix-server/src/db/models/applicationmetadata.rs
server/svix-server/src/db/models/mod.rs
server/svix-server/src/error.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/tests/e2e_application.rs
server/svix-server/tests/e2e_operational_webhooks.rs
server/svix-server/tests/utils/common_calls.rs

This adds the `metadata` field to the application CRUD group.
The `metadata` field is just a JSON dictionary with string only values. This field was added to our public API, but never to our open source solution. This PR corrects that.
We add the field to our `/apps` CRUD group. `Metadata` itself is a separate joined table, instead of a column on the apps field, because metadata can be quite large (up to 4096 bytes).
Because it's a separate model, the sea_orm queries end up being pretty tedious. I tried to keep things efficient and query for both records in a single round trip where possible, but in some places we needed two roundtrips.
A side effect is that the endpoints were starting to get fairly complicated, so I tried to offload a lot of the logic to the relevant `db::models` where …

Adding metadata to application CRUD group

---

server/testing-docker-compose.yml

Due to a change in the `bitnami/redis-cluster` Docker image, tests have been failing. These changes to the configuration of the Docker containers should work around the problem.

Correct testing-docker-compose to reflect changes to redis-cluster

---

server/Cargo.lock

This simply is the result of running `cargo update` from the `svix-server` project. This is good to do regularly, and in this case it avoids a now-yanked crate which was causing a security advisory failure.

Run cargo update

---

server/Cargo.lock

A followup to #710 which runs `cargo update` on `svix-server_derive` too to avoid a yanked crate.

Run cargo update for svix-server_derive

---

server/svix-server/src/v1/utils/mod.rs

We use the ListResponse type everywhere where we have lists, and we haven't added prev iterator support for all of them. This means that for those we haven't supported, we were just seeing prevIterator=null which is confusing and wrong.
This change omits the serialization of prev iterator when it's none. At least until we actually get around to implementing it for all of the routes.

Server: omit prevIterator when null.

---

server/svix-server/migrations/20221206214656_missing_msg_dest_endpoint.down.sql
server/svix-server/migrations/20221206214656_missing_msg_dest_endpoint.up.sql

It causes slow querying when trying to get a specific attempt for a message id. This happens in resend message, list attempts by msg and a few other places.

Server: add missing msg id index causing slow querying.

---

server/svix-server/src/queue/redis.rs

Fixes #720 by eliminating an ineffective Redis background task used for clearing previously ACKed queue items created before the fix in #671.

Eliminate ineffective Redis queue background task

---

server/svix-server/config.default.toml
server/svix-server/src/core/cache/mod.rs

This fixes a typo. 
Typos are bad.
Fix the typo.

Fix typo - it's 'database' not 'databse'

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/core/idempotency.rs
server/svix-server/src/core/permissions.rs
server/svix-server/src/core/security.rs
server/svix-server/src/lib.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/headers.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs
server/svix-server/src/v1/endpoints/endpoint/secrets.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/mod.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/tests/e2e_application.rs
server/svix-server/tests/e2e_auth.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/e2e_event_type.rs
server/svix-server/tests/e2e_message.rs
server/svix-server/tests/utils/mod.rs

Keep up with changes in axum.
The way routes were composed before with `nest` is no longer possible, `merge` panics when there's an existing route ending in a slash for which it has already installed a fallback handler. Therefore, each router has to fully qualify its paths.

Update axum to 0.6

---

server/svix-server/migrations/20221215195541_add_endpoint_metadata.down.sql
server/svix-server/migrations/20221215195541_add_endpoint_metadata.up.sql
server/svix-server/src/db/models/endpoint.rs
server/svix-server/src/db/models/endpointmetadata.rs
server/svix-server/src/db/models/mod.rs

This is the initial PR to add metadata support to our OSS. We already have this field for endpoints in our propriety solution, as well as metadata support for applications in the OSS.
This PR just adds the necessary migrations and model boilerplate. That's pretty much it. In future PRs we'll update the CRUD group to make this field visible/configurable to users.

Add endpoint metadata model

---

server/svix-server/src/core/message_app.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/worker.rs

1. Change param order to have org_id first and app_id second - we always go from "large" to small in our parameter order.
2. Make the filtered endpoints function to only get what it needs.
3. Fix cache key to accept references (we only needs refs anyway).

Server: cleanup CreateMessageApp

---

server/svix-server/src/core/operational_webhooks.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs

While adding metadata to the endpoint CRUD group, I noticed some repetitive and boilerplatey logic that made the endpoints harder to read and extend.
This DRYs up some of the `EndpointEvent` and secret generation logic. As a little bonus, the endpoint secret generation code should be a bit more performant since we're no longer cloning the entire input or secret.

Simplify Endpoint CRUD

---

server/svix-server/src/db/models/endpoint.rs
server/svix-server/src/db/models/endpointmetadata.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/e2e_operational_webhooks.rs
server/svix-server/tests/worker.rs

A while ago, we added `metadata` (just a dict of str:str) to applications and endpoints to our app. We also added this field to our application CRUD in the OSS, so it's about time we did the same for endpoints.
This updates the CRUD group for /endpoints to return/configure `metadata`. Most of this pretty straightforward, with a couple of notes
* We don't persist empty Metadata records, just to save space (the model abstracts over this detail pretty well)
* The endpoint/crud methods were getting fat. Since `put` upserts `Endpoint`s, there was some common "update endpoint" / "create endpoint" functions we could extract
* Finally, `EndpointOut` is also used by MessageAttemptOut. I didn't want to add the `metadata` field to the message endpoint, so there's a bit of extra indirection in the …

Add Metadata field to Endpoint CRUD

---

server/svix-server/src/core/permissions.rs
server/svix-server/src/v1/endpoints/event_type.rs

This PR fixes a regression with the `GET /event-type` endpoint.
In [#674](https://github.com/svix/svix-webhooks/commit/cc01b8482202ce7442487a4b5e86850cd3783fc3#diff-2a76cfc85cbfeae62fdc056d281dfa9a9c61fdfcb434435b02993b5cd31ddf58), we refactored a lot of our permission logic so that the `Permission` struct was no longer extracted directly in axum handlers. Instead, a `permission::<Struct>` is extracted instead, which describes the resources the user has authorized access too.
The regression was introduced [here](https://github.com/svix/svix-webhooks/commit/cc01b8482202ce7442487a4b5e86850cd3783fc3#diff-2a76cfc85cbfeae62fdc056d281dfa9a9c61fdfcb434435b02993b5cd31ddf58L176). Originally, `GET /event-type` accepted the `Permission` struct directly - which effectively means any authenticated …

Fix GET /event-types permission regression

---

server/svix-server/src/v1/endpoints/event_type.rs

This fixes the permissions for the singular `GET /event-type/:name` endpoint. This wasn't a regression, we just noticed it's been wrong all this time.
Change the permissions to `ReadAll`, which matches `GET /event-type/`.

Fix GET /event-type/:name permissions

---

server/Dockerfile

Run Docker command with exec so that process will
capture signals properly.

Server: Use `exec` in Dockerfile

---

server/svix-server/src/worker.rs

There was an issue with small payloads (well potentially larger too, but exceedingly unlikely) which could cause the payloads to not serialize correctly which could cause signatures to be incorrect in same rare scenarios likely only affecting small payloads.
If memory serves, serde parses and stringifies json in a non-deterministic way. Normally it would be deterministic, but it also maintains an internal cache of "json structures", and if it thinks that it can reuse one it does. This means that if there's a "cache hit", which I'm not sure about the circumstances, it can reuse one of those and therefore generate a different string.
Why does it matter? Because instead of using the string representation of the payload, we were passing a `Json::Value` around and stringifying and parsing it …

Worker: fix potentially incorrect signatures for some small payloads

---

rust/src/webhooks.rs

There's no reason why it should accept a String, a &str is sufficient.

Rust: fix Webhook verification to accept &str

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/e2e_operational_webhooks.rs
server/svix-server/tests/utils/common_calls.rs

Right now, we call `Url::parse(...)` multiple times on `EndpointIn`'s URL field. This isn't a huge inconvenience, but it's definitely more complicated and inefficient than things need to be.
This PR changes the EndpointIn field to be a URL type instead of a String - leveraging the URL crate's serde (de)serialization to only `Url::parse` once.
The only annoying downside is that `Url` doesn't have a default implementation - so we had to role our own. However, this ended up cleaning up a lot of test logic (since that's all that uses `EndpointIn::default()`), so more likely a win.
In addition, `Url::to_string()` normalizes the URL domain, down-casing the string and adding a trailing `/`. This meant updating a few tests, although this shouldn't be a functionally breaking change for anyone.

Endpoint.URL - change to parse, not validate

---

server/svix-server/src/lib.rs
server/svix-server/src/v1/mod.rs

HTTP routes broke after Axum upgrade to 0.6.0 due to changes
in how nested routes work so that matched routes were displaying
as the literal route in the request rather than a generic route
with placeholders for resource IDs. Adding the otel layer
directly in the nested API route fixes the problem.

Server: Fix Span HTTP Routes

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/core/permissions.rs
server/svix-server/src/core/types/metadata.rs
server/svix-server/src/core/types/mod.rs
server/svix-server/src/db/models/eventtype.rs
server/svix-server/src/error.rs
server/svix-server/src/lib.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/health.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/mod.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/src/v1/utils/patch.rs

Aide is a library that automatically generates an OpenAPI schema by integrating with axum, extracting API information based on axum routing and extractors.
Replace the currently static OpenAPI definition with an automatically generated one, based on code. Among other benefits, it's useful to ensure we don't make breaking changes to the API by accident.
`aide` was chosen as it is lightweight and has the most features out of the box for us. Alternatives considered:
* [`utoipa`](https://github.com/juhaku/utoipa) - integrates with axum like aide but relies heavily on code generation with a lot of annotations that aide is able to derive automatically out of the box
* [`okapi`](https://github.com/GREsau/okapi) - does not integrate with axum out of the box
While aide is newer and perhaps less …

Integrate aide for automatic OpenAPI generation

---

server/svix-server/src/core/types/mod.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs

In our closed source solution, we ensure header values aren't greater than a certain length. We want to add that same validation to our open source solution.
In addition to enforcing a maximum length, I also moved the validation logic into Deserialize, to prevent invalid EndpointHeaders from being created and opening the possibility of forgetting to validate the record.

Add Length limit validation to EndpointHeader value

---

server/svix-server/migrations/20230116095641_add_event_type_feature_flags.down.sql
server/svix-server/migrations/20230116095641_add_event_type_feature_flags.up.sql
server/svix-server/src/core/permissions.rs
server/svix-server/src/core/security.rs
server/svix-server/src/core/types/mod.rs
server/svix-server/src/db/models/eventtype.rs
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/tests/e2e_auth.rs
server/svix-server/tests/e2e_event_type.rs
server/svix-server/tests/utils/common_calls.rs

Organizations might want to introduce new event types without first exposing them to their users. These changes allow adding an optional `feature_flag` to event types. If an event type has a feature flag set then only application tokens which have the corresponding feature flag set can see the event type. This does *not* filter receiving these events on endpoints though.
Event types can now be gated behind a feature flag field. If an event type has a featue flag set then it won't be returned to application access clients that don't have the appropriate event type feature flag claim set in their token.
Organization access tokens can always see all event types.

Add feature flag gating to event types

---

rust/Cargo.toml

Ensure that Rust Svix Client can properly
connect to https endpoints out of the box
by enabling `default-tls` feature in `reqwest`.

Rust: Enable `reqwest` default-tls

---

server/Cargo.lock
server/Cargo.toml
server/run-tests.sh
server/svix-server/Cargo.toml
server/svix-server/config.default.toml
server/svix-server/src/cfg.rs
server/svix-server/src/core/message_app.rs
server/svix-server/src/core/mod.rs
server/svix-server/src/core/webhook_http_client.rs
server/svix-server/src/error.rs
server/svix-server/src/lib.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/src/worker.rs
server/svix-server/tests/integ_webhook_http_client.rs

* Add webhook-http-client, which is based on hyper, enabling several
critical improvements:
* Default filtering of endpoints that resolve to private
address space, with ability to add CIDR exceptions as needed
* Case-sensitive HTTP1 headers -- although HTTP spec states that
headers are not case-sensitive, in practice many widely
deployed web-servers expect to support case-sensitive headers.
This requires a fork of hyper, which currently has but does
not expose support for case-sensitive headers.
* Assurance that the `host` header appears first in outgoing HTTP requests.
Although HTTP spec does not prescribe an order for headers, in
our experience, many web-servers will fail if the `host` header does
not appear first in request headers. We ensure this by manually
adding the header …

Server: Worker refactor

---

server/svix-server/src/db/mod.rs
server/svix-server/src/lib.rs
server/svix-server/src/main.rs

We were only logging about initialization starting, and never about the success status. This meant that it wasn't very clear for someone reviewing the logs what is going on exactly.
We've cleaned up the logs to be more consistent, and print for both start of an operation and the end (success).
Reason for the change: this just confused a customer (and me!) when we were trying to figure out what's going on. The issue was with the server not connecting to redis, but it wasn't obvious from the logs.

Server: improve startup logs to indicate status

---

server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/tests/e2e_auth.rs

PR #765 added support for attaching feature flags to auth tokens. This added a request body requirement to the dashboard access endpoint which is a backwards-incompatible change for old client libraries. 
Change it back so that a body is optional, keeping backwards compatibility.

Make request body to dashboard-access optional again

---

server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/tests/e2e_auth.rs
server/svix-server/tests/e2e_event_type.rs
server/svix-server/tests/utils/common_calls.rs

2 reasons for this endpoint:
* Better naming than current "dashboard access"
* This one requires a body, even if it's just an empty JSON object with no keys. This way we can add body parameters later without breaking existing clients.
Functionally the same as the existing `/dashboard-access/` endpoint but we require a request body on this endpoint.

Add new endpoint for app portal access

---

server/Dockerfile

Add common root CA certificates to Docker, otherwise TLS connections 
to common destinations are likely to fail.

Server: Add root certificates to Docker image

---

server/svix-server/src/db/models/eventtype.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/tests/e2e_event_type.rs

The previous logic was incorrectly filtering out event types with no feature flag set.
Apply the correct condition to the database query.

Fix event type filtering involving feature flags

---

server/svix-server/src/v1/endpoints/auth.rs

Svix's API uses camel casing across the board; this was missed when implementing this endpoint.
Apply serde `rename_all` attribute.

Change app portal access request body casing to camel case

---

server/svix-server/src/core/otel_spans.rs
server/svix-server/src/core/security.rs

This change simply adds two additional fields, the `org_id` and `app_id` (if any) associated with a request, to the main `tracing` span created in `core::otel_spans` allowing the relevant organization to be recorded in the event of an error.

Add org_id and app_id to main tracing span

---

server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/tests/e2e_attempt.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/e2e_message.rs
server/svix-server/tests/utils/mod.rs

These endpoints can be used to erase the payload of a message, and the response body of attempts. They can be useful in cases where a message was inadvertently sent with sensitive data that it shouldn't have contained, or an endpoint returned a response body with something of the same sort.
Erasing message payloads is technically OK, the worker already handles the case where there's no payload (due to payload expiration) and the response body is not currently used by svix, it is only retained for troubleshooting purposes.

Add endpoints to erase payload and response

---

README.md
server/svix-server/src/core/webhook_http_client.rs

Solves #792 by clarifying the error message surrounding a filtered internal IP address, making it clear that this can be configured. Additionally this changes the  README to include a short paragraph on how to add subnets to the whitelist.

Clarify error message and documentation around filtered IP addresses

---

server/svix-server/src/core/webhook_http_client.rs

Note the explicit use of openssl due to lack of rustls support
for many common ciphers.

Add comment noting use of openssl

---

csharp/Svix/Endpoint.cs
go/endpoint.go
java/lib/src/main/java/com/svix/Endpoint.java
kotlin/lib/src/main/kotlin/Endpoint.kt
python/svix/api.py
ruby/lib/svix/endpoint_api.rb
rust/src/api.rs

It was only implemented in JS and missed for the other libs.
Fixes #764

Add replay method to libraries

---

server/svix-server/src/core/message_app.rs

It's easy to accidentally misuse this field outside of `message_app.rs`. There's a public method that filters out expired keys, we want to prevent accidentally reading from the field directly.
Make the `old_signing_keys` field private.

CreateMessageEndpoint - change old_signing_keys to private

---

server/svix-server/src/v1/endpoints/endpoint/crud.rs

There were a few issues with this error:
1. It was using the wrong field name.
2. The error message itself was confusing.
3. The type names were searilazed in a funny way.
This PR fixes these.

Endpoint CRUD: fix error message and field name.

---

server/svix-server/src/v1/utils/mod.rs
server/svix-server/tests/e2e_attempt.rs

In our API, particularly with paginated endpoints, we often allow `?before=<some time>` or `?after=<some time>` to filter results. Internally, these timestamps are mapped to a Ksuid for the relevant record. This works since our rows are sorted by Ksuid, and Ksuid's have a timestamp component.
This PR fixes a subtle bug with many of our paginated endpoints, where the Ksuid from `?after=` was being generated incorrectly.
For IDs, we use `start_id(<some time>)` and `end_id(<some time>)` to generate a Ksuid with the given timestamp, and the entropy bits set to either all 0s or all 1s, respectively. This way, any ID created at `<some time>` will always come strictly after `start_id(<some time>)`, and reverse for `end_id`. 
However, we were using `end_id(<some_time>)` when querying on …

Fix `?after=<time>` ID Parsing in paginated endpoints

---

server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/headers.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs
server/svix-server/src/v1/endpoints/endpoint/secrets.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils/mod.rs

This has 2 benefits:
1. It is a little safer because tuple params are extracted based simply on position so it's possible to make a mistake simply by putting the types in the wrong order. It still doesn't check that the path placeholders match the extractors at compile-time, though.
2. Aide can match field names to URL placeholder names this way, as a result including the path parameters in the OpenAPI params section.

Change all path extractors to use structs

---

csharp/Svix/Endpoint.cs
go/endpoint.go
go/internal/openapi/api_authentication.go
go/internal/openapi/api_message.go
go/internal/openapi/api_message_attempt.go
go/internal/openapi/model_app_portal_access_in.go
go/webhook.go
java/lib/src/main/java/com/svix/Endpoint.java
javascript/src/index.ts
kotlin/lib/src/main/kotlin/Endpoint.kt
openapi.json
python/svix/api.py
ruby/lib/svix/endpoint_api.rb
rust/src/api.rs

These changes introduce methods for interfacing with the transformations API in the libraries. In the process it updates the `openapi.json` file to the most recent version, meaning some of the unrelated Go generated code is updated by proxy.

Include transformations API in the libs

---

csharp/Svix/Endpoint.cs

Recover [returns](https://api.svix.com/docs#tag/Endpoint/operation/recover_failed_webhooks_api_v1_app__app_id__endpoint__endpoint_id__recover__post) HTTP 202 Accepted, not 204 No Content on success, therefore this condition would never evaluate to true.

Fix incorrect status code comparison for `Recover`

---

rust/src/api.rs

The main `api` package has so far reexported the types used in the functions it wraps, with a few exceptions. This PR moves these types from the private `use` statement to the publicly reexporting one. 
Fixes #805

Publicly reexport types in the `api` pkg in rust

---

server/svix-server/src/core/types/mod.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/tests/e2e_attempt.rs
server/svix-server/tests/utils/common_calls.rs

`/attempt/endpoint` is borked.
When `?channel=` is specified, an improper join happens which causes the Endpoint to fail with a 500 error.
Also, the actual query on a specific channel just straight up doesn't work. `channel ?? ?` is neither the proper operation, nor is `?` even used for params in postgres. You need a `$N`.
Fix the damn queries! And update the tests so we catch this in the future.

Fix `/attempt/endpoint`'s broken `?channel=` query

---

csharp/Svix/Endpoint.cs
go/endpoint.go
java/lib/src/main/java/com/svix/Endpoint.java
javascript/src/index.ts
kotlin/lib/src/main/kotlin/Endpoint.kt
python/svix/api.py
ruby/lib/svix/endpoint_api.rb

They were incorrectly named `replay` instead of `replay-missing` (and the various capitalization variants) in all but Rust.

Fix naming of replay-missing methods in libraries

---

rust/src/api.rs

Like what's fixed in #806, sometimes types are accidentally not publicly reexported in the `api` package. This changes the import/reexport statement to a glob so generated models are automatically reexported.

Glob-reexport all generated models in Rust

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/tests/e2e_attempt.rs

This fixes how `?event_types` query parameters are parsed in `*/attempt/endpoint/*`, in addition to some adjacent refactors.
`axum::Query` doesn't support URL query array parameter parsing very well. For example,
- `?a=1&a=2` gets rejected
- `?a[]=1&a[]=2` also gets rejected
- `?a[0]=1&a[1]=2` _also_ gets rejected
This is largely because `serde::urlencoded` doesn't support any of these formats. See https://github.com/nox/serde_urlencoded/issues/75
There is `serde_qs`, which supports the last two. But not the first format. See https://github.com/samscott89/serde_qs/issues/16
Unfortunately, we _need_ to support the first format because that is what our internal API has supported up to today.
However, our OSS has been inconsistent. Specifically with `?event_types`.
Most endpoints that took …

Fix event_type array query parsing

---

server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/endpoint/secrets.rs
server/svix-server/tests/e2e_operational_webhooks.rs

As per title, rotating the secrets of an endpoint is an update to the endpoint, therefore it should fire the corresponding operational webhook.

Fire operational webhook on endpoint secret rotation

---

server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/tests/e2e_endpoint.rs

With this change `Endpoint` also returns a `prev_iterator` in its list response, and accepts such an iterator.

Implement bidirectional pagination for endpoints

---

server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/tests/e2e_endpoint.rs

The overall pagination is still done first-to-last, but within a page results are listed last-to-first.
Builds on top of #812

Query parameter to list endpoints newest-to-oldest

---

server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/headers.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs
server/svix-server/src/v1/endpoints/endpoint/secrets.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils/mod.rs

This change just copy-pastes the description from the existing spec, except for fixing obvious mistakes (e.g. get_endpoint says "gets an application" in the current spec)

Add operation descriptions to generated OpenAPI

---

server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/tests/e2e_endpoint.rs

After the last change, a "previous" iterator for descending sorting was not handled correctly. This fixes that.

Handle previous iterator on descending ordering

---

javascript/src/index.ts

At the moment it assumes that the date is round to the nearest
second. This fix changes that.

JS: fix sign function to support non-round dates.

---

server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/utils/common_calls.rs

This is to make it consistent with the hosted version of Svix.

Change default iteration of endpoints to descend

---

server/svix-server/src/v1/utils/mod.rs
server/svix-server/tests/utils/common_calls.rs

While working on some new endpoints, I was surprised/annoyed that I needed to implement `Clone` for the various structs used in the axum handler.
Turns out, we don't need it at all. So I'm removing the unnecessary trait bound. We can probably remove `#[derive(Clone)]` from a bunch of structs in our `v1` folder, but that's for another day.
Remove the unnecessary trait bound.

Remove unnecessary Clone trait bounds

---

csharp/Svix/Endpoint.cs
csharp/Svix/EventType.cs
csharp/Svix/Models/ListOptions.cs
go/endpoint.go
java/lib/src/main/java/com/svix/Endpoint.java
java/lib/src/main/java/com/svix/EndpointListOptions.java
java/lib/src/main/java/com/svix/EventType.java
javascript/src/index.ts
kotlin/lib/src/main/kotlin/Endpoint.kt
kotlin/lib/src/main/kotlin/EndpointListOptions.kt
kotlin/lib/src/main/kotlin/EventType.kt
python/svix/api.py
rust/src/api.rs

These were missed when the OpenAPI spec was updated, so fixing that here.

Add new event type and endpoint params to libs

---

server/svix-server/src/error.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/event_type.rs

These changes alter the `Traceable` implementation for `DbErr` to only return `Error::database`s instead of having logic which implicitly converts these errors to `HttpError`s depending on the error type.
Instead the relevant conversion is performed explicitly via the new utility function `http_error_on_conflict`. Note that 404 responses did not need to be explicitly checked as every instance where a 404 should be returned has logic that handles `None`  responses.

Alter DbErr Traceable impl to make conversions explicit

---

server/svix-server/src/db/models/application.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/tests/e2e_application.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/e2e_event_type.rs
server/svix-server/tests/utils/common_calls.rs

It also extends the `common_test_list` function to test for reverse ordering, where supported.

Add support for ordering and prev_iter in app list

---

server/svix-server/src/core/types/mod.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/tests/utils/common_calls.rs

Two noteworthy changes:
* Introduce a new `IdIterator` trait to represent all identifier-like things we use for iteration in the API. These are generally the `BaseId` types but there are some exceptions, like `EventTypeName` in this change's case.
* Move `From<String>` impl from the `create_id_type` macro to the `string_wrapper_impl` macro since all string wrappers will want this, and it's needed for `EventTypeName` to function as a `ReversibleIterator`.

Add prev_iter support for event type list

---

.github/workflows/csharp-lint.yml
.github/workflows/java-lint.yml
.github/workflows/javascript-lint.yml
.github/workflows/kotlin-lint.yml
.github/workflows/other-lint.yml
.github/workflows/python-lint.yml
.github/workflows/ruby-lint.yml
.github/workflows/rust-lint.yml

Changing OpenAPI means the generated parts of the codebase may change. We need to run linting in this case to ensure the libraries are still valid after a change.

Run library linting on OpenAPI change

---

.github/workflows/go-lint.yml

In #842 I missed adding openapi as a lint trigger to the go workflow. This remedies that.

Add missing OpenAPI-lint-trigger to go

---

ruby/lib/svix.rb

This was missed when app portal access was added.
Fixes #838

Require (reexport) app portal models in ruby

---

server/svix-server/src/v1/endpoints/application.rs

Followup to #835 which adds a missing explicit conversion from conflict `DbErr`s during message creation.

Return CONFLICT on UID constraint breached on app creation

---

server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/event_type.rs

Followup to #846 which identifies and fixes the same problem in other parts of the code. In brief, with unluckily timed concurrent PUT/PATCH requests to the same object, the checks for UID conflicts done during the start of the request would become stale as one request processed. This leads to a specific `DbErr` which the changes now manually map to a HTTP CONFLICT response.

Fix 5xx responses during concurrent UID updates

---

ChangeLog.md
csharp/Svix/Models/SvixOptions.cs

Today, the default behavior for the C# client is to swallow exceptions and return a `null` in the event of a failed HTTP request.
In addition to being surprising, this hides the HTTP status code for the response since this is exposed via the exception being swallowed.
Refs: <https://github.com/svix/svix-webhooks/issues/823>
This diff changes the default for `Throw` from `false` to `true` so that callers need to opt-in to the swallowing behavior rather than opt-out.

[CSharp] change `SvixOptions.Throw` default to `true`

---

server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/headers.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs
server/svix-server/src/v1/endpoints/endpoint/secrets.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server_derive/src/lib.rs

This macro can be used to annotate axum handler functions to automatically generate an operation transformation that adds an operation ID, summary, and description.
Here's how to use it:
```rust
/// Doc comment
#[aide_annotate]
async fn some_handler(/* some params */) -> impl IntoResponse {
}
```
This generates a new function `some_handler_operation` which has the signature `fn(TransformOperation) -> TransformOperation`, i.e. what's needed for aide. This function sets the following in OpenAPI:
1. Operation ID becomes the name of the function, or can be optionally overridden with an `#[aide_annotate(op_id = "foobar")]`.
2. Operation summary becomes the title cased name of the function, e.g. `create_message` becomes `Create Message`. This can also be overridden, with `op_summary = "summary …

Add attr macro to generate operation transform

---

server/svix-server/src/core/message_app.rs
server/svix-server/tests/message_app.rs

It was discovered that deleted applications could still be improperly handled if a `CreateMessageApp` 's deleted fields (either on the `struct`  itself or via the `endpoints` field which each could be deleted) was not respected. These changes ensure that deleted application models return `Ok(None)` instead of `Some` `CreateMessageApp`, centralizing the logic to the only constructor of the `struct`. 
Additionally, to prevent such issues from ever occurring the `CreateMessageApp` has been changed slightly such that the `endpoints` and `deleted` fields are private. This means that the struct must be always be constructed via the `layered_fetch` which now filters for deleted applications. And it  means that endpoints must be fetched through the `filtered_endpoints` method, which filters …

Centralize the handling of deleted flags in CreateMessageApp

---

go.mod

We are quite a few # of Go versions behind. Also, this should fix
* https://github.com/svix/svix-webhooks/security/dependabot/35
* https://github.com/svix/svix-webhooks/security/dependabot/32
* https://github.com/svix/svix-webhooks/security/dependabot/34
Bump to latest go version, and ran `go mod tidy`

Bump Go version

---

server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/headers.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs
server/svix-server/src/v1/endpoints/endpoint/secrets.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils/mod.rs

This way the response code can be correctly inferred by aide for endpoints where we were previously returning `(StatusCode, Json<T>)` style responses. With the tuple style aide had no way of knowing what was the response like that's being returned. This way the response code is known statically at compile time which we can use to inform aide.
There are two structs, `JsonStatus`, for endpoints that always return the same status code on success, and `JsonStatusUpsert`, which is appropriate for endpoints that do upsert-style operations, e.g. where you have two status codes to distinguish between what happened internally, e.g. create versus update, but the output is the same. There's a fair number of endpoints that follow this pattern so it seemed worthwhile to add this.
Unfortunately custom …

Add JSON response type wrapper with response code

---

server/svix-server/src/expired_message_cleaner.rs
server/svix-server/tests/e2e_message.rs

In cases where a large number of messages expire within a short period, and multiple instances of svix-server are running in concert, it's possible to see postgres deadlocks.
This diff adjusts the cleaner to make it more cooperative by using row-locks to incrementally remove the payloads a batch at a time.
The polling schedule has been updated as well. When the backlog of expired messages is small or zero, we poll every 3 or 10 seconds respectively. In other cases (where there are many rows processed) there will be no sleep at all; the loop will "go hot" as it works through the backlog.
With this, we should no longer see deadlocks related to the cleaner but at the cost of (possibly) a delay in payload expiry.

refactor expired message cleaner to be incremental to avoid db deadlocks

---

ChangeLog.md

Neglected to update the changelog with the initial work on #869. This diff adds the missing entry.

add changelog entry for expired message cleaner refactor

---

go/messageattempt.go

When these ListResponse* types are aliased in the svix package, the struct type they're returning in the Data array should also be aliased.
If the user would like to, say, make a helper function that cycles through all the iterators for this, and returns the structs on a channel, they cannot do that without the types being available (or defining their own struct types that mimic the openapi ones).
Simply alias the struct types that are used in each of these ListReponse* type's Data array field.

Alias types from internal dir / openapi package

---

server/Cargo.lock
server/svix-server/Cargo.toml

This just bumps `tower-http` to the latest version. We use some of the crate's services for limiting request bodies.
This isn't motivated by anything specific, I just saw we were behind versions when looking at adjacent code.
Bumping the version. That's it.

Bump tower-http version

---

server/svix-server/Cargo.toml
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/e2e_message.rs
server/svix-server/tests/utils/common_calls.rs

We were using the `serde_json::Value` for the message payload which resulted in a lot of allocations when the payload was complex, and was causing high memory usage and fragmentation. With this, we don't actually parse this part of the json, but rather just treat it as a string (serde verifies it's valid json though). We unfortunately turn it into a `Value` when persisting to PG, we should fix this extra thing that diminishes the point of this change a bit.
Includes a hack to workaround the serde_json flatten issue with RawValue: https://github.com/serde-rs/json/issues/599

Create message: change to RawValue instead of Value

---

server/Cargo.lock

The current version is yanked.

Bump version of crossbeam-channels

---

rust/Cargo.toml
rust/README.md

// only the default-tls
cargo tree
// both since features are additive
cargo tree --features rustls-tls
// only rustls-tls
cargo tree --features rustls-tls --no-default-features
closes #889
Bellow is verbatim copy from issue #889 created by @msdinit
We are building our application against musl, cross-compiling it from regular libc Ubuntu. However, we are having issues with svix client, because it depends on system OpenSSL, which in our case would be linked against libc. There https://github.com/sfackler/rust-openssl/issues/603, but they are a bit involved.
Added cargo features allowing users to choose which ssl version to use for svix reqwest http client, keeping backwards compatibility.

[rust]: allow specifying TLS flavour to use

---

server/svix-server/src/core/types/mod.rs
server/svix-server/src/v1/endpoints/event_type.rs

It was discovered that some fields in various `ModelIn` implementors were not validated correctly. 
These changes ensure that 
- The `#[validate]` macro is no longer missing for the `EventTypeName` in `EventTypeIn` instances
- `EventTypeName`s are validated to have a length greater than one
- That the `BaseUid` default validation implementation also checks for a length greater than one
Additionally fixes a typo in the `test_id_validation` test which caused one case to be skipped.

Add additional validation to some inputs

---

server/svix-server/config.default.toml

The redis DSN is not required, given that redis
is not required for either queuing or caching. Nonetheless 
our config defaults were always adding it, causing it to waited on, 
and causing the application to panic.
Fixes #870.

Make redis-dsn optional

---

ruby/lib/svix.rb
ruby/lib/svix/internal.rb

Current library version fails to load due to a missing dependency. 
This dependency is not really part of the public API, though, so removing.
Fixes #908

Ruby: Fix missing dependency

---

rust/src/error.rs

It was printing the typoed string.

Lib/Rust: fix typo Varidation -> Validation in error handling.

---

webhook-bridge/Cargo.lock
webhook-bridge/Cargo.toml
webhook-bridge/README.md
webhook-bridge/generic-queue/Cargo.toml
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/src/config.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/src/error.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/src/gcp_pubsub/mod.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/src/lib.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/tests/gcp_pubsub_consumer.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/tests/rabbitmq_consumer.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/tests/redis_stream_consumer.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/tests/sqs_consumer.rs
webhook-bridge/svix-webhook-bridge-types/Cargo.toml
webhook-bridge/svix-webhook-bridge-types/src/lib.rs
webhook-bridge/svix-webhook-bridge.example.yaml
webhook-bridge/svix-webhook-bridge/Cargo.toml
webhook-bridge/svix-webhook-bridge/src/main.rs
webhook-bridge/svix-webhook-bridge/src/runtime/mod.rs
webhook-bridge/svix-webhook-bridge/src/runtime/tests.rs

Embeds a deno runtime in the bridge binary to allow ad hoc reshaping of messages read from queues before they are sent to Svix.
When consuming JSON from messaging systems to generate new webhooks, it's common to need to transform the payload before making the Create Message request to Svix.
Embedding a JS runtime into the bridge process allows us to run user-defined functions on the payloads as they move from input to output.
With this diff, plugin instances provided by `svix-webhook-bridge-plugin-queue-consumer` can now evaluate js included in the plugin config:
```yaml
plugins:
- type: "rabbitmqconsumer"
input:
uri: "amqp://guest:guest@localhost:5672/%2f"
queue_name: "local"
requeue_on_nack: false
transformation: | 
function handler(input) {
return { 
app_id: input.key, 
message: { …
```

add js transforms to bridge

---

server/svix-server/src/v1/utils/mod.rs
server/svix-server/tests/e2e_attempt.rs

Our Rust lib generates query params in comma-separated syntax.
This is technically not what our API expects, but frankly it's easy to
support it and seems reasonable to do so. Added and updated tests
accordingly.
Fixes #921

Server: Support comma-separated array query params

---

webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/src/gcp_pubsub/mod.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/src/lib.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/src/rabbitmq/mod.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/src/redis/mod.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/src/sqs/mod.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/tests/gcp_pubsub_consumer.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/tests/rabbitmq_consumer.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/tests/redis_stream_consumer.rs
webhook-bridge/svix-webhook-bridge-plugin-queue-consumer/tests/sqs_consumer.rs
webhook-bridge/svix-webhook-bridge/src/config/mod.rs

Adds wrapper types around the backend-specific types we get from generic-queue.
Adding new backends to the consumer bridge plugin today is a bit of a chore, encouraging parts of the ack/nack and consumer loop flow to be duplicated. The generics exposed in the signatures of items from `generic-queue` tend to make code reuse tricky.
This is mostly focused on moving the decision-making bits of the flow up to the trait's default implementation for methods like `receive` and `process` since these were essentially duplicate from backend to backend.
New wrapper types are used to hide/erase the distinct backend typing from the consumer flow.
Additionally, the code related to each backend has been relegated to a dedicated module (which should help when adding new backends since you can copy the …

bridge: reduce duplicate consumer code as much as possible

---

.github/workflows/webhook-bridge-ci.yml

Largely copypasta'd from the equivalent `server` workflow.
Runs a build, clippy, checks the formatting, runs the testing docker compose stack and finally runs the `run-tests.sh` script.

add CI for webhook-bridge

---

webhook-bridge/Dockerfile

Looks like `deno_core` depends on `rusty_v8` which will try to download prebuilt a binary v8 archive via some python script, and when that fails it'll try again with `curl`.
The Python download was failing. Why? No idea. The curl fallback also failed because curl was not installed.
This diff adds `curl` to the list of installed packages for the builder stage of the `Dockerfile` which allows the `cargo build` layer to complete successfully.

fix deno failure in bridge docker build

---

webhook-bridge/Cargo.lock

Cleans up the lockfile now that the dust is settling on the initial push for release.
Some items in the lockfile are no longer needed, and also some patch-level updates are probably available with the dependency graph as is written today.
Run `cargo update` and update the lockfile.

run `cargo update` for bridge

---

csharp/Svix/Endpoint.cs
csharp/Svix/Models/EndpointStatsOptions.cs
go/endpoint.go
go/internal/openapi/api_endpoint.go
java/lib/src/main/java/com/svix/Endpoint.java
java/lib/src/main/java/com/svix/EndpointStatsOptions.java
javascript/src/index.ts
kotlin/lib/src/main/kotlin/Endpoint.kt
kotlin/lib/src/main/kotlin/EndpointStatsOptions.kt
python/svix/api.py
ruby/lib/svix/endpoint_api.rb
rust/src/api.rs

We added this feature to our API a while ago (see [here](https://api.svix.com/docs#tag/Endpoint/operation/v1.endpoint.get-stats)), but never updated the libs.
This PR corrects that.
Update the libs.

Add Since/Until for endpoint stats to libs

---

webhook-bridge/svix-webhook-bridge-plugin-webhook-receiver/src/config.rs
webhook-bridge/svix-webhook-bridge-plugin-webhook-receiver/src/forwarding.rs
webhook-bridge/svix-webhook-bridge-plugin-webhook-receiver/src/lib.rs
webhook-bridge/svix-webhook-bridge-plugin-webhook-receiver/src/types.rs

Updates the webhook-receiver plugin to accept a `TransformerTx` so it can leverage the JS Runtime managed by bridge.
This is not the best diff, sadly.
The original webhook-ingester made some design decisions that made this a little awkward. Specifically, the request would accept a forwarder on its `forward` method which took responsibility for payload handling.
When transformations are optionally happening, the payload either needs to transform as a part of the `forward` method, or (my preference) the payload handling needs to be moved up to the handler level.
I went for the latter - The "forward" method now hangs off the forwarder and receives a payload. This means the handler can attempt the transformation before forwarding, which keeps the go/no-go logic all within the handler body. It …

integrate bridge js transformations with webhook-receiver plugin

---

package.json
yarn.lock

Helps with a dependbot advisory for a transient dep on `@nestjs/core`. <https://github.com/advisories/GHSA-4jpv-8r57-pv7j>
To verify this upgrade, I reran `regen_openapi.sh` and it exited `0`, making it through the whole run.

bump openapi-generator-cli to 2.6

---

ChangeLog.md
go/messageattempt.go

Looks like this option was omitted from the public API accidentally.
Fixes #928

[Go] add `endpoint_id` option to List Attempts By Msg

---

ChangeLog.md
javascript/src/index.ts

Helps with #942 but to fix we need to update the spec and regenerate the openapi client code.

[JavaScript] add missing `withContent` field to `MessageListOptions`

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/redis/mod.rs

Update redis connection pooling to use use bb8-redis's `RedisMultiplexedConnectionManager` for non-clustered connections. This uses redis-rs's multiplexed connection type under the hood, which is more secure and more performant than the non-multiplexed connection type used by `RedisConnectionManager`.

Server: Update Redis Connection Pooling

---

.github/workflows/bridge-ci.yml
bridge/svix-bridge.example.receivers.yaml
bridge/svix-bridge.example.senders.yaml
bridge/svix-bridge/src/config/tests.rs

At one point bridge was being called "webhook bridge" and during the renaming some references to the old name were missed.
Most of these omissions are harmless but in the case of the CI workflow name, it mismatched with the updated name used in the badge on the readme.
This should fix the broken link for the badge.
Superseeds #948

rename bridge ci

---

go/messageattempt.go

The motivation behind this Pull Request is to enhance the Svix Go SDK by expanding the functionality of the List Attempted Messages endpoint. Currently, the SDK lacks the capability to return messages with payload. This limitation poses a challenge for developers who require access to the payload data when retrieving attempted messages. Therefore, this PR aims to introduce an option within the SDK that enables the retrieval of messages along with their payloads. By addressing this limitation, developers will have a more comprehensive and convenient way to access the desired message data.
`WithContent` field of type `*bool` has been added to the `MessageAttemptListOptions` type. That value is then passed as query parameter in the request to the List Attempted Messages endpoint.

Pass `WithContent` option as query parameter to `List Attempted Messages` EP

---

server/svix-server/src/core/webhook_http_client.rs
server/svix-server/src/worker.rs

Workers that run for a long time uninterrupted can leak memory _very slowly_.
Running svix-server through [bytehound](https://github.com/koute/bytehound), grouping allocations by the "largest leak by backtrace" gives us:
```
#00 [svix-server] _start
#01 [libc.so.6] __libc_start_main
#02 [libc.so.6] 7f15c8e4dd8f
#03 [svix-server] main
#15 [svix-server] svix_server::main
#16 [svix-server] tokio::runtime::scheduler::multi_thread::MultiThread::block_on
#17 [svix-server] tokio::runtime::context::BlockingRegionGuard::block_on
#18 [svix-server] svix_server::main::{{closure}}
#19 [svix-server] <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
#20 [svix-server] svix_server::run_with_prefix::{{closure}}
#21 [svix-server] <tokio::future::poll_fn::PollFn<F> as …
```

curb incredibly slow leak in openssl connector

---

server/svix-server/src/core/message_app.rs
server/svix-server/src/core/types/mod.rs
server/svix-server/src/db/models/endpoint.rs
server/svix-server/src/v1/endpoints/endpoint/headers.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs

We will need to reuse the current header sanitizing logic in a future PR, so 
introduce `SanitizedHeaders` as a type, use it where appropriate, and 
rename the non-sanitized field to indicate clearly that it could contain 
sensitive information.

Server: Centralize header sanitize logic

---

server/testing-docker-compose.yml

CI is failing for rediscluster configurations as of the 7.0.11 release that just came out.
Pin the redis containers we use in CI to 7.0.10 instead so the tests can actually run cleanly.

pin redis images to 7.0.10

---

server/Cargo.lock
server/openapi.json
server/svix-server/Cargo.toml
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/mod.rs
server/svix-server/tests/e2e_auth.rs

Support for one time tokens depends on cache.
A JWT and one-time token are generated in `app_portal_access`, and the
one-time token is used as a part of the cache key where the value is the
JWT itself.
The cache entry has a 7 day TTL.

Server: add  support for one time token auth

---

server/openapi.json
server/svix-server/src/db/models/eventtype.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/worker.rs

Support sending example events to given endpoints.
This works out-of-the-box for `svix.ping` events and 
for user-defined events with an example defined.
This also makes slight modification to `MessageTaskBatch`
to support optional endpoint overrides.

Server: Support sending example event

---

server/openapi.json
server/svix-server/src/v1/endpoints/endpoint/mod.rs

- Change permission in /send_example endpoint from `OrganizationWithApplication` to `Application`, so it's accessible with an App Portal one time token.
- Use camelCase in EventTypeIn for /send-example

Server: fix permissions and payload format in send_example endpoint

---

server/svix-server/src/redis/cluster.rs

Because we already have our own generic retry implementation that we use for queuing and caching, we should disable the clustered redis client's own default retry mechanism, which defaults to 16(!) retries if none are specified. For certain classes of errors, this limit includes exponental backoffs, so if we add our own layer of retries on top of this, we could potentially spend minutes in an endless retry loop. Let's ensure that doesn't happen!

Server: Disable clustered-redis lib retries

---

server/openapi.json
server/svix-server/src/v1/endpoints/mod.rs
server/svix-server/src/v1/endpoints/stats.rs
server/svix-server/src/v1/mod.rs
server/svix-server/tests/e2e_endp_stats.rs

Implements the "endpoint stats by app" endpoint, porting over the
original tests along with it.
Spot-checked the output with curl as well.
```
$ curl "http://localhost:8071/api/v1/stats/app/app_2RFwwVIcJtUu5ncRmIkD7RPUtjP/attempt/?startDate=2023-06-15T19:45:00.000Z&endDate=2023-06-15T20:15:00.000Z" -sS | jq
{
"startDate": "2023-06-15T19:45:00Z",
"endDate": "2023-06-15T20:15:00Z",
"period": "FiveMinutes",
"data": {
"successCount": [
0,
0,
0,
5,
0,
0
],
"failureCount": [
0,
0,
0,
1,
0,
0
]
}
}
```

Server: add app attempt stats

---

.github/workflows/server-ci.yml
server/svix-server/src/worker.rs
server/svix-server/tests/e2e_application.rs
server/svix-server/tests/e2e_attempt.rs
server/svix-server/tests/e2e_endpoint.rs
server/svix-server/tests/worker.rs

Many of the flakes we see are timing-related. The more straightforward
kludges I've used here are just adding small sleeps between things so
they are more clearly separated in time.
---
`test_endpoint_disable_on_repeated_failure` is a special case.
The test requires that 2 requests fire but not too soon but also not too
far apart.
In practice when this test fails, it's because the 2nd request fires too
late, after the "forgiveness" rule kicks in (if an endpoint fails and we
don't see it _fail again_ within 2x the `disabled_in` duration, then we don't
disable it).
The reason for the poor timing could be contention on the db/queue from
or just due to the CPU being too busy. I tweaked the timing a little to
try and smooth it over, but setting `RUST_TEST_THREADS=1` seemed to help
the most. …

Server: fixup some flaky tests

---

server/openapi.json
server/svix-server/src/db/models/eventtype.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/worker.rs
server/svix-server/tests/e2e_endpoint.rs

This change implements the `send-example` route which allows dispatching example events to a given endpoint.

Implement send-example route

---

javascript/src/index.ts

We had a check in typescript, but this obviously doesn't matter in JavaScript environments. Passing an object instead of a payload is an extremely common error case, so it's better to be explicit about it rather than implicit (just failing verification).
Fixes #977

JavaScript: Add an explicit check that payload is a string

---

bridge/README.md
bridge/generic-queue/src/gcp_pubsub.rs
bridge/generic-queue/src/lib.rs
bridge/generic-queue/src/memory_queue.rs
bridge/generic-queue/src/rabbitmq.rs
bridge/generic-queue/src/redis.rs
bridge/generic-queue/src/sqs.rs
bridge/svix-bridge-plugin-queue/src/config.rs
bridge/svix-bridge-plugin-queue/src/gcp_pubsub/mod.rs
bridge/svix-bridge-plugin-queue/src/lib.rs
bridge/svix-bridge-plugin-queue/src/rabbitmq/mod.rs
bridge/svix-bridge-plugin-queue/src/receiver_output/mod.rs
bridge/svix-bridge-plugin-queue/src/redis/mod.rs
bridge/svix-bridge-plugin-queue/src/sqs/mod.rs
bridge/svix-bridge-plugin-queue/tests/gcp_pubsub_consumer.rs
bridge/svix-bridge-plugin-queue/tests/rabbitmq_consumer.rs
bridge/svix-bridge-plugin-queue/tests/redis_stream_consumer.rs
bridge/svix-bridge-plugin-queue/tests/sqs_consumer.rs
bridge/svix-bridge-types/src/lib.rs
bridge/svix-bridge.example.receivers.yaml
bridge/svix-bridge.example.senders.yaml
bridge/svix-bridge/src/config/mod.rs
bridge/svix-bridge/src/config/tests.rs
bridge/svix-bridge/src/main.rs
bridge/svix-bridge/src/runtime/mod.rs
bridge/svix-bridge/src/runtime/tests.rs
bridge/svix-bridge/src/webhook_receiver/config.rs
bridge/svix-bridge/src/webhook_receiver/mod.rs
bridge/svix-bridge/src/webhook_receiver/tests.rs
bridge/svix-bridge/src/webhook_receiver/types.rs

Adds a bunch of plumbing to allow the message payloads from consumers to
be passed to transformations as strings rather than pre-parsing as JSON
in rust.
One concrete use case for this is if the system publishing those
messages to the queue is sending XML or perhaps base64 encoded data.
When configured to specify the `format` of a transformation, you can set
it to `string` rather than the default `json`. Then, when the
transformation receives that string as an argument, it can do whatever
parsing is required in order to return a valid `Object`.
Tests have been added up and down the stack to show that strings are
handled correctly, and that the new config data is propagated.
Notable omissions:
- redis relies on JSON values internally and can't easily support "raw"
inputs. We can revisit …

Bridge: support raw inputs for transformations

---

bridge/README.md
bridge/svix-bridge-plugin-queue/src/lib.rs
bridge/svix-bridge-plugin-queue/src/receiver_output/mod.rs
bridge/svix-bridge-plugin-queue/tests/gcp_pubsub_consumer.rs
bridge/svix-bridge-plugin-queue/tests/rabbitmq_consumer.rs
bridge/svix-bridge-plugin-queue/tests/redis_stream_consumer.rs
bridge/svix-bridge-plugin-queue/tests/sqs_consumer.rs
bridge/svix-bridge-types/src/lib.rs
bridge/svix-bridge.example.receivers.yaml
bridge/svix-bridge.example.senders.yaml
bridge/svix-bridge/src/config/tests.rs
bridge/svix-bridge/src/webhook_receiver/mod.rs
bridge/svix-bridge/src/webhook_receiver/tests.rs

This diff is a little more broad than just "put the payload in a field."
It also tries to formalize the requirements of each output case, both
Senders and Receivers.
For Senders, we need a certain shape useful for building a call to
Create Message.
For Receivers, outputs expect to get a JSON object with a `payload`
field on it, representing the data to publish to the queue or what have
you.
These boundary types are now both in the `-types` crate, and used to
ensure both as-is and transformed data conforms where needed.
Existing tests caught the changes on the receiver side (which is
the main thing for this diff).
Additionally, for Senders, I camelCased the `appId` field to make the
create message JSON cased more consistently. This was a remark that came
up during review of an up-coming …

Bridge: receivers now publish to queues with `payload` field

---

bridge/README.md
bridge/svix-bridge/src/webhook_receiver/mod.rs
bridge/svix-bridge/src/webhook_receiver/tests.rs

Follow-on from #982.
For cases where the webhook receiver has not transformation set, we assume the body is JSON. Formerly, that JSON body would fail to validate if it didn't happen to have a root key named "payload" to align with our expectations. This is a bad default.
Instead, we take the body, parse it as JSON, then shove it in the payload field.

Bridge: receivers with no transformation set body as payload field

---

bridge/Cargo.lock
bridge/README.md
bridge/svix-bridge/Cargo.toml
bridge/svix-bridge/src/config/mod.rs
bridge/svix-bridge/src/config/tests.rs
bridge/svix-bridge/src/main.rs

Config files can now use "dollar brace" notation to do variable
substitutions. See the readme for an example.
~~Since variable expansion might not be assumed, this behavior is gated by
a CLI flag/env var and is **off by default**.~~
Furthermore, the variables available for substitution are exposed via a
simple HashMap meaning we can filter the vars exposed in the future, if
requested. This also has the benefit of being nicer for testing ;)
Tests are added to capture the initial behavior of the new dep, but also
to lock in the contract if we decided to "roll our own" in the future.
---
Open source review required.
Adds a dependency on [envsubst-rs](https://github.com/coreos/envsubst-rs)
to provide the base substitution capability.
This was selected based on the following criteria:
- …

Bridge: variable expansion for config files

---

server/run-tests.sh
server/testing-docker-compose.yml

It's not uncommon for tests to fail due to a pool timeout.
Raise the connection limits to help avoid this.

CI: raise max connections, pool size for redis/pg in server tests

---

server/openapi.json
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/tests/e2e_attempt.rs

The 'v1.message-attempt.list-by-endpoint' API takes in a 'event_types' parameter that filters the returned 'MessageAttemptOut's by event type. The similar  'v1.message-attempt.list-by-endpoint' API should have an equivalent parameter.
Add `EventTypesQueryParams` to the `'v1.message-attempt.list-by-endpoint' API

Server: add 'event_types' query param to 'list-attempted-messages'

---

server/svix-server/src/core/cache/mod.rs
server/svix-server/src/core/idempotency.rs
server/svix-server/src/core/message_app.rs
server/svix-server/src/worker.rs

Removes the associated const `PREFIX_CACHE` from the `CacheKey` trait, and supporting macro APIs.
This diff should be non-breaking in that the key strings should be the same as before, just without the API confusion.
Formerly it was possible to specify an override for the prefix of cache keys via an optional 3rd arg to `kv_def!`, and `string_kv_def!`.
The issue is, the override (or the default when omitted) are not included in the actual string form of the key unless you explicitly `format!()` it in there.
This is to say, the following are equivalent:
```rust
// specify the override, then manually format it in.
kv_def!(KeyA, ValA, "MY_PREFIX")
impl KeyA {
pub fn new(x: &str) -> Self {
Self(format!("{Self::PREFIX_CACHE}_{x}"))
}
}
// no override, so `Self::PREFIX_CACHE` is whatever the …
```

Server: remove `CacheKey::PREFIX_CACHE`, `kv_def!`, `string_kv_def!`

---

bridge/Dockerfile
server/Dockerfile

This updates Rust to the latest stable version for both server and bridge.
That's it.
Folks are recommended to update Rust locally as well.
```
rustup update
```

Update Rust to latest stable version

---

bridge/README.md
bridge/svix-bridge/src/main.rs

Writing out config data to disk can sometimes be awkward. Users of the Bridge docker image would either need to customize, using the bridge image as a base then add their config file to the fs, or otherwise use a volume mount (or similar).
k8s users have the benefit of config maps, which can be represented as files on disk, but this is not always a good option.
Allows Bridge to load its config data from a string, which can be supplied as an env var or directly on the cli with `--cfg`.
The original flag for specifying an alternative file path to read config data from (formerly `--cfg` or `-c`) has been renamed to `--cfg-file`.
Sorry that's so confusing!
- Use `--cfg` to pass config as string
- Use `--cfg-file` to read from file, non-default loction
Additionally, a naive "search path" has …

Bridge: load config from string (env var or cli flag)

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/core/types/mod.rs
server/svix-server/src/db/models/application.rs
server/svix-server/src/db/models/applicationmetadata.rs
server/svix-server/src/db/models/endpoint.rs
server/svix-server/src/db/models/endpointmetadata.rs
server/svix-server/src/db/models/eventtype.rs
server/svix-server/src/db/models/messagedestination.rs

This updates sea_orm to the latest stable version
The newest version of sea_orm isn't _that_ different from what we're currently running, but it does have more features that can be useful.
- Updates the dependency
- Fixes compile time errors, of which there were two
- 1. The `trait TryGetable:` has a new required method that needs implementing. Doing this was pretty straightforward, as everything that implements `TryGetable` is just a wrapper type
- 2. `ActiveModelBehavior::before_save` is now an async_trait that accepts that DatabaseConnection as a parameter. The code change here isn't really meaningfully different from what we had before.

Update sea_orm to latest stable version

---

rust/Cargo.toml
rust/src/lib.rs
rust/templates/model.mustache

We have a couple of integer-based enums in our API responses. The existing template for enum generation in the Rust client library only supports string-based enums.
Fixes #1009 
We can switch on the type of enum as defined in the OpenAPI specification. Then it's just a matter of pulling in serde_repr to do the heavy lifting.

Extend Rust enum generation template to handle integer-based enums

---

bridge/Cargo.lock
bridge/svix-bridge-types/src/lib.rs
bridge/svix-bridge/Cargo.toml
bridge/svix-bridge/src/config/mod.rs
bridge/svix-bridge/src/config/tests.rs
bridge/svix-bridge/src/main.rs
bridge/svix-bridge/src/runtime/mod.rs
bridge/svix-bridge/src/runtime/tests.rs
deny.toml

This PR serves a few aims:
1. improve diagnostics around configuring transformations.
2. improve overall performance of transformations.
3. upgrade deno
3a. without the penalty of leaking memory.
3b. open the door to using async/await and JS module code (needed for
the "poller input" prototyped during our recent hack week.
3c. avoid that CVE we saw for all but recent deno versions.
This diff upgrades us from a very old `deno_core` to the current release
`0.195.0` via the latest `deno_runtime`. The latter is what provides
expanded JS features such as async/await and typical DOM APIs you might
expect to have, such as `fetch`.
In `deno_core` versions beyond `0.142.0`, we see memory leaked each time
we initialized a `JsRuntime` and drop it.
This was the old method for executing JS code in …

Bridge: better js transformations

---

go/svix.go

what:
- add a simple constructor for NullableInt32 type
why:
- Having this constructor will allow setting `RateLimit` value in `svix.Endpoint...` and `svix.Application...` types.
solves #1017

Add constructor for `openapi.NullableInt32`

---

python/requirements.in/development.txt

I'm not entirely sure, but it looks like we can't upgrade to 0.15.0?

Python: add a comment about potentially dangerous update.

---

yarn.lock

Originally to try and fix https://github.com/svix/svix-webhooks/security/dependabot/57, but looking at the diff I'm not sure it actually fixes it.
`yarn upgrade openapi-to-postmanv2`

Upgrade openapi-to-postmanv2 to latest version

---

server/openapi.json
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/message.rs

Add support for the `with_content` parameter to three endpoints, defaulting them to `true` for backwards compatibility.
For `GET /api/v1/app/{app_id}/endpoint/{endpoint_id}/msg/`, the "list attempted messages by endpoint" route:
`with_content` set to false replaces the message payload with an empty object `{}`, in the same way that `with_content` functions on other message-related endpoints.
For `GET /api/v1/app/{app_id}/attempt/endpoint/{endpoint_id}/`, the "list attempts by endpoint" route:
`with_content` set to false replaces the response payload of the attempt with the string `{}`.
For `GET /api/v1/app/{app_id}/attempt/msg/{msg_id}/`, the "list attempts by message id" route:
`with_content` set to false replaces the response payload of the attempt with the string `{}`.

Server: Add `with_content` to attempt listing endpoints

---

server/svix-server/src/core/idempotency.rs
server/svix-server/src/error.rs
server/svix-server/src/queue/rabbitmq.rs
server/svix-server/src/worker.rs

This cleans up some of our error macros to make them a bit more ergonomic (no need to manually call `format!`), and add more detail by using the `Debug` representation of errors at certain callsites.

Cleanup error macros

---

server/Cargo.lock
server/svix-server/Cargo.toml

Ouroboros is a transitive dep of SeaORM, and SeaORM bump their dependency on it in the `0.12` release.
Refs: https://github.com/svix/svix-webhooks-private/security/dependabot/31
In truth there are a handful of crates that had to be updated in concert to get the build green after bumping `sea-orm`.
- `sea-orm`, `0.11.3` -> `0.12.2`
- `sqlx`, `0.6.2` -> `0.7.1`
- `jwt-simple`, `0.10.8` -> `0.11.6`

Server: update ouroboros via sea-orm

---

server/openapi.json
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils/mod.rs

We were missing the documentation for these fields which made the API a bit unclear in some areas. For example, `with_content` was obtuse. I took the opportunity to document many other fields too.

OpenAPI: add missing field documentation for query params.

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/config.default.toml
server/svix-server/src/cfg.rs
server/svix-server/src/lib.rs
server/svix-server/src/main.rs
server/svix-server/tests/utils/mod.rs

Sentry is a useful error-reporting service
This adds two new config values - `sentry_dsn` and `sentry_environment`. When `sentry_dsn` is provided, we enable Sentry reporting at the provided DSN with the supplied environment name.
Currently, we report both panics (handled by default by Sentry), and all warnings/errors logged through `tracing`

Server: Add Sentry support

---

deny.toml

To be removed once webpki has a safe release to upgrade to

Update cargo deny config to temporarily ignore webpki advisory

---

deny.toml
server/Cargo.lock
server/svix-server/Cargo.toml

Solves #1042 by updating the version of `serde` specified in the server's `Cargo.toml` to ensure `serde_derive`'s version is not affected by the binary blob.
Similarly ensures that all versions of the crate with the blob are banned via `cargo-deny`.

Avoid serde_derive blob and ban affected versions via cargo-deny

---

bridge/Cargo.lock
bridge/svix-bridge/Cargo.toml
bridge/svix-bridge/src/allocator.rs
bridge/svix-bridge/src/main.rs
bridge/svix-bridge/src/metrics.rs

This PR changes the global allocator for svix-bridge to jemalloc. Said allocator is only enabled on non-Windows targets.
This also includes some runtime memory metrics exposed via opentelemetry.

Bridge: Use jemalloc as the global allocator, except for windows

---

bridge/Cargo.lock
bridge/svix-bridge/Cargo.toml
bridge/svix-bridge/src/main.rs

See also #1024 
lazy_static is unmaintained, once_cell is the new hotness. This PR swaps out the one lazy_static invocation for the equivalent lazy construct from once_cell.

Bridge: Replace lazy_static macro with once_cell

---

bridge/svix-bridge-plugin-queue/src/config.rs
bridge/svix-bridge-plugin-queue/src/error.rs
bridge/svix-bridge-plugin-queue/src/gcp_pubsub/mod.rs
bridge/svix-bridge-plugin-queue/src/lib.rs
bridge/svix-bridge-plugin-queue/src/rabbitmq/mod.rs
bridge/svix-bridge-plugin-queue/src/receiver_output/mod.rs
bridge/svix-bridge-plugin-queue/src/redis/mod.rs
bridge/svix-bridge-plugin-queue/src/sender_input/mod.rs
bridge/svix-bridge-plugin-queue/src/sqs/mod.rs
bridge/svix-bridge-plugin-queue/tests/gcp_pubsub_consumer.rs
bridge/svix-bridge-plugin-queue/tests/rabbitmq_consumer.rs
bridge/svix-bridge-plugin-queue/tests/redis_stream_consumer.rs
bridge/svix-bridge-plugin-queue/tests/sqs_consumer.rs
bridge/svix-bridge/src/config/mod.rs

Essentially, once we've got omniqueue in bridge, we can "debulk" a lot
of the consumer code by un-traiting it.
A single concrete type can hold an input config which can be used to
produce a `DynConsumer` which can then be used to run the consumer loop.
This diff takes us _most of the way there_, keeping the trait, but now
building a single type which implements it from a range of config
values.

Bridge: debulk consumer code

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/main.rs

This adds jemalloc as the global allocator.
This is gated by an optional feature (on by default), which should be turned off in the case of building on windows as jemalloc is not supported on that platform.

Server: add jemalloc

---

.github/workflows/bridge-release.yml
.github/workflows/server-release.yml

We want to also release arm64 images for both server and bridge. These are popular targets and we should be building for them.
The builds take forever, but at least it's arm64 + amd64, and it only runs on release anyway.

Server/Bridge: enable arm64 docker builds.

---

bridge/Dockerfile
server/Dockerfile

Images built on Debian 12 were failing due to openssl lib issue. Upgrading to Debian 12 will require more significant changes to our dependencies, so for now use `bullseye`-based images, which will keep our images on latest 11.x release.
Fixes #1061

Fix Docker Images

---

bridge/Dockerfile

We normally try to compile all transitive deps in their own layer when building a Docker image.
When we removed `generic-queue`, we neglected to also cleanup references to it in the Dockerfile to support this transitive dep layer.
This diff removes those now-orphaned references.

Bridge: remove refs to generic-queue in Dockerfile

---

bridge/Cargo.lock
server/Cargo.lock

Updates webpki to avoid a DoS vulnerability.
Ref:
- <https://github.com/advisories/GHSA-8qv2-5vq6-g2g7>
- <https://github.com/briansmith/webpki/issues/69#issuecomment-1699894848>

Update webpki for server and bridge

---

.github/workflows/server-docker-image.yml
server/Dockerfile

Following #1061, update the svix-server docker image to debian bookworm.
Add a CI workflow to test image build and container execution.

server: Update docker image to bookworm and add CI workflow to test it

---

.github/workflows/javascript-release.yml

It is useful to have pre-release versions of the JS library for development, before the public release. 
Publish JS package using `--tag next` on all new pushes to `main` (not just those tagged with a version). Uses `github.ref_type` variable to avoid duplicating the workflow code.

Publish pre-release version of JS package on pushes to main

---

.github/workflows/javascript-release.yml

See https://github.com/svix/svix-webhooks/actions/runs/6173804183/job/16756967707
Publishing the prerelease package failed because we didn't set the correct version before `yarn publish`
This uses `yarn version --prerelease --preid next`. For example, `1.12.0` becomes `1.12.0-next.1` before publishing, so it doesn't conflict with the current released version. 
Also added a filter to only run the workflow if the javascript directory was changed.

Set prerelease version before publishing to npm in Github action

---

server/svix-server/src/error.rs

We currently lose `#[track_caller]` information when our `impl<T> Traceable<T> for Result<T>` impl is used, due to the use of `Result::map_err`
Write a manual `match` expression, so that we correctly propagate caller information.

Server: Avoid using `map_err` in order to preserve `#[track_caller]`

---

ruby/templates/api_client_typhoeus_partial.mustache

Currently if there is a general network error, there is no retry to send the message. This fix is suggested here: https://github.com/svix/svix-webhooks/issues/964#issuecomment-1722595011
if there is a general network error the response code is 0. In this case we should still retry.
Note: there is no guarantee the second retry will work. Maybe it would be nice to be able to configure the number of retries, if this fix does indeed improve the original issue.
There seem to be no specs for this part of the code at all, please could you confirm whether a test needs to be added here.

fix: retry if response code is 0

---

go/eventtype.go

This is to help add support for sending `expunge` through the `svix-cli`.

Libs(Go): add `EventType.DeleteWithOptions`

---

go/eventtype.go

I forgot I was writing Go and neglected to check for `nil` when optionally setting options.
Keep checking for `nil` all the way down.

Libs(Go): extra nil check for options in `EventType.DeleteWithOptions`

---

.github/workflows/server-ci.yml

Server CI was failing because of "no space left on device" while building test binaries via `run-tests.sh`.
Bump to the latest version of the rust cache action.
Updating to the latest rust-cache seems to reset the starting disk to `70Gb` which leaves around `14Gb` for the rest of the job to run.
This may just be a bandaid, perhaps requiring us to "bump the cache prefix" in the future to shed accumulated artifacts. Unsure.
Still, bumping the action seems to solve the immediate need.

Bump version and update changelog.

---

.github/workflows/javascript-release.yml

The trigger was only on changes to `javascript/**`, but the lib changes when the openapi spec if updated. The `javascript` directory is not always modified in a commit since some updates are made by the codegen step.

Publish pre-release javascript package when openapi spec changes

---

csharp/Svix/Abstractions/IEventType.cs
csharp/Svix/EventType.cs

The .net client does not have the option to hard delete an EventType, only to archive it.
Allow to send the 'expunge' parameter as a bool optional parameter with the Archive() and ArchiveAsync() methods.

Allow EventType hard delete from .net client.

---

.github/workflows/bridge-ci.yml
bridge/Cargo.lock
bridge/svix-bridge/Cargo.toml

`lexical` is a transitive dependency added to the graph via `deno_ast`. As of `deno_ast` version `0.28.0` they no longer depend on `lexical`.
In order to bump `deno_ast` we also need to bump `deno_runtime`.
N.b. I looked at bumping us all the way up to the latest for both ast/runtime, but the caused the transformation tests to segfault, so... I'm deferring that effort. For now, I'm bringing us to the smallest upgrade that also avoids the security issue.
Refs: https://github.com/svix/svix-webhooks/security/dependabot/66

Bridge: avoid lexical by upgrading deno_ast, deno_runtime

---

ruby/lib/svix/message_api.rb
ruby/spec/message_api_spec.rb

This PR adds the ability to pass options in the `message.get` calls. [The Documentation](https://api.svix.com/docs#tag/Message/operation/v1.message.get) shows that the "with_content" option is valid, but the ruby wrapper made no accommodation to pass the option.

Libs(Ruby) Accept options on message get

---

.github/workflows/javascript-release.yml

Last run of the JS release action failed since the prerelease version already existed in npm https://github.com/svix/svix-webhooks/actions/runs/6472292636/job/17572620116
Add commit SHA to prerelease version to avoid overlaps

Add commit SHA to prerelease version to avoid overlaps

---

go/endpoint.go

The endpoint transformation update didn't assign the request (payload) correctly, resulting in an error.
Assign the request
Corrected spelling of func name

Libs(Go): corrected name + req assign

---

server/svix-server/migrations/20231010170520_messagecontent_table.down.sql
server/svix-server/migrations/20231010170520_messagecontent_table.up.sql
server/svix-server/src/db/models/message.rs
server/svix-server/src/db/models/messagecontent.rs
server/svix-server/src/db/models/mod.rs
server/svix-server/src/expired_message_cleaner.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/worker.rs
server/svix-server/tests/e2e_message.rs

Move message content from `message.payload` to its own table. Data is stored as `bytea` for future flexibility. Payloads will be queried from the new table but will fall back to the existing column, which has been renamed in code for clarity. The `expired_message_cleaner` process has been updated to expire records from both tables.

Add `messagecontent` model

---

bridge/Cargo.lock
bridge/svix-bridge/Cargo.toml
bridge/svix-bridge/src/config/mod.rs
bridge/svix-bridge/src/config/tests.rs

The implementation used for variable substitution in `envsubst` makes it illegal for env vars to point to values with characters that could make the replacement text look like a new variable to be substituted. This restriction is needed to make replacements deterministic.
The crux of the issue for us is this validation prevents us from defining env vars that point to JSON strings, which is necessary for GCP's credential handling scheme and can otherwise show up in the wild as in the case of https://github.com/svix/svix-webhooks/issues/1084 where vars injected by vscode contained braces which triggered a validation error.
`shellexpand` has no such requirement, allowing JSON to appear in values without failing.
Key difference:
1. `shellexpand` reads directly from the env instead of from a …

Bridge: switch `envsubst` for `shellexpand`

---

bridge/Cargo.lock

Refs: <https://github.com/svix/svix-webhooks/security/dependabot/74>
Formerly we had a runtime dep on a vulnerable version of `rustix`. This was transitive, and introduced via `clap`. Bumping clap removed this dependency from our tree.
There is still one vulnerable version introduced via `opentelemetry-otlp`, but since it's a build-dep it's less of a concern (see the advisory for the rationale).
```
$ cargo tree -p rustix@0.38.8 -i
rustix v0.38.8
└── tempfile v3.7.1
└── prost-build v0.11.9
└── tonic-build v0.8.4
[build-dependencies]
└── opentelemetry-proto v0.1.0
└── opentelemetry-otlp v0.11.0
└── svix-bridge v1.13.0 (/home/onelson/Projects/svix-webhooks/bridge/svix-bridge)
```
If we can update the various otel-related deps, we might be able to bump `rustix` or remove it entirely, but …

Bridge: remove rustix via clap bump

---

server/Cargo.lock

Same boat for `svix-server` as with `svix-bridge` in #1109
Bumping clap removes the sole runtime dependency on `rustix`, but it still exists in the dep tree impacting only compile-time code paths.
```
$ cargo tree -p rustix@0.38.4 -i
rustix v0.38.4
└── tempfile v3.7.0
├── figment v0.10.10
│   └── svix-server v1.13.0 (/home/onelson/Projects/svix-webhooks/server/svix-server)
├── prost-build v0.9.0
│   └── tonic-build v0.6.2
│       [build-dependencies]
│       └── opentelemetry-otlp v0.10.0
│           └── svix-server v1.13.0 (/home/onelson/Projects/svix-webhooks/server/svix-server)
└── sqlx-macros-core v0.7.1
└── sqlx-macros v0.7.1 (proc-macro)
└── sqlx v0.7.1
├── sea-orm v0.12.2
│   └── svix-server v1.13.0 (/home/onelson/Projects/svix-webhooks/server/svix-server)
├── sea-query-binder …
```

Server: remove rustix via clap bump

---

server/svix-server/src/expired_message_cleaner.rs

This clone is totally unnecessary. It's not a huge deal since the underlying PgPool is ARCed, but still.

Remove totally unnecessary DatabaseConnection clone

---

server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs
server/svix-server/tests/worker.rs

Replace `get(0)` with `first` to appease beta Clippy.

Fix Clippy lint errors

---

server/Cargo.lock

This is a transitive dependency, the locked version of 
which has been yanked. Updating so that `security_audit` 
CI step will pass.

Update `ahash` dependency

---

server/Cargo.lock
server/svix-server/Cargo.toml

The issue for which we originally forked aide appears to have been
fixed here: https://github.com/tamasfe/aide/pull/73
Our code compiles using the latest aide version, and the openapi
spec shows no changes, so I think we're good.

Stop forking aide

---

deny.toml
server/Cargo.lock
server/svix-server/Cargo.toml

Update dependencies (and explicitly do so for Redis in Cargo.toml).
Also ignore `RUSTSEC-2023-0071` security advisory for now, as there's no 
workaround at the moment anyway.

Cargo update

---

bridge/Cargo.lock

Cargo Deny woke up for a version of `time` in the bridge lockfile, now removed by updating `chrono`.

Bridge: bump `chrono`, `time`

---

README.md

After following the README I had issues setting up the operational webhooks locally, this was due to the README suggesting that the setting `operational_webhook_address` is commonly set to `http://127.0.0.1:8071/`
See following discussion for more details: [https://github.com/svix/svix-webhooks/discussions/1125](https://github.com/svix/svix-webhooks/discussions/1125)
The setting should be `http://127.0.0.1:8071` so this PR is just updating the README.

Update README.md operational server

---

server/svix-server/src/expired_message_cleaner.rs
server/svix-server/tests/e2e_message.rs

Widens the period of the cleaner to be 12h when row counts cleaned dips
below the batch size.
The legacy cleaner query also has its timeout extended as was done when
troubleshooting the cleaner for one deployment. We may need to do the
same for the new `messagecontent` table, but for now I left it as-is.
Some additional refactors were needed with the 12h period to ensure the
process would not block (for hours) when the shutdown atomic gets set.
Additionally, since the "worst case" search for the `message` table
cleaner is the inevitable conclusion when a deployment starts writing to
`messagecontent` instead, a check is done when the cleaner first starts
up to see if there are any pending payloads at all in the `message` table.
This allows us to skip repeatedly scanning a table that will …

Server: backport expired message cleaner updates

---

server/svix-server/src/core/cache/memory.rs
server/svix-server/src/core/cache/mod.rs
server/svix-server/src/core/cache/none.rs
server/svix-server/src/core/cache/redis.rs

Since `StringCacheValue` is always a String, there's not much point in having a separate type for it. This adds a marker trait that gets implemented in the macro so that we can have still have type safety around cache keys that store strings, but otherwise change the relevant cache methods to just take/return `&str`/`String` as appropriate.

Simplify string caching

---

javascript/templates/api/api.mustache

The response body was not read correctly, causing the SDK to throw errors like `Message: "Unknown API Status Code! Body: "[object Object]"`. This happens when the API returns an unexpected status code (like 500) or when the content type is not defined.
Using `await response.body.text()` should return the actual response body.

[javascript] Fix thrown error message when API status code is unknown

---

bridge/Cargo.lock

We had a yanked version of the crate in the lockfile. This diff bumps to the highest available minor.

Bridge: bump transitive dep on elliptical-curve

---

javascript/templates/api/api.mustache

In a previous PR https://github.com/svix/svix-webhooks/pull/1160 I added an error message that is thrown before checking the response types, when no content type is defined. That is causing issues in some cases since there are cases in which the API returns no content type in the response (for example, when the response code is `202 Accepted`).
Undoing that change for now. We need a better way to check for invalid content-type responses, but I want to get this fix out first.

[javascript] Fix no content-type error for empty responses

---

server/Cargo.toml

Extracted from #1129.
The second version of the resolver is the default for edition 2021+ crates, but for workspaces it has to be set like this because there is no `workspace.edition`.
Set `resolver = "2"` to avoid Cargo feature unification between host (proc-macro / build script) dependencies and target (regular) dependencies. Could improve or worsen compile times, but for runtime and code size it can only realistically improve things. It's also good for forwards compatibility.

server: Don't unify features of host and target dependencies

---

server/Cargo.lock
server/Cargo.toml
server/svix-server/Cargo.toml

… of the svix fork. Pre-requisite for omniqueue integration.
Omniqueue pulls in a dependency that needs a newer version of hyper.
Upgrade to the latest rev of the fork.

Upgrade hyper to 0.14.28

---

server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs

Preparation for omniqueue integration, in particular solves the problem discussed [here](https://github.com/svix/svix-webhooks/pull/1129/files#r1463610989).
Refactor redis queue implementation to not take `TaskQueueDelivery` parameter in `ack`, `nack` methods, instead only taking references to the fields it is interested in, specifically *ex*cluding the `acker` field (such that it can be borrowed mutably when calling one of these methods).
Additionally, I improved one of the methods to use implicit named format arguments.

server: Some redis queue refactorings

---

go/webhook_test.go
javascript/src/webhook.test.ts
rust/src/webhooks.rs

There was a bug in the code which meant that the signatures are only compared up to the length of the shorter signature, which means that an attacker can just pass `v1,` as the signature and that will always pass verification.
This change fixes it so that the length of the signature is also taken into account when comparing, to make sure that it's always the same length before comparing.
Manually verified all of the other libraries are correct, and added tests to JavaScript and Go (even though they were also not affected).
Many thanks to Fredrik Meringdal (@fmeringdal) for the report.

Rust verification library: fix comparison of different length signatures

---

bridge/testing-docker-compose.yml
server/docker-compose.yml
server/testing-docker-compose.yml

Compatibility with podman-compose w/ default configuration.
Use `docker.io/` prefix for image names from DockerHub.

Use fully-qualified image names in docker-compose files

---

.github/workflows/bridge-ci.yml
.github/workflows/bridge-release.yml
.github/workflows/rust-lint.yml
.github/workflows/rust-release.yml
.github/workflows/server-ci.yml
.github/workflows/server-release.yml

Subset of the changes I did for omniqueue's CI yesterday: https://github.com/svix/omniqueue-rs/pull/23
CI failures are unrelated and will be fixed through #1194.

CI improvements

---

bridge/Cargo.lock
bridge/svix-bridge/Cargo.toml
bridge/svix-bridge/src/main.rs
bridge/svix-bridge/src/metrics.rs
server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/lib.rs

They were quite outdated.
Upgrade!

Upgrade opentelemetry dependencies

---

.github/workflows/bridge-ci.yml
.github/workflows/bridge-release.yml
.github/workflows/rust-lint.yml
.github/workflows/server-ci.yml
.github/workflows/server-docker-image.yml
.github/workflows/server-release.yml

About the first commit: In  #1188 there were some panics in tests, but without a backtrace they were pretty useless (they occurred inside the Rust standard library). By setting `RUST_BACKTRACE=1` in the two CI jobs that run tests, we should get more useful output if this ever happens again in the future.
About the second commit: Simply less scary, `master` of the checkout action could have different behavior with the next major version.

Further CI improvements

---

.github/workflows/bridge-ci.yml
.github/workflows/other-lint.yml
.github/workflows/rust-lint.yml
.github/workflows/rust-release.yml
.github/workflows/server-ci.yml

Caches saved from PRs count against the 10GB cache limit after which old cache entries are evicted, but they rarely get re-used as they're only available for further commits on the same PR.
We hit this limit all the time: https://github.com/svix/svix-webhooks/actions/caches
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

ci: Limit when CI cache is written

---

csharp/Svix/Abstractions/IApplication.cs
csharp/Svix/Abstractions/IBackgroundTask.cs
csharp/Svix/Abstractions/IEndpoint.cs
csharp/Svix/Abstractions/IEventType.cs
csharp/Svix/Abstractions/IIntegration.cs
csharp/Svix/Abstractions/IMessage.cs
csharp/Svix/Abstractions/IMessageAttempt.cs
csharp/Svix/Application.cs
csharp/Svix/BackgroundTask.cs
csharp/Svix/Endpoint.cs
csharp/Svix/EventType.cs
csharp/Svix/Integration.cs
csharp/Svix/Message.cs
csharp/Svix/MessageAttempt.cs

Our list endpoints, e.g., Endpoint.List, Endpoint.ListAsync, do not return pagination data, which makes the library unusable if results are paginated. We need to return the full response, and not just the data portion of it.
Return the full response (`data`, `iterator` and `done`) from the listing methods.
**This is a breaking change.** Users upgrading to the latest version of the C# lib will need to update their usage of these endpoints. `var res = Application.List(...)` becomes `var res = Application.List(...).Data`.
Fixes #1200

[lib/c#] Return iterator information in list endpoints

---

.github/workflows/bridge-ci.yml
.github/workflows/bridge-security.yml
.github/workflows/csharp-lint.yml
.github/workflows/csharp-release.yml
.github/workflows/go-lint.yml
.github/workflows/java-lint.yml
.github/workflows/java-release.yml
.github/workflows/javascript-lint.yml
.github/workflows/javascript-release.yml
.github/workflows/kotlin-lint.yml
.github/workflows/kotlin-release.yml
.github/workflows/other-lint.yml
.github/workflows/python-lint.yml
.github/workflows/python-release.yml
.github/workflows/ruby-lint.yml
.github/workflows/ruby-release.yml
.github/workflows/rust-release.yml
.github/workflows/rust-security.yml
.github/workflows/server-ci.yml
.github/workflows/server-security.yml
.github/workflows/update-postman.yml

I saw breakage from `arguments: --manifest-path` in a private PR, but even if the old way was still working, is nice to use the dedicated option.

ci: Simplify cargo-deny-action usage

---

bridge/testing-docker-compose.yml

CI for the bridge component is broken in #1217, #1218.
Upgrade testing container images. This is just a shot in the dark as upgrading containers has helped with similar issues before.

bridge: Upgrade docker containers used for testing

---

server/svix-server/src/core/cache/redis.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/redis/mod.rs
server/svix-server/tests/it/queue.rs

Our own redis traits are a maintenance burden and not necessary.
Implement `redis::aio::ConnectionLike`, get `redis::AsyncCommands` impl for free :sparkles:

server: Remove PooledConnectionLike in favor of upstream traits

---

bridge/Cargo.lock
bridge/svix-bridge-plugin-queue/Cargo.toml
bridge/svix-bridge-plugin-queue/src/config.rs
bridge/svix-bridge-plugin-queue/src/lib.rs
bridge/svix-bridge-plugin-queue/src/rabbitmq/mod.rs
bridge/svix-bridge-plugin-queue/src/redis/mod.rs
bridge/svix-bridge-plugin-queue/tests/it/redis_stream_consumer.rs

The main interesting change here is the omniqueue upgrade. Changes for that are: https://github.com/svix/omniqueue-rs/compare/247904053bcf90cf693df4429092923bf97770eb...b6383db507ca2d61da1b31dfb4ea0981cf7c6881
I don't really know if the earlier commits in that range contain any runtime behavior changes (commit messages suggest no). Also the config struct updates I did were my best guesses as to what we might want to do about the new omniqueue redis backend features. Happy to iterate on all of this.

bridge: Upgrade dependencies

---

.github/workflows/server-ci.yml

- Counts test build time against the build step
- Aborts earlier in case tests fail to build

ci: Build server tests earlier

---

bridge/Cargo.lock

The previously-locked version of async-executor is yanked.
I already had to re-bump the `Cargo.lock` due to a different yank earlier today, and after merging `cargo-deny` failed again due to another yanked crate 🫠

bridge: Bump lockfile again

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/queue/redis.rs

In #1228, I needed some extra context on failing assertions.
Prefer `assert_eq!`, `assert_matches!` to check expected emptiness of a value, such that if the assertion fails, the non-empty value is printed.

server: Print more info on failed assertions in redis module

---

server/svix-server/src/cfg.rs
server/svix-server/src/core/security.rs
server/svix-server/src/core/types/mod.rs
server/svix-server/src/error.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/src/v1/utils/patch.rs
server/svix-server/src/worker.rs

Removes the need to fully qualify `std::result::Result` anywhere except the one place the alias is introduced.
Allow our `Result` alias to be a proper drop-in replacement for std's result by having an optional second type parameter.

server: Add defaulted generic error parameter to error::Result

---

server/Cargo.toml
server/svix-server/Cargo.toml
server/svix-server/src/cfg.rs
server/svix-server/src/core/cache/mod.rs
server/svix-server/src/core/webhook_http_client.rs
server/svix-server/src/error.rs
server/svix-server/src/redis/mod.rs
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server_derive/Cargo.toml

Explanations for the rust lints can be found [here](https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html).
Explanations for the clippy lints can be found [here](https://rust-lang.github.io/rust-clippy/master).

server: Enable some allow-by-default lints

---

bridge/Cargo.lock
bridge/svix-bridge-plugin-queue/Cargo.toml
bridge/svix-bridge-plugin-queue/src/gcp_pubsub/mod.rs
bridge/svix-bridge-plugin-queue/src/lib.rs
bridge/svix-bridge-plugin-queue/src/rabbitmq/mod.rs
bridge/svix-bridge-plugin-queue/src/receiver_output/mod.rs
bridge/svix-bridge-plugin-queue/src/redis/mod.rs
bridge/svix-bridge-plugin-queue/src/sender_input/mod.rs
bridge/svix-bridge-plugin-queue/src/sqs/mod.rs
server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/rabbitmq.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/redis/mod.rs

The redis omniqueue PR (#1228) is a bit on the large side and still has one inexplicably failing test. Pull out one unrelated redis refactoring and the omniqueue upgrade (also for bridge, new in this PR) to land changes incrementally.

Preparation for redis omniqueue usage

---

bridge/svix-bridge/src/main.rs
server/svix-server/src/lib.rs
server/svix-server/src/main.rs
server/svix-server/tests/it/utils/mod.rs

Previously, it was possible that tests would overwrite each other's intended logging configuration.

Tracing initialization improvements

---

bridge/Cargo.lock
server/Cargo.lock

bb8 0.8.2 fixes an important bug affecting us where acquiring a connection from a pool could take super long if a long-running request was blocking another connection from being returned to the pool (or something along those lines). Also CI failed in #1228 due to a broken dependency for some fringe OSes (and it's easier to bump than to add an exception to `deny.toml`).
Upgrade all the dependencies! … except the `svix` library, to avoid pulling in hyper 1.0 for now.

Update Cargo lockfiles

---

bridge/Cargo.toml
server/Cargo.toml

This takes extra compile time on first build of quote, but the cost is recouped by faster runtime of proc-macros, even for clean `cargo check`. (tested for server, but bridge has just as many proc-macro dependencies)

Make procedural macros faster by optimizing quote

---

rust/src/error.rs

Since we throw away the original error, let's debug-print it to capture more information

Debug-print error when constructing 'Error::Generic'

---

ruby/Gemfile.lock
ruby/svix.gemspec

We are going to use Svix for our webhooks and we have a Gemfile with `bundler 2.4.21` and a `ruby version 2.7.8`.
But due to `bundler (>= 2.2.10)` in svix/ruby/gemfile.lock our build is failing on Heroku because `>=` tries to get the latest version of bundler which is currently `2.5.6` that requires ruby version 3.0 (which we don't have in our repo). So basically we need to restrict the bundler from updating to the latest version.
There are two options:
- We can include the bundler dependency but with the `~>` sign, not the `>=` (so that it will not jump to the latest version).
- As we do not have any need to add bundler as a dependency we can remove it too.
I have implemented the 2nd one in my PR.

Remove Bundler as a dependency

---

.github/workflows/other-lint.yml
bridge/Cargo.lock
bridge/svix-bridge-plugin-queue/Cargo.toml
server/Cargo.lock
server/run-tests.sh
server/svix-server/Cargo.toml
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/rabbitmq.rs

… and one related dependency.
Also fix a regression in the rabbitmq queue backend that would result in tasks from a new API process not being picked up by old worker processes due to missing message IDs.

Upgrade omniqueue

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/core/webhook_http_client.rs

Trust DNS was renamed: https://bluejekyll.github.io/blog/posts/announcing-hickory-dns/

Upgrade trust-dns-resolver -> hickory-resolver

---

.github/workflows/other-lint.yml
server/run-tests.sh
server/svix-server/src/core/cache/redis.rs
server/svix-server/src/core/types/mod.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/redis/mod.rs
server/svix-server/tests/it/main.rs
server/svix-server/tests/it/redis_queue.rs
server/svix-server_derive/Cargo.toml
server/svix-server_derive/src/lib.rs

The redis tests are now run once for the redis backend, and once for the redis cluster backend in run-tests.sh. Previously, all six runs would execute these tests, most of the time with the redis backend. Since these tests are relatively low-level, they are not affected by other configuration changes. It really only makes sense to run e2e tests with all the different configuration combinations.
@svix-onelson you were previously not convinced about this approach of using `#[ignore]`d tests plus extra `--ignored` test runs w.r.t. rabbitmq. How do you feel about it here given the diff?

server: Reduce redundant test runs

---

.github/workflows/rust-lint.yml
rust/.rustfmt.toml
rust/src/api.rs
rust/src/lib.rs
rust/src/request.rs
rust/src/webhooks.rs

Start with the smallest crate / workspace in the repo. Same thing that was done for omniqueue before: https://github.com/svix/omniqueue-rs/pull/54

rust: Use nightly rustfmt to control comment wrapping and import formatting

---

server/openapi.json
server/svix-server/Cargo.toml
server/svix-server/src/lib.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/health.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/tests/it/e2e_health.rs
server/svix-server/tests/it/main.rs

server: Don't require trailing slash at the end of request paths

---

server/svix-server/src/lib.rs

`serde_json::Value` is [very memory-inefficient](https://github.com/serde-rs/json/issues/635) and even if it wasn't, this deserialization + serialization cycle would be pointless.

Don't make a serialization roundtrip in openapi.json route

---

server/svix-server/src/v1/mod.rs

Now that we normalize paths, any routes registered with a slash at the end can't actually be hit at all as the trailing slash will be stripped before the request goes to the router.
Follow-up to #1270

Fix route of development/echo

---

server/svix-server/src/lib.rs
server/svix-server/src/main.rs
server/svix-server/tests/it/utils/mod.rs

… so that logs are only printed for failing tests.

server: Use tracing_subscriber's TestWriter in tests

---

rust/src/webhooks.rs
server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/cfg.rs
server/svix-server/src/core/cryptography.rs
server/svix-server/src/core/message_app.rs
server/svix-server/src/core/types/mod.rs
server/svix-server/src/core/webhook_http_client.rs
server/svix-server/src/lib.rs
server/svix-server/src/redis/mod.rs
server/svix-server/src/worker.rs
server/svix-server/tests/it/main.rs

Since #1244, we were no longer installing a global tracing subscriber that would print logs from (failing) tests. With this, we do again.
First two commits are drive-by improvements in response to local warnings from my nightly toolchain about redundant imports.

Some testing improvements

---

bridge/svix-bridge/src/config/mod.rs
server/.clippy.toml
server/Cargo.toml
server/svix-server/src/cfg.rs
server/svix-server/src/core/message_app.rs
server/svix-server/src/core/webhook_http_client.rs
server/svix-server/src/db/models/application.rs
server/svix-server/src/db/models/applicationmetadata.rs
server/svix-server/src/db/models/endpoint.rs
server/svix-server/src/db/models/endpointmetadata.rs
server/svix-server/src/error.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/endpoints/endpoint/crud.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs
server/svix-server/src/v1/endpoints/event_type.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/worker.rs
server/svix-server/tests/it/e2e_attempt.rs
server/svix-server/tests/it/e2e_endpoint.rs
server/svix-server/tests/it/e2e_message.rs
server/svix-server/tests/it/utils/common_calls.rs
server/svix-server/tests/it/utils/mod.rs

More linting and uniform code style reduces the things to watch out for in review. I'm running a nightly toolchain locally now, and have noticed some extra lints from that. Also enabled one extra clippy lint via `Cargo.toml`.

More clippy and rustfmt things

---

.github/workflows/server-ci.yml
server/.rustfmt.toml
server/svix-server/src/core/cache/memory.rs
server/svix-server/src/core/cache/redis.rs
server/svix-server/src/core/cryptography.rs
server/svix-server/src/core/idempotency.rs
server/svix-server/src/core/message_app.rs
server/svix-server/src/core/operational_webhooks.rs
server/svix-server/src/core/permissions.rs
server/svix-server/src/core/security.rs
server/svix-server/src/core/types/metadata.rs
server/svix-server/src/core/types/mod.rs
server/svix-server/src/core/webhook_http_client.rs
server/svix-server/src/db/models/eventtype.rs
server/svix-server/src/db/models/message.rs
server/svix-server/src/db/models/messageattempt.rs
server/svix-server/src/db/models/messagecontent.rs
server/svix-server/src/db/models/messagedestination.rs
server/svix-server/src/error.rs
server/svix-server/src/expired_message_cleaner.rs
server/svix-server/src/lib.rs
server/svix-server/src/main.rs
server/svix-server/src/redis/cluster.rs
server/svix-server/src/v1/endpoints/application.rs
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/endpoint/secrets.rs
server/svix-server/src/v1/mod.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/src/worker.rs

After #1268 for the client library and #1280 for the bridge workspace, this is the last PR in this series for more (import) formatting consistency.
PRs for comment wrapping / doctest formatting will likely follow, in the coming weeks.

server: Reformat remaining imports using nightly

---

.github/workflows/bridge-ci.yml
.github/workflows/server-ci.yml
.github/workflows/server-docker-image.yml
README.md
server/README.md

The docker-compose command is apparently no longer available in GitHub's CI runners by default (CI failed on main).

Switch to Docker Compose v2

---

kotlin/lib/src/main/kotlin/Application.kt
kotlin/lib/src/main/kotlin/Authentication.kt
kotlin/lib/src/main/kotlin/Endpoint.kt
kotlin/lib/src/main/kotlin/EventType.kt
kotlin/lib/src/main/kotlin/Integration.kt
kotlin/lib/src/main/kotlin/Message.kt
kotlin/lib/src/main/kotlin/MessageAttempt.kt
kotlin/lib/src/main/kotlin/MessageAttemptListOptions.kt
kotlin/lib/src/main/kotlin/MessageListOptions.kt
kotlin/lib/src/main/kotlin/Statistics.kt
kotlin/lib/src/main/kotlin/Svix.kt
kotlin/lib/src/main/kotlin/Webhook.kt
kotlin/lib/src/main/kotlin/exceptions/ApiException.kt
kotlin/lib/src/test/com/svix/kotlin/BasicTest.kt
kotlin/lib/src/test/com/svix/kotlin/WebhookTest.kt

Mostly automated with `ktlint --format`. Not needed right now, probably because CI is running an older version of ktlint, but doesn't hurt either.

More ktlint formatting

---

server/svix-server/tests/it/e2e_operational_webhooks.rs
server/svix-server/tests/it/integ_webhook_http_client.rs

CI is failing
Silence the lints because they're not actually helpful here.

server: Silence dead_code warnings for a few test struct fields

---

server/svix-server/tests/it/integ_webhook_http_client.rs

It doesn't make sense for the server tokio task to continue running after the `TestReciver` is dropped. In usual `tokio::test`s it's probably stopped at the end of the test anyways, but stopping it in `Drop` seems cleaner.

server: Abort server tokio task when TestReceiver drops

---

javascript/src/index.ts

The `headers` methods were named inconsistently. Let's 
make them match other methods and deprecate appropriately.

Fix method naming consistency

---

javascript/src/index.ts
openapi.json

This updates the OpenApi spec/Javascript lib with new routes 
for oauth support. We are keeping the changes limited to Js
for now until the API is finalized.

Add oauth support to javascript

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/queue/redis.rs
server/svix-server/src/redis/cluster.rs

Due to recent changes in the redis library, a PING command is now routed to all main nodes by default, rather than a single random node, and all must succeed. This makes connections particularly fragile if a single node is having transient issues. So, in an effort to maximize uptime, let's require a successful response from only one node.
This also updates omniqueue to the same version we use downstream. It includes the same version of the redis lib/bb8.

Update redis health check

---

server/svix-server/Cargo.toml

We should enable this with no_further_delay

Enable redis `tcp_nodelay`

---

go/svix.go

The `AppPortalAccess` function in the golang SDK takes a `ReadOnly` parameter, of type `NullableBool`. However, the `NullableBool` struct and associated functions aren't accessible outside the SDK, so it's not possible to construct a `NullableBool` to pass into this function. 
For other types (`NullableString`, `NullableInt32`), there's a set of wrapper functions defined in the `svix` package. 
Add a `NullableBool` function to the svix package, next to the existing wrapper functions.

Add NullableBool function

---

bridge/svix-bridge-plugin-queue/src/config.rs
bridge/svix-bridge-types/src/lib.rs
bridge/svix-bridge/src/config/mod.rs
bridge/svix-bridge/src/config/tests.rs

I want to add a kafka variant to `SenderConfig` and `ReceiverOut`, but with current variant names, that will either cause a common suffix (which clippy will likely complain about) or odd-looking naming inconsistencies.
Remove the unnecessary `Consumer`, `Producer` variant name suffixes. Since both enums are `#[serde(untagged)]`, this does not affect deserialization. Also rename `QueueConsumerConfig` to `QueueSenderConfig`, which seems to be correct naming given it contains fields of type `Sender*Opts` and it's contained in the only variant of `SenderConfig`, whereas the previous name was rather confusing.
Part of https://github.com/svix/monorepo-private/issues/8508.

Make config type, variant names less confusing

---

server/svix-server/src/core/cache/redis.rs
server/svix-server/src/lib.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/redis/mod.rs
server/svix-server/tests/it/message_app.rs
server/svix-server/tests/it/redis_queue.rs

* Rename `RedisPool` to `RedisManager`
Now that our redis backends are not always pooled,
having `Pool` in the name is sort of confusing, so
rename the type to something a bit more generic.
* Refactor redis helper functions into methods
This is slightly less error-prone, since the caller no longer has
to specify whether to create a pooled or unpooled manager, and it's
also less repetitive.

More redis updates

---

bridge/svix-bridge-plugin-queue/src/config.rs
bridge/svix-bridge-plugin-queue/src/lib.rs
bridge/svix-bridge-plugin-queue/src/receiver_output/mod.rs
bridge/svix-bridge-plugin-queue/src/sender_input/mod.rs
bridge/svix-bridge-plugin-queue/tests/it/gcp_pubsub_consumer.rs
bridge/svix-bridge-plugin-queue/tests/it/rabbitmq_consumer.rs
bridge/svix-bridge-plugin-queue/tests/it/redis_stream_consumer.rs
bridge/svix-bridge-plugin-queue/tests/it/sqs_consumer.rs
bridge/svix-bridge/Cargo.toml
bridge/svix-bridge/src/config/mod.rs
bridge/svix-bridge/src/config/tests.rs
bridge/svix-bridge/src/webhook_receiver/config.rs
bridge/svix-bridge/src/webhook_receiver/mod.rs
bridge/svix-bridge/src/webhook_receiver/types.rs

Follow-up to #1327 / further cleanup before adding kafka because the things were still plenty confusing.

bridge: More config cleanup

---

bridge/Cargo.lock

Beta CI is failing in #1333 due to a type inference change affecting older version of the `time` crate.
Bump `Cargo.lock` by running `cargo update`. Could have only updated `time`, but I don't think it hurts to pull in other dependency updates.

bridge: Update Cargo.lock

---

deny.toml
server/Cargo.lock
server/Cargo.toml
server/svix-server/src/core/operational_webhooks.rs
server/svix-server/src/core/otel_spans.rs
server/svix-server/src/core/types/mod.rs

Fixes nightly builds that were running into inference errors in time.
Re. license: The [unicode.org FAQ](https://unicode.org/faq/unicode_license.html) describes it as a "permissive MIT type of license" and it is OSI approved. We need this because several new dependencies with this license are now being pulled in by the url crate (through idna).

server: Update Cargo.lock

---

bridge/Cargo.lock
bridge/Cargo.toml
bridge/svix-bridge-plugin-kafka/Cargo.toml
bridge/svix-bridge-plugin-kafka/LICENSE
bridge/svix-bridge-plugin-kafka/src/config.rs
bridge/svix-bridge-plugin-kafka/src/error.rs
bridge/svix-bridge-plugin-kafka/src/input.rs
bridge/svix-bridge-plugin-kafka/src/lib.rs
bridge/svix-bridge-plugin-kafka/tests/it/kafka_consumer.rs
bridge/svix-bridge-plugin-kafka/tests/it/main.rs
bridge/svix-bridge-types/src/lib.rs
bridge/svix-bridge/Cargo.toml
bridge/svix-bridge/src/config/mod.rs
bridge/testing-docker-compose.yml

… that is, support converting Kafka messages into Svix API calls.
Part of https://github.com/svix/monorepo-private/issues/8508.

bridge: Add Kafka as an input

---

rust/src/api.rs

We previously had the `BackgroundTask` object as a proxy object for the two background task routes, but no way to construct and thus use it.
Add a method to `Svix` like we have for all the other proxy objects.
Closes #1340.

rust: Add Svix::background_task

---

rust/src/api.rs

Constructing a new `Svix` client performs TLS initialization, which can be expensive (openssl needs to read certs from disk).
The new `with_token` method allows changing the api token while re-using the Hyper client, which avoids performing disk io.

rust: Add `Svix::with_token` to allow changing api token

---

bridge/Cargo.lock
bridge/svix-bridge-plugin-kafka/Cargo.toml
bridge/svix-bridge-plugin-queue/Cargo.toml

Gets rid of some cruft in `Cargo.lock`.

bridge: Upgrade wiremock dev-dependency

---

bridge/.config/nextest.toml
bridge/Cargo.lock
bridge/svix-bridge-plugin-kafka/src/input.rs
bridge/svix-bridge-plugin-kafka/tests/it/kafka_consumer.rs
bridge/svix-bridge-plugin-queue/Cargo.toml
bridge/svix-bridge-plugin-queue/src/error.rs
bridge/svix-bridge-plugin-queue/src/lib.rs
bridge/svix-bridge-plugin-queue/src/receiver_output/mod.rs
bridge/svix-bridge-plugin-queue/src/sender_input/mod.rs
bridge/svix-bridge-types/src/lib.rs
bridge/svix-bridge/src/main.rs
bridge/svix-bridge/src/webhook_receiver/tests.rs

Preparation for adding kafka `ReceiverOutput`.
Part of https://github.com/svix/monorepo-private/issues/8508.

bridge: Error refactoring

---

bridge/Cargo.lock
bridge/Cargo.toml
bridge/svix-bridge-plugin-kafka/Cargo.toml
bridge/svix-bridge-plugin-queue/Cargo.toml
bridge/svix-bridge-types/Cargo.toml
bridge/svix-bridge/Cargo.toml

With the introduction of the kafka "plugin" crate, we now have four crates. Seems like it's about time to use workspace dependencies.
Move dependency specifications for dependencies used in multiple bridge crates out into the workspace manifest and reference them in the package manifests. Also disable publishing to crates.io and reduce tokio features, because why not.

bridge: Cargo manifest cleanup

---

server/openapi.json
server/svix-server/src/core/types/mod.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs

The current response doesn't match what our libraries expect, which results in exceptions when calling this endpoint with our libraries. This adds the minimal changes necessary to make the endpoint compliant.

Fix `Recover Failed Webhooks` response

---

.github/workflows/go-lint.yml
.github/workflows/other-lint.yml

Stops using superlinter, relying solely on golangci-lint.
N.b. superlinter was tuned by default to use a much more exhaustive golangci-lint configuration. Still, we should not be invoking golangci-lint from two separate workflows with two different configurations.

Libs(Go): adjust Go linter

---

.github/workflows/other-lint.yml

Follow-on from https://github.com/svix/svix-webhooks/pull/1351 which I didn't catch because editing the linter doesn't run the lints for the different langs, so problems only surfaced when I rebased the other branch... 😢

Libs(Go): pluralize GO_MODULES in superlinter

---

server/openapi.json
server/svix-server/src/v1/endpoints/endpoint/mod.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs
server/svix-server/tests/it/e2e_endpoint.rs
server/svix-server/tests/it/utils/common_calls.rs

Our API docs support an optional `until` parameter. This adds support for it in the backend.

`Recover Failed Webhooks` use configurable `until`

---

php/src/Webhook.php

From [php.net's ctype_digit documentation](https://www.php.net/manual/en/function.ctype-digit.php):
> As of PHP 8.1.0, passing a non-string argument is deprecated. In the future, the argument will be interpreted as a string instead of an ASCII codepoint. Depending on the intended behavior, the argument should either be cast to [string](https://www.php.net/manual/en/language.types.string.php) or an explicit call to [chr()](https://www.php.net/manual/en/function.chr.php) should be made.
Deprecation is throwing a warning when passing a string into ctype_digit when checking the timestamp.
Updated the integer check to move away from `ctype_digit`.

Replace ctype_digit for PHP 8.1 deprecation of non-string arguments

---

.github/workflows/php-ci.yml
php/init.php
php/phpunit.xml
php/src/Webhook.php
php/tests/WebhookTest.php
php/tests/bootstrap.php

We recently had a contribution to the PHP lib and verifying the change was sound turned out to be a bit of a wild goose chase.
We already had some tests in place so it felt natural to get the suite running in CI.
After getting that going, there were a few warnings and failures that needed fixing up.

CI: add something to run php tests

---

javascript/src/openapi/http/isomorphic-fetch.ts

Closes #1331.
I tested that `"credentials" in Request.prototype` evals to true in both Firefox and Chrome.

js: Apply workaround for incomplete fetch support in Cloudflare Worker

---

server/Cargo.lock

Server: bump zerovec-derive

---

bridge/svix-bridge.example.receivers.yaml
bridge/svix-bridge.example.senders.yaml
bridge/svix-bridge/src/config/tests.rs

Follow-up to #1333, #1345 which added Kafka support but did not update the example YAML files, or config parsing tests.

bridge: Add kafka to example configs, config tests

---

bridge/Cargo.lock
bridge/svix-bridge-types/Cargo.toml
bridge/svix-bridge-types/src/lib.rs
bridge/svix-bridge/Cargo.toml
bridge/svix-bridge/src/config/mod.rs
bridge/svix-bridge/src/config/tests.rs
bridge/svix-bridge/src/main.rs
bridge/svix-bridge/src/webhook_receiver/mod.rs

Helps with https://github.com/svix/monorepo-private/issues/8654
Depends on client lib updates (not yet available).
I'd call this "quick and dirty" but it was actually a bit of a hefty lift to pull together. It is however fairly dirty.
The want is to be able to pull messages from `/events` and feed them into a receiver output.
The flow we'd see with `SenderInput` paired with `ReceiverOutput` is what we want, but the existing typing didn't allow for this.
Refactors were needed to:
- lift out the parts from the HTTP server that run payloads through transformations then forward to an output.
- update config to account for a new type of receiver: a "poller".
- new traits/types for the poller to differentiate it from the standard webhook receiver (to ensure we don't accidentally pass one …

Bridge: add `/events` poller

---

server/Cargo.toml

Optimize *all* host dependencies (proc-macros, build scripts), not just `quote`. Slows down clean builds (such as after `cargo clean`, a toolchain upgrade) and some rebuilds (after a host dependency upgrades), but speeds up recompilation in other more common cases where only runtime dependencies changed (if any).
Reduces re-`check` times when `svix-server/lib.rs` is touched by about 10% locally.

server: Optimize all external host dependencies for faster rebuilds

---

bridge/svix-bridge/src/webhook_receiver/mod.rs

We've got 3 places where we log errors in the poller loop and this one somehow wound up logging as `trace!` instead of `error!` like the rest.
Follow-on from https://github.com/svix/svix-webhooks/pull/1363

Bridge: log svix client errors as error, not trace

---

bridge/Cargo.lock
server/Cargo.lock

`bytes 1.6.0` is yanked.
`cargo update`. Could limit it to `--package bytes`, but why not bump everything?

Bump Cargo lockfiles

---

server/svix-server/config.default.toml
server/svix-server/src/cfg.rs
server/svix-server/src/lib.rs

Currently, the OpenTelemetry service name for svix-server is hardcoded to "svix_server". This lack of configurability limits the flexibility for users who want to customize the service name in their OpenTelemetry setup, especially in environments where multiple services are being monitored, like having several servers in "worker mode". 
This change aims to provide users with the ability to set a custom OpenTelemetry service name,  for better integration with their existing monitoring, observability infrastructure or naming convention. 
The solution implements a configurable OpenTelemetry service name for svix-server:
1. Added a new configuration option `opentelemetry_service_name` in the `ConfigurationInner` struct.
2. Updated the default configuration file (`config.default.toml`) to …

server: add configuration to for changing service name on OpenTelemetry

---

bridge/README.md
bridge/svix-bridge-plugin-kafka/src/config.rs
bridge/svix-bridge-plugin-kafka/src/input.rs
bridge/svix-bridge-plugin-kafka/src/output.rs
bridge/svix-bridge-plugin-kafka/tests/it/kafka_consumer.rs
bridge/svix-bridge-plugin-kafka/tests/it/kafka_producer.rs
bridge/svix-bridge.example.receivers.yaml
bridge/svix-bridge.example.senders.yaml
bridge/svix-bridge/src/config/tests.rs

… same as for other inputs and outputs.
Also mention that kafka is supported in the `README.md`.

bridge: Require type field for kafka input, output

---

python/svix/api.py

It already existed in the sync library, but not the async.

Python (async): add missing 'get_stats' function.

---

bridge/svix-bridge-plugin-queue/src/receiver_output/mod.rs
bridge/svix-bridge-plugin-queue/tests/it/main.rs
bridge/svix-bridge-plugin-queue/tests/it/rabbitmq_receiver.rs

Previously there were two defects related to RabbitMQ connection handling as a receiver output:
1. When unable to connect to rabbitmq on startup, bridge would exit immediately.
2. When forwarding to rabbitmq resulted in an error, the connection could be left in a bad state and not recover leaving all subsequent deliveries to the node to fail until bridge was restarted.
To address both of these issues, `QueueForwarder` now initializes clients lazily, on demand, and will tear down the client when errors are encountered.
When the client is discarded, the output will re-initialize another client using the same connection parameters at the time of the next delivery to that output.
For webhook receiver and poller inputs, the HTTP client POSTing the input will see a 500 response in the case the …

Bridge: rebuild rabbitmq producer on error

---

csharp/Svix/Abstractions/IAuthentication.cs

This closes https://github.com/svix/svix-webhooks/issues/1272
Basically what the ticket asks for. This extends the `IAuthentication` interface with the requested `AppPortalAccess` methods.

c# lib: add GetAppPortalAccess* methods to IAuthentication interface

---

go/message.go

Just another query param missing from the public API.
Helps with https://github.com/svix/svix-webhooks/issues/1381

Libs(Go): expose `with_content` for `Message.List`

---

go/integration.go

Another missing query param now exposed in the public API.
Helps with #1381

Libs(Go): expose `order` in `Integtation.List`

---

go/eventtype.go

Another param missing from the public API.
Helps with #1381

Libs(Go): expose `order` for `EventType.List`

---

go/endpoint.go

Fixes https://github.com/svix/svix-webhooks/issues/1383
The response bodies for replay and recover missing were being ignored instead of returned.
No longer! Now the bodies are propagated up, back to the caller.
> [!NOTE]
> This is techncially a breaking API change for the Go client.

Libs(Go): return response body for recover/replay

---

go/messageattempt.go

Helps with https://github.com/svix/svix-webhooks/issues/1381
Another case of a query param we have in the private API, not exposed in the public API.

Libs(Go): expose `tag` for several `MessageAttempt` list endpoints

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/cfg.rs
server/svix-server/src/core/webhook_http_client.rs
server/svix-server/src/worker.rs
server/svix-server/tests/it/e2e_proxy.rs
server/svix-server/tests/it/integ_webhook_http_client.rs
server/svix-server/tests/it/main.rs

Closes https://github.com/svix/monorepo-private/issues/8815.
New ignored test succeeded with a locally-running `microsocks` outside of Docker.

Add support for SOCKS5 proxies

---

javascript/package.json

We export source maps with the `svix` javascript package, but not the corresponding source files. 
Something like `{"version":3,"file":"index.js","sourceRoot":"","sources":["../src/index.ts"],"names":[].....` in `index.js.map` throws an error since `../src/index.ts` can't be found. This causes several warnings in certain bundlers.
Add the source files to the files published to npm. 
Closes #1299

Libs/JS: Publish src to npm to make it available for source maps

---

server/run-tests.sh
server/svix-server/tests/it/e2e_attempt.rs

We were only testing that newer attempts weren't returned, not that older attempts weren't. The original bug was actually with the latter.
Follow-up to https://github.com/svix/svix-webhooks/pull/1399.

server: Improve test_combined_before_after_filtering

---

bridge/README.md

Bridge has been around for over two years, I think it's safe to no longer call it Beta.

Bridge: remove Beta tag.

---

server/svix-server/tests/it/e2e_application.rs
server/svix-server/tests/it/e2e_attempt.rs
server/svix-server/tests/it/e2e_auth.rs
server/svix-server/tests/it/e2e_endpoint.rs
server/svix-server/tests/it/e2e_event_type.rs
server/svix-server/tests/it/e2e_health.rs
server/svix-server/tests/it/e2e_message.rs
server/svix-server/tests/it/e2e_operational_webhooks.rs
server/svix-server/tests/it/message_app.rs
server/svix-server/tests/it/utils/common_calls.rs
server/svix-server/tests/it/utils/mod.rs

Resolves #1373 
This PR refactors the server test suite by replacing the custom `IgnoredResponse` type with serde's built-in `IgnoredAny` type. The `IgnoredAny` type serves the same purpose but does so more efficiently.

Replace custom `IgnoredResponse` with serde's `IgnoredAny`

---

regen_openapi.sh

Looks like there might be an issue in the Go client generator. There is some older discussion around the template incorrectly inserting imports for `time` in some cases, and this might just be another such case.
For the near term, let's automate removal of the imports. Should the import become necessary later, CI should report a failure at lint time for the missing import.

Libs(Go): prune out unused import for "time" in codegen output

---

csharp/Svix/Endpoint.cs

Close https://github.com/svix/svix-webhooks/issues/1407
Swap the order of the parameters.

Fix appId,endpointId order in C Sharp RotateSecretWithHttpInfoAsync call

---

server/svix-server/src/cfg.rs

Looks like figment's env parser doesn't really support nested structures.
Use `#[serde(flatten)]`, like for other bits of the config.

Fix parsing proxy config from environment

---

bridge/svix-bridge-types/src/lib.rs
server/svix-server/src/core/idempotency.rs
server/svix-server/src/error.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/src/v1/utils/patch.rs
server/svix-server_derive/src/lib.rs

Clippy is unhappy about some of our doc comments, and I agree with it. They're supposed to have a succinct first paragraph that can be rendered as a summary (also helpful in our OpenAPI docs). This PR makes it so, at least for all the comments that were surpassing the threshold that makes clippy warn about an overly long first paragraph.

Rewrap doc comments to always have a succinct first paragraph

---

server/openapi.json
server/svix-server/src/v1/endpoints/attempt.rs

… to unbreak client libraries that expect this field now.
Since we added this field to Svix'es cloud offering and updated the client libraries accordingly, they are now expecting it to be present, meaning they don't work correctly against the OSS version.
This bug was reported in #1415.
Make the OSS server emit this field with a value of `0`. A future version might start recording and properly reporting response durations.

Add responseDurationMs to MessageAttempt

---

.github/workflows/server-release.yml

The server release workflow has been failing to build windows and macOS releases for a long time. Looks like nobody is using them, as we haven't received any complaints.
Remove the release jobs for Windows and macOS from the workflow.
Internal ref: https://github.com/svix/monorepo-private/issues/8977

ci: Remove Windows and macOS server releases

---

server/svix-server/src/cfg.rs
server/svix-server/src/core/webhook_http_client.rs

Some preparations for adding HTTP proxy support.
Part of https://github.com/svix/monorepo-private/issues/8990.

server: Refactor proxy implementation

---

server/run-tests.sh
server/svix-server/tests/it/e2e_application.rs
server/svix-server/tests/it/e2e_attempt.rs
server/svix-server/tests/it/e2e_auth.rs
server/svix-server/tests/it/e2e_endpoint.rs
server/svix-server/tests/it/e2e_health.rs
server/svix-server/tests/it/e2e_message.rs
server/svix-server/tests/it/e2e_operational_webhooks.rs
server/svix-server/tests/it/message_app.rs
server/svix-server/tests/it/utils/common_calls.rs
server/svix-server/tests/it/utils/mod.rs

Our test script was broken :facepalm: 
A lot of tests were failing because they were asserting wrong things about server responses.
We didn't see it in CI because the script was missing `set -e`.
Make it actually fail if a command other than the last one fails. Repair broken tests.

Repair broken tests

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/cfg.rs
server/svix-server/src/core/webhook_http_client.rs
server/svix-server/src/worker.rs
server/svix-server/tests/it/e2e_proxy.rs

Adds support for HTTP(S) proxies, in addition to SOCKS5 proxies that we've been supporting for a little while.
Closes https://github.com/svix/monorepo-private/issues/8990.

Add support for http proxies

---

server/docker-compose.yml

This docker compose is not really an example per se, but it's being used as a reference one. So it's better to have it include the last missing piece for starting the server, which is setting the JWT secret.

Server: include JWT secret in the docker compose example.

---

.github/workflows/bridge-release.yml

We did this for server, let's do same here, as they are failing.

Remove windows and macos bridge release

---

server/svix-server/tests/it/e2e_attempt.rs

We have a flaky message-attempt test. Nobody likes flaky tests.
Make sure the retrying in the test actually happens if first attempt at getting message attempts fails.

server: Fix flaky attempt test

---

python/svix/api.py
python/templates/model.py.jinja

Based on https://github.com/svix/svix-webhooks/pull/1442
We now special-case `CreateStreamOut` to avoid generating invalid code. This allows us to keep the current code generation for `MessageInPayload`/`MessageOutPayload` (which are both just `dict`s, not actual classes)

Revert Python code generation changes and fix CreateStreamOut generation

---

server/svix-server/src/cfg.rs
server/svix-server/tests/config.rs

… since they can influence other tests.

Move environment parsing tests out of the unit test suite

---

go/endpoint_test.go
go/internal/openapi/model_endpoint_in.go

This is a stop-gap "quick fix" to allow callers to successfully create endpoints without specifying channels and filter types.
Today, they get a 422 response when passing an empty array (as required by our lib).
With this diff, the fields are set to pointers so they can be properly nulled out, as they were prior to #545.
Research required to see what we need to do so the codegen does the right thing given the spec (which produces good output for the other libs).

Libs(Go): edit `EndpointIn` to allow null for channels, filter types

---

.github/workflows/go-ci.yml

We've got a handful of unit test that could catch problems when the Go sources are changing, so let's run them as a part of CI.
This doesn't re-run the OpenAPI codegen (but it could later). It would be nice to know if the checked in sources were not aligned with whatever the generator produces, for example if a recent spec bump PR neglected to check them in.

Libs(Go): get go tests running in CI

---

go/internal/openapi/model_endpoint_patch.go
go/internal/openapi/model_endpoint_update.go

Pairs with <https://github.com/svix/svix-webhooks/pull/1448>
This is effectively the same change we made for `EndpointIn`, but for the request bodies for `PUT` and `PATCH` requests.
This is still a workaround with a more comprehensive fix expected via <https://github.com/svix/svix-webhooks/pull/1450> (once some additional testing has been done).

Libs(Go): hand-edit `EndpointUpdate` and `EndpointPatch` for nulls

---

server/Cargo.toml
server/svix-server/Cargo.toml
server/svix-server_derive/Cargo.toml

- Use workspace inheritance for edition and license
- Remove fields that serve no purpose for packages that are never published

server: Normalize package metadata

---

go/internal/openapi/model_app_usage_stats_in.go
go/internal/openapi/model_attempt_statistics_data.go
go/internal/openapi/model_auth_token_out.go
go/internal/openapi/model_endpoint_message_out.go
go/internal/openapi/model_endpoint_oauth_config_in.go
go/internal/openapi/model_endpoint_out.go
go/internal/openapi/model_endpoint_transformation_simulate_in.go
go/internal/openapi/model_environment_in.go
go/internal/openapi/model_event_type_from_open_api.go
go/internal/openapi/model_event_type_import_open_api_in.go
go/internal/openapi/model_event_type_import_open_api_out_data.go
go/internal/openapi/model_event_type_in.go
go/internal/openapi/model_event_type_out.go
go/internal/openapi/model_event_type_patch.go
go/internal/openapi/model_event_type_update.go
go/internal/openapi/model_message_attempt_headers_out.go
go/internal/openapi/model_message_broadcast_in.go
go/internal/openapi/model_message_endpoint_out.go
go/internal/openapi/model_message_in.go
go/internal/openapi/model_message_out.go
go/internal/openapi/model_template_in.go
go/internal/openapi/model_template_out.go
go/internal/openapi/model_template_patch.go
go/internal/openapi/model_template_update.go
go/internal/openapi/model_transformation_simulate_in.go
go/svix_test.go
go/templates/model_simple.mustache

In #1448 the `EndpointIn` model was hand-edited such that `channels` and `filterTypes` were nullable, and thus correctly omitted from request bodies sent to the server.
This series of commits attempts to remove the need to keep reapplying this patch with each spec bump by updating the codegen template used to produce the model code.
This change is comprised of 3 commits:
1. the addition of a template override for `model_simple` ([src](https://github.com/OpenAPITools/openapi-generator/blob/v5.2.0/modules/openapi-generator/src/main/resources/go/model_simple.mustache)) as-is, taken from openapi at the v5.2.0 tag (matching the version of the generator we're using currently).
2. some modifications to said template, i.e. _our patch_.
3. updated go sources from running the generator.
When …

Libs(Go): template overrides for nullable non-required containers

---

server/svix-server/src/v1/endpoints/message.rs
server/svix-server/tests/it/e2e_message.rs

Ensure that we don't return a 5xx when user attempts to insert a duplicate message (i.e., due to msg-uid conflict)
Fixes https://github.com/svix/svix-webhooks/issues/1454

Return 409 on duplicate message insert

---

server/openapi.json
server/svix-server/src/v1/endpoints/event_type.rs

This already exists in the hosted svix.com product
Fixes #1457

Server: Add 'expunge' parameter to event-type deletion route

---

server/svix-server/src/queue/redis.rs
server/svix-server/src/redis/mod.rs

Light refactoring of some of the redis code. I really dislike how repetitive 
some of this code is. This doesn't fix the core issue but reduces some
duplication.

Redis refactor

---

yarn.lock

Addresses https://github.com/svix/svix-webhooks/security/dependabot/128 by bumping `@openapitools/openapi-generator-cli` to transitively bump `path-to-regexp`.

bump `path-to-regexp` via `openapi-generator-cli`

---

server/Cargo.lock
server/run-tests.sh
server/svix-server/Cargo.toml
server/svix-server/src/cfg.rs
server/svix-server/src/lib.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/redis/mod.rs
server/svix-server/src/redis/sentinel.rs
server/svix-server/tests/it/e2e_message.rs
server/svix-server/tests/it/message_app.rs
server/testing-docker-compose.yml

This adds support for using Redis Sentinel for queuing and caching.
Sentinel potentially requires a lot of additional configuration params,
so support for that that has been added here, although the `redis_dsn`
field has been reused and should point to a sentinel server if using the 
`redissentinel` queue/cache types.

Add redis sentinel support

---

server/svix-server/src/core/cache/redis.rs
server/svix-server/src/redis/mod.rs

This removes a lot of the needless indirection/structs that were obscuring what should be a pretty simple thing -- i.e., the different variants for `ConnectionManager`s and `RedisConnection`s.
Note also that by moving some of the `query_async` calls to the `Cmd` rather than the connection, we can completely remove the `*Connection` types and associated macros.
There's definitely some more cleanup that can be done here, but I think this is good for one PR.

More redis refactors

---

bridge/Cargo.lock
bridge/svix-bridge/Cargo.toml
bridge/svix-bridge/src/runtime/mod.rs

Use a version of `deno_core` we know not to leak memory.

bridge: Upgrade deno crates

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/lib.rs
server/svix-server/src/metrics/mod.rs
server/svix-server/src/metrics/redis.rs
server/svix-server/src/mod.rs
server/svix-server/src/queue/redis.rs

This adds support exporting OTEL metrics and adds some basic monitoring of the various redis queues.

Add redis OTEL metrics

---

README.md
server/svix-server/Cargo.toml
server/svix-server/config.default.toml
server/svix-server/src/cfg.rs
server/svix-server/src/metrics/redis.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/rabbitmq.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/v1/endpoints/admin.rs
server/svix-server/src/v1/endpoints/attempt.rs
server/svix-server/src/v1/endpoints/endpoint/recovery.rs
server/svix-server/src/v1/endpoints/health.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/v1/endpoints/mod.rs
server/svix-server/src/v1/mod.rs
server/svix-server/src/worker.rs
server/svix-server/tests/it/redis_queue.rs
server/svix-server/tests/it/utils/mod.rs

Add support for moving failed messages to deadletter queue in
Redis. The queue can be re-driven via an undocumented endpoint,
`/api/v1/admin/redrive-dlq`.

Redis dlq support

---

bridge/Dockerfile
bridge/svix-bridge-plugin-kafka/Cargo.toml

This PR updates Dockerfile  with docker images versions 
and adds the necessary support for the svix kafka plugin
The Docker build for the bridge plugin was failing due
to the missing kafka dev library and needed rust version
update for some rust crates.
This PR updates the rust image version from `rust:1.72-slim-bullseye`
to `rust:1.81-slim-bookworm` as was promted during the test builds for
the underlying crate versions. It installs kafka dev library for supporting
the rdkafka crate. It also adds the associated changes for including the
`svix-bridge-plugin-kafka` and fixes the `cmake` missing error by adding
the `cmake` utility for building the required libraries. Similarly the
`debian:bullseye-slim` is now `debian:bookworm-slim` for the ultimate
prod image

Update the base images to bookworm, support kafka plugin

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/core/message_app.rs
server/svix-server/src/core/types/mod.rs

`sqlx 0.8.1` fixed a security issue. The issue very likely doesn't impact us, but it's better to be on a fixed version.
Upgrade!

Upgrade sea-orm, sqlx

---

server/svix-server/src/core/message_app.rs

I noticed in https://github.com/svix/svix-webhooks/pull/1487 that this method was formatted quite badly. I removed the comments, let rustfmt do its thing, then put the comments back in again (and made some small manual adjustments).

Clean up formatting of CreateMessageApp::filtered_endpoints

---

.github/workflows/javascript-lint.yml
.github/workflows/javascript-release.yml

The latest version of `openapi-generator-cli` requires a newer version of Node. We can just use LTS/latest, no need to pin to an older version. 
https://github.com/svix/svix-webhooks/actions/runs/11404529698/job/31733893512

Upgrade Node version in Javascript release action

---

go/svix.go
go/svix_test.go

Fixes <https://github.com/svix/svix-webhooks/issues/1198>
While this isn't quite the type of change that was requested in #1198, I'm hopeful it'll reduce a bit of the friction.
A new constructor is now available as `svix.StaticNullableString()` which gives an `openapi.NullableString`.
Note that the return type (not a pointer) is inconsistent with the rest of the functions that act as primative constructors, and in fact goes against the convention of constructors returning pointers to the value they initialize.
The issue was raised, however, that all the places in the lib where a `NullableString` is needed, we'd have to dereference it anyway. 
Since this alt constructor is all about convenience, we may as well break convention. _In for a penny, in for a pound..._
The net effect is instead …

Libs(Go): add convenience constructor for static nullable strings

---

deny.toml
server/Cargo.lock

0.27.4 was yanked due to a bug: https://github.com/redis-rs/redis-rs/releases/tag/redis-0.27.4
0.27.5 has no other changes other than the bug fix. 
Also removes security advisory ignores that are no longer used.

Upgrade redis to get rid of yanked version

---

javascript/package.json
javascript/yarn.lock

Fixes https://github.com/svix/svix-webhooks/issues/1505
Big thanks to @ZONGMENG-kaito for the report.
During the work on https://github.com/svix/svix-webhooks/pull/1480 various dependencies were updated to match what is being produced by the upstream code generator. Unfortunately, the version spec change for `@stablelib/base64` up to 2.x means we inherit their ESM requirement.
The local tests (i.e. `SVIX_SERVER_URL=... SVIX_TOKEN=... yarn test`) continue to pass with the downgrade, so it seems like pinning to 1.x will free consumers of _our lib_ of this new requirement for now.
Hopefully in the future we'll find a way to track 2.x without disruption.

Libs(JS): downgrade `@stablelib/base64` avoiding `ERR_REQUIRE_ESM`

---

bridge/svix-bridge/src/config/mod.rs

Adds a few more `cfg` attributes to hide kafka-related things at compile time when needed.

Bridge(kafka): guard kafka-related symbols with cfg attrs

---

bridge/svix-bridge/src/main.rs

Long-living tracing spans can leak memory over time if logs happen to be produced inside them.
Removing the span should help avoid a leak later.

Bridge: remove long-living span around metrics collection

---

bridge/Cargo.lock
bridge/svix-bridge/Cargo.toml
bridge/svix-bridge/src/runtime/mod.rs

Seeing segfaults shortly after launching the process with the deno version we were using. It's unclear why.
Effectively backs out https://github.com/svix/svix-webhooks/pull/1469

Bridge: downgrade deno

---

server/svix-server/src/core/idempotency.rs
server/svix-server/src/lib.rs
server/svix-server/src/main.rs
server/svix-server/src/metrics/redis.rs
server/svix-server/src/worker.rs
server/svix-server/tests/it/e2e_operational_webhooks.rs
server/svix-server/tests/it/integ_webhook_http_client.rs
server/svix-server/tests/it/utils/mod.rs

Upstreaming some internal improvements.
Part of https://github.com/svix/monorepo-private/issues/7844.

Some hyper 1.0 / axum 0.7 preparations

---

server/svix-server/src/lib.rs

This looks like a probable cause of memory-leaks, since the span will never complete while the application is running.

Remove toplevel span

---

server/svix-server/src/worker.rs

Ensure that we don't try to process a message for which endpoints 
no longer exist. Fixes #1511.

Server: exit early if endpoints don't exist

---

bridge/Dockerfile
bridge/scripts/check-deps.sh

The v1.39 tag on docker hub currently fails with:
```
docker run --rm -it -e SVIX_BRIDGE_CFG='{}' docker.io/svix/svix-bridge:v1.39.0
svix-bridge: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```
This diff adds script to look at the output from `ldd` and see if there are libs that aren't found.
The version of the Dockerfile in main currently seems to pass this check. Removing the cacert install gets us back to a failing state, so we can see the script working:
```
Step 17/22 : USER appuser
---> Using cache
---> 80f72cf25adf
Step 18/22 : COPY --from=build /app/target/release/svix-bridge /usr/local/bin/svix-bridge
---> Using cache
---> 1bcafc142c09
Step 19/22 : COPY scripts/check-deps.sh /usr/local/bin/check-deps.sh
---> …
```

Bridge: add check for missing dynamic libs

---

.github/workflows/bridge-ci.yml
bridge/run-idle-test.sh

Mentioned in the script comments, we've seen segfaults in bridge coming from deno, and only after the interpreter has had some time to achieve steady-state.
This diff adds a script to run a check where we launch the process with an empty config (no senders or receivers registered), and send it to the background.
Bridge should be able to stay up indefinitely like this. If the process ends before we check on it (after sleeping a spell), that's probably a bug.
I reverted the last deno downgrade to try this script out in the failing state. It seemed to catch the issue well.
```
$ ./run-idle-test.sh
Compiling svix-bridge v1.39.0 (/home/onelson/Projects/svix-webhooks/bridge/svix-bridge)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.29s
Monitoring PID=189293
fail: process …
```

Bridge: add a test to check process liveness

---

javascript/src/index.ts

Since these are commonly gotten from a previous API response, which actually returns nulls for them, rather than leaving out the fields (the response types used to have wrong typings w.r.t. that).
Part of https://github.com/svix/monorepo-private/issues/9393.

js: Allow iterator and date list params to be null

---

openapi.json

Avoids a problem with the codegen output for JS specifically, and possibly others, where query params for `status` could be left unset by the client.
This is a stop-gap. Changes are WIP to get the spec generation to maintain this change moving forward more exhaustively. In the meantime, this should set the codegen right for `MessageStatus`.

Libs(all): set `explode: false` for `MessageStatus`

---

regen_openapi.sh
rust/.gitignore
rust/src/api.rs
rust/tests/kitchen_sink.rs

The OpenAPI code generator upgrade caused a lot of Rust fields to be double options, but for most of them it just gets in the way. Patch the openapi spec before generating Rust code to revert this.
Closes https://github.com/svix/monorepo-private/issues/9393.
Closes https://github.com/svix/monorepo-private/issues/9398.

rust: Update openapi codegen script to revert field type changes

---

.github/workflows/bridge-ci.yml
.github/workflows/bridge-security.yml
.github/workflows/rust-security.yml
.github/workflows/server-ci.yml
.github/workflows/server-security.yml
deny.toml

Current Rust nightly toolchains have updated the default lockfile version (written whenever any changes to the lockfile are made), to a version that the older `cargo-deny` we were using doesn't understand. This requires manual fiddling and is only going to get worse as time goes on.
Fixes the CI errors in #1528.

Upgrade cargo-deny

---

server/svix-server/src/error.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/tests/it/e2e_message.rs

On large payloads, the server now returns 500
Return 413 instead of 500. Also added a test that checks that.

Return 413 on large payloads

---

kotlin/lib/src/main/kotlin/Message.kt

kotlin: Add convenient construction of rawPayload messages

---

regen_openapi.sh

It was removing it even when the property was marked required, which was not intended.

rust: Fix jq script that removes nullable attributes

---

kotlin/lib/src/main/kotlin/Message.kt
rust/src/lib.rs
rust/src/model_ext.rs

… and add some extra detail to the docs of the kotlin equivalent.

rust: Add MessageIn::{new_raw_payload, with_content_type}

---

javascript/src/index.ts

js: Add convenient construction of rawPayload messages

---

csharp/Svix.Tests/IgnoreIfClientVarsUnset.cs
csharp/Svix.Tests/SvixClientTests.cs

This reverts commit ec5acbd56a56b12f47c0b9931df567c56ade351a.
Now that the target runtime has been updated, these tests should be compatible with our CI situation.

Reapply "Libs(CSharp): add kitchen sink test"

---

java/lib/src/main/java/com/svix/Message.java

java: Add convenient construction of rawPayload messages

---

go/message.go

go: Add convenient construction of rawPayload messages

---

python/svix/api.py

python: Add convenient construction of rawPayload messages

---

bridge/svix-bridge-plugin-kafka/src/error.rs

It's difficult to troubleshoot when you can't see the original error.

Bridge: Surface kafka error

---

ruby/lib/svix/message_api.rb
ruby/spec/message_api_spec.rb

ruby: Add convenient construction of rawPayload messages

---

javascript/package.json
javascript/tsconfig.cjs.json
javascript/tsconfig.esm.json

Closes https://github.com/svix/svix-webhooks/issues/1483
Compile the svix JavaScript package in `ESM` and `CommonJS` simultaneously. This should solve the issues with tree-shaking (since it can only be done when the package is compiled with ESM). Also keeps the CommonJS version for backwards compatibility.
Tested this locally and all the usual imports (`import { EventTypeOut } from "svix"`) work as expected, with no changes whatsoever.

[Lib/JS] Compile svix package for ESM and CommonJS

---

go/svix.go

Without this, it is impossible to create a `NullableInt64` for things like the payload retention period.
Add a "constructor" function like we have for `NullableInt32`, `NullableBool`, `NullableString`.

go: Add svix.NullableInt64

---

csharp/Svix/Message.cs

c#: Add convenient construction of rawPayload messages

---

javascript/package.json

I accidentally changed the version in https://github.com/svix/svix-webhooks/pull/1549

Libs/JS: Fix package version

---

csharp/Svix/Message.cs
java/lib/src/main/java/com/svix/Message.java
javascript/src/index.ts
kotlin/lib/src/main/kotlin/Message.kt
python/svix/api.py
ruby/lib/svix/message_api.rb
rust/src/model_ext.rs

In previous PRs for https://github.com/svix/monorepo-private/issues/9470, some review comments were made for better docs. I also just failed and used different ways of saying the same thing in different places. This all made for pointlessly diverging docs between the different languages.
Use the same basic formulation everywhere: "pre-serialized payload", same description of the "as-is" nature of raw payloads, same description of the content-type parameter. A number of language-specific docs remain to cover differences in how these functions work (e.g. for optional content-type, Java has two overloads of one function, Rust has a builder-style method, most other languages use an optional parameter).

Unify rawPayload message docs

---

javascript/package.json

Revert the ESM package update. I'm still investigating some issues with importing the ESM version, but in the meanwhile, let's revert to the previous working state.

[Libs/JS] Revert ESM package update

---

ChangeLog.md
rust/src/api.rs
rust/tests/kitchen_sink.rs

These parameters are useless, and get ignored.
Remove.

rust: Remove unused optional `PostOptions` parameters from non-POST methods

---

rust/src/api/application.rs
rust/src/api/endpoint.rs
rust/src/api/event_type.rs
rust/src/api/integration.rs
rust/src/api/message.rs

Adjust some field lists and impl block items to match the order in the spec.
This was done by importing the output of our new codegen tool, then reverting changes we don't (yet) want to import.
Version used: https://github.com/svix/openapi-codegen/commit/fd7dbc40af6badfe0dac8b6ccc1b889c2dd62d1f
Based on #1559.

Add query parameter docs and reorder some things

---

javascript/src/api/application.ts
javascript/src/api/background_task.ts
javascript/src/api/endpoint.ts
javascript/src/api/event_type.ts
javascript/src/api/integration.ts
javascript/src/api/message.ts
javascript/src/api/message_attempt.ts
javascript/src/api/op_webhook_endpoint.ts
javascript/src/util.ts

And get rid of internal ListOptions type.
The ones without docs are not getting generated yet for various reasons, but I think this is a good enough start for replacing the high-level JS API with generated code.

js: Add generated query parameter types

---

deny.toml
server/Cargo.lock
server/svix-server/Cargo.toml

The version of validator we were using depends on an old `idna`, and has a bug where it can panic in validation.
Because upgrading to v0.17+ is pretty involved, switch to our fork for now which fixes the panic and upgrades dependencies but is otherwise the same as v0.16.1.

server: Use forked validator crate

---

javascript/.prettierrc.cjs
javascript/.prettierrc.toml
javascript/package.json
javascript/src/api/application.ts
javascript/src/api/authentication.ts
javascript/src/api/background_task.ts
javascript/src/api/endpoint.ts
javascript/src/api/event_type.ts
javascript/src/api/integration.ts
javascript/src/api/message.ts
javascript/src/api/message_attempt.ts
javascript/src/api/op_webhook_endpoint.ts
javascript/src/api/statistics.ts
javascript/src/index.ts
javascript/src/util.ts
javascript/src/webhook.ts

We're going to commit more generated code soon that needs auto-formatting to look good. Seems like we didn't have auto-formatting set up correctly so we had some overly long lines and a mix of two-space and four-space indentation. This PR fixes that, and updates CI to error on unformatted files.

js: Enforce uniform formatting

---

go/application.go
go/endpoint.go
go/eventtype.go
go/integration.go
go/message.go
go/operational_webhook_endpoint.go

Following what I just did for JS (#1571).
Part of https://github.com/svix/monorepo-private/issues/9576.

go: Add generated query parameter structs

---

ChangeLog.md

js: Add recent query parameter type change to changelog

---

javascript/src/api/application.ts
javascript/src/api/authentication.ts
javascript/src/api/endpoint.ts
javascript/src/api/event_type.ts
javascript/src/api/integration.ts
javascript/src/api/message.ts
javascript/src/api/message_attempt.ts
javascript/src/api/statistics.ts

Using our new codegen.
Part of https://github.com/svix/monorepo-private/issues/9576.

js: Replace api/ files by generated files with minor manual changes

---

ChangeLog.md
rust/src/api/authentication.rs
rust/src/api/endpoint.rs
rust/src/api/event_type.rs
rust/src/api/message.rs
rust/src/api/message_attempt.rs
rust/src/api/mod.rs

Reverting parts of the changes to avoid unnecessary breakage.

rust: Regenerate high-level API

---

ChangeLog.md
javascript/src/api/application.ts
javascript/src/api/authentication.ts
javascript/src/api/endpoint.ts
javascript/src/api/event_type.ts
javascript/src/api/integration.ts
javascript/src/api/message.ts
javascript/src/api/message_attempt.ts
javascript/src/api/statistics.ts
javascript/src/index.ts

Rust-style doc comments don't seem to work here :smile: 
Adjusted the codegen to output Java-style doc comments, which get picked up by VSCode for on-hover info, so that's a good sign.

js: Regenerate high-level API

---

rust/Cargo.toml
svix-cli/Cargo.lock
svix-cli/Cargo.toml

Using rustls simplifies some of the build/distribution concerns when packaging the CLI. Namely it allows us to produce binaries without having to ensure `openssl-sys` can build, and all that that involves.
Oddly, while `native-tls` is listed as an optional-but-default dep in the Rust SDK, specifying the dep on the SDK from the CLI with `default-features = false` didn't seem to remove `openssl-sys` from the dependency tree.
As a work around, I've updated the default features in the Rust SDK to target `rustls`, which does allow the sys crate to drop away.
This seems fine to me. Folks who still want to use `native-tls` can elect to do so, just not by default.
Some CLI features have been tuned up to support this effort, namely targeting specific individual features for `tokio`, and so on.

Libs(Rust, CLI): switch from `native-tls` to `rustls`

---

svix-cli/src/config.rs

When the CLI creates a config file for the user, we use `600` unix permissions to ensure only the user can read/write the file.
Setting the file mode like this is only possible like this on unix-like systems so this breaks the build for Windows.
This diff splits the opening of the file into platform-specific functions, one for `windows` which doesn't set the file mode. The `unix` flavored function does what we had in the first place.
In <https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createfile2> there's mention of ACL being inherited from the parent directory. My understanding is `%APPDATA%` should only be accessible by the named user, so I'm hoping the defaults are correct for our use case.

CLI: skip setting file mode for Windows

---

svix-cli/src/relay/mod.rs

For whatever reason the error detail wasn't surfaced while I was debugging some TLS things.
This `.inspect_err()` gave me what I needed. Let's keep it in there.

CLI: show websocket connection failure details

---

svix-cli/Cargo.toml

One of the `dist` jobs complains that this is unset.

CLI: add `authors` to manifest

---

.github/workflows/python-release.yml

- direct invocation of setup.py is [deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/)
- publish wheels

publish wheels

---

server/Dockerfile

I don't think exposing 8080 ever did anything as the server is listening on 8071. It looks like a customer has been facing issues with their docker setup not letting them map the port because it doesn't match the exposed from the dockerfile. I'm not sure how it works for everyone else but not here though anyhow it should be fixed.
Ref: https://x.com/0xblacklight/status/1872430388158533871

Docker: fix exposed port to be 8071.

---

svix-cli/Cargo.toml

This is to help clarify what the binary actually is among the rest of the svix tooling in the repo.
Looking forward, this will also help to keep the naming scheme consistent between the binary, the package name, and the updater while handling distribution via `dist` (pending PR:
https://github.com/svix/svix-webhooks/pull/1593)

CLI: change binary name to `svix-cli`

---

svix-cli/README.md
svix-cli/src/cmds/login.rs
svix-cli/src/main.rs
svix-cli/src/relay/mod.rs
tools/bump_version.js

The text in this readme is based largely on the one from the old Go CLI.
Some sections have been removed since support for the thing being
mentioned was not carried forward (e.g. `--data-*` flags, import/export, and
also piping json bodies in which apparently our new clap-based parser doesn't
do).
Installer instructions are limited to the initial set offered via
https://github.com/svix/svix-webhooks/pull/1593
Since the version number appears in the script-based installer URLs,
`tools/bump_version.js` has been updated to also target this readme.
More sections will be added to describe `homebrew`/`cargo` installation
once available.

CLI: add readme with install instructions

---

svix-cli/README.md

These were copied over as-is from the old svix-cli repo and don't make sense any longer.

CLI: remove badges from readme

---

svix-cli/Cargo.toml
svix-cli/README.md
svix-cli/wix/main.wxs

We flip-flopped on this. For now, let's call the binary `svix`.
`dist plan` shows that the various build artifacts will still be named `svix-cli` which is what we want.
```
$ dist plan
announcing v1.45.0
svix-cli 1.45.0
source.tar.gz
[checksum] source.tar.gz.sha256
svix-cli-installer.sh
svix-cli-installer.ps1
sha256.sum
svix-cli-aarch64-apple-darwin-update
svix-cli-aarch64-apple-darwin.tar.xz
[bin] svix
[misc] LICENSE, README.md
[checksum] svix-cli-aarch64-apple-darwin.tar.xz.sha256
svix-cli-aarch64-unknown-linux-gnu-update
svix-cli-aarch64-unknown-linux-gnu.tar.xz
[bin] svix
[misc] LICENSE, README.md
[checksum] svix-cli-aarch64-unknown-linux-gnu.tar.xz.sha256
svix-cli-x86_64-apple-darwin-update
svix-cli-x86_64-apple-darwin.tar.xz
[bin] svix
[misc] LICENSE, README.md
[checksum] …
```

CLI: rename the binary `svix-cli` -> `svix`

---

ChangeLog.md
java/lib/src/main/java/com/svix/Application.java
java/lib/src/main/java/com/svix/Authentication.java
java/lib/src/main/java/com/svix/BackgroundTask.java
java/lib/src/main/java/com/svix/Endpoint.java
java/lib/src/main/java/com/svix/EventType.java
java/lib/src/main/java/com/svix/Integration.java
java/lib/src/main/java/com/svix/Message.java
java/lib/src/main/java/com/svix/MessageAttempt.java
java/lib/src/main/java/com/svix/OperationalWebhookEndpoint.java
java/lib/src/main/java/com/svix/Statistics.java
java/lib/src/main/java/com/svix/Svix.java

java: Stop sharing one ApiClient between all Svix instances

---

.github/workflows/rust-release.yml

Removes some steps in the Rust release workflow which were needed when we were generating sources.
Today, all the sources needed for release should be present and tracked by git before the workflow runs.

Libs(Rust): skip regeneration and "cargo hack" for release

---

go.mod

Some tags got pushed (from a fork) into the main OSS repo, causing problems for the Go package tooling once the tags had been removed.
These retractions should tell the packager that these versions should not be depended on.

Libs(Go): add retractions for accidentally published test versions

---

.github/workflows/csharp-release.yml
.github/workflows/java-release.yml
.github/workflows/javascript-release.yml
.github/workflows/kotlin-release.yml
.github/workflows/php-release.yml
.github/workflows/python-release.yml
.github/workflows/ruby-release.yml
.github/workflows/rust-release.yml
.github/workflows/update-postman.yml

We had an issue where pushing tags named for version numbers caused unwanted side-effects.
Attempting to avoid this:
- no longer manually push tags.
- let the GitHub release automatically tag when it publishes.
- drive the other release workflows based on release: published events.
By moving the trigger off of tag push, this additionally opens the door for situations where we need to push a tag then create a release for it since the lib workflows won't be triggered until the release is finalized.

Libs: change release workflows to be triggered by release published

---

.github/workflows/bridge-release.yml
.github/workflows/csharp-release.yml
.github/workflows/java-release.yml
.github/workflows/javascript-release.yml
.github/workflows/kotlin-release.yml
.github/workflows/mega-releaser.yml
.github/workflows/php-release.yml
.github/workflows/python-release.yml
.github/workflows/ruby-release.yml
.github/workflows/rust-release.yml
.github/workflows/server-release.yml
.github/workflows/update-postman.yml

Changes all workflows related to Releases so they are manually triggered.
Continuing to iron out the kinks of the new `dist` based workflow used for building/releasing the CLI.
It looks as though the "release published" event we tried to trigger these on doesn't fire in some cases. Rumors suggest having a release published by an automation rather than a real person could be the difference.
For now as a workaround, let's trigger these manually. It's tedious, but we can likely add One More Workflow to kick them all off on our behalf as a 2nd step.
Additional: a new workflow called "Mega Releaser" aims to try and kick off all the rest. It might work. It might not. TBD.

CI: release libs, server, bridge with manual workflows

---

csharp/Svix.Tests/WebhookTest.cs
csharp/Svix/Webhook.cs

Provide an overload to the `Webhook.Verify` function to except an `Func<string, string>` function that acts as an function provider.
Creating an extra `WebHeaderCollection` everytime a webhook signature needs to get verified is unnecessary overhead for environments where the `WebHeaderCollection` is not part of underlying http stack; The object needs to get created just for the verification. 
Allowing to pass a header provider function to avoid creating a WebHeaderCollection in asp.net core environments
See also #1616

csharp: allow verification of webhook signature without the need of a WebHeaderCollection

---

svix-cli/src/cmds/api/application.rs
svix-cli/src/cmds/api/authentication.rs
svix-cli/src/cmds/api/endpoint.rs
svix-cli/src/cmds/api/event_type.rs
svix-cli/src/cmds/api/integration.rs
svix-cli/src/cmds/api/message.rs
svix-cli/src/cmds/api/message_attempt.rs

Continued refinement of the generator templates to help reduce friction.
Some imports have been reworked to make them more stable diff-to-diff with fully-qualified paths used as needed (i.e. when we shadow models and convert them via a `From` impl).

CLI: update codegen again

---

ChangeLog.md
kotlin/lib/src/main/kotlin/Application.kt
kotlin/lib/src/main/kotlin/Authentication.kt
kotlin/lib/src/main/kotlin/Endpoint.kt
kotlin/lib/src/main/kotlin/EventType.kt
kotlin/lib/src/main/kotlin/Integration.kt
kotlin/lib/src/main/kotlin/Message.kt
kotlin/lib/src/main/kotlin/MessageAttempt.kt
kotlin/lib/src/main/kotlin/Statistics.kt

Like in other languages, `MessageAttempt` is a very large diff so I'd like to handle it separately. There's already enough breaking changes in this one PR :smiling_face_with_tear: 
Part of https://github.com/svix/monorepo-private/issues/9576.

kotlin: Use generated source file for most of the high-level API

---

svix-cli/src/cmds/api/application.rs
svix-cli/src/cmds/api/authentication.rs
svix-cli/src/cmds/api/endpoint.rs
svix-cli/src/cmds/api/event_type.rs
svix-cli/src/json.rs

For the API calls that require a body but all the fields are technically optional, the ideal case is to allow the CLI command to be invoked without a body argument at all.
This diff wraps the `JsonOf` fields in this situation with `Option` to this effect.
The generator template changes were "basic" in so much as the `Option`-wrapping happens uniformally for cases where passing nothing isn't especially useful (e.g. `PATCH` request).
With some additional special-casing, we can probably make those required arguments, but for now they are optional.

CLI: update codegen for optional request bodies

---

ChangeLog.md
rust/src/api/authentication.rs
rust/src/api/endpoint.rs
rust/src/api/event_type.rs
rust/src/api/integration.rs
rust/src/api/message_attempt.rs
rust/src/api/mod.rs
svix-cli/src/cmds/api/application.rs
svix-cli/src/cmds/api/authentication.rs
svix-cli/src/cmds/api/endpoint.rs
svix-cli/src/cmds/api/event_type.rs
svix-cli/src/cmds/api/integration.rs
svix-cli/src/cmds/api/message_attempt.rs

Introduce some optional parameters that I had been excluding because it was a breaking change. We have now evaluated this sufficiently and have decided to introduce them, even though it is a breaking change (existing uses of these methods need an extra `None` argument).
Also, our code generation now handles deprecated methods. This leads to some things being added to message-attempt that we don't want, but otherwise reduces the amount of manual changes we need to do to clean up the generated code.

rust: Remove some manual changes after codegen

---

csharp/Svix/MessageAttempt.cs
go/message_attempt.go
java/lib/src/main/java/com/svix/MessageAttempt.java
python/svix/api.py

These have been deprecated in the spec for years.

Mark a few deprecated methods as such

---

ChangeLog.md
kotlin/lib/src/main/kotlin/MessageAttempt.kt

Follow-up to https://github.com/svix/svix-webhooks/pull/1618.
Part of https://github.com/svix/monorepo-private/issues/9576.

kotlin: Replace most of MessageAttempt.kt by generated code

---

go/application.go
go/authentication.go
go/backgroundtask.go
go/endpoint.go
go/event_type.go
go/integration.go
go/message.go
go/message_attempt.go
go/operational_webhook_endpoint.go
go/statistics.go

… to reduce the diff of the upcoming codegen PR.
Seems like gofmt just doesn't care about how long function signatures are (no line limit at all???), how many parameters are on one line, whether the closing parenthesis is on a new line or not, or whether there are empty lines between the parameters. This was a _true_ chore.

go: Put parameters on separate lines for API methods

---

python/svix/api/common.py

Cleaning up the python client code in preparation for the new codegen code
These changes I will do by hand, and I want the codegen to be able to match the code (or at least have the diff be as small as possible)

python: Cleanup ListOptions to_dict to use BaseOptions

---

.gitignore
go/.gitignore
regen_openapi.sh
rust/.gitignore
tools/bump_version.js

So we no longer need to patch these in the file committed to the repository root.
Part of https://github.com/svix/monorepo-private/issues/9734.

Patch OpenAPI versions for codegen

---

python/svix/api/__init__.py
python/svix/api/application.py

Most of the code is generated by the codegen, excluding the `get_or_create` code and the `__all__` export

python: add generated client code for application.py

---

regen_openapi.sh

We can remove all these weird hacks once we get rid of OpenAPI generator, but for now we should avoid inflating every single generated file with our doc string / make sure we don't have it in diffs when we ship a less hacky `openapi.json` to this repo.

Remove description from openapi.json before using it for codegen

---

python/svix/api/endpoint.py
python/svix/api/event_type.py
python/svix/api/message_attempt.py

These should be the only files that need sorting, the rest of resources have their methods sorted correctly.

python: Sort methods on python resources consistently

---

ChangeLog.md
python/svix/api/__init__.py
python/svix/api/authentication.py
python/svix/api/endpoint.py
python/svix/api/event_type.py
python/svix/api/integration.py
python/svix/api/message.py
python/svix/api/message_attempt.py
python/svix/api/statistics.py

The `openapi.json` file I am working with is incomplete. 
1. Some of the deprecated methods are not included in the `openapi.json`.
2. Some of the API resources are missing, `background_task` and `operational_webhook`. (I know that  `operational_webhook` is not a single resource)
3. Some API resources that are in the `openapi.json` are not currently in the high-level API client (`health` and `environment`).
Jonas is working on a fix for the `openapi.json` generator.
For now. 
1. I will manually add these deprecated calls by hand. And add a `@deprecated` decorator to those methods.
2. If the API resource is not included in the `openapi.json`, I will leave it as is.
3. For API resources that are not currently in the high-level API client, but are included in the `openapi.json`, I will …

python: Use openapi-codegen for high-level python API client 

---

rust/src/api/background_task.rs
rust/src/api/operational_webhook_endpoint.rs

We fixed the inconsistent operation IDs for background tasks in the spec and added support for subresources in our codegen. This is the improvements these two changes bring.

rust: Pull in changes from codegen improvements

---

.github/workflows/python-tests.yml
python/tests/conftest.py

When running the python tests, the svix server docker image is executed.
Instead of building the server from scratch each time, use the publicly released image.

ci: Switch python tests to use public release image

---

python/svix/api/application.py

`__all__` allows a `from svix.api.application import *`, but this was never a supported feature. And the `__all__` is not in any of the other modules.

python: Remove `__all__` export from `application.py`

---

rust/src/api/message.rs
rust/src/api/message_attempt.rs
rust/src/request.rs

Get rid of one more discrepancy between generated code and the working status quo.

rust: Move query parameter encoding out into request.rs

---

javascript/src/api/authentication.ts
javascript/src/api/background_task.ts
javascript/src/api/event_type.ts
javascript/src/api/integration.ts
javascript/src/api/op_webhook_endpoint.ts
javascript/src/api/operational_webhook_endpoint.ts
javascript/src/index.ts

I don't like the idea of dropping `.codegen.json` files in every subdirectory that contains generated sources, so I'll drop the metadata here instead (and once we have a script for regenerating all the libs + CLI we can have it write a single `.codegen.json`):
```json
{
"file-generated-at": "2025-01-27T15:49:46.172909034+00:00",
"git-rev": "bde54facee73c3ae9a4f21159f0f5d08065e91d7",
"openapi-codegen-version": "0.1.0",
"openapi.json-sha256": "9fa16f8eb28f617b8495cafc9bd529626145df7af01e5c09acdc2b98e39a4725"
}
```

js: Pull in some codegen changes

---

.github/workflows/release.yml
dist-workspace.toml

The dist docs for for the `homebrew` installer indicate there are two parts to this:
1. create a "tap" repo and a github token for dist to use to manage it
2. configure dist here (with the token as a secret)
The first piece will need to be done by someone else. This diff does the 2nd piece.
The config for dist targets the extant `svix/homebrew-svix` repo, which appears to be where the tap lived previously.
It's not clear if we'd need to empty that repo, reboot it, or anything else.
Refs:
- https://opensource.axo.dev/cargo-dist/book/installers/homebrew.html
- https://github.com/svix/homebrew-svix

CLI: enable homebrew installer

---

javascript/src/api/application.ts
javascript/src/api/authentication.ts
javascript/src/api/background_task.ts
javascript/src/api/endpoint.ts
javascript/src/api/event_type.ts
javascript/src/api/integration.ts
javascript/src/api/message.ts
javascript/src/api/message_attempt.ts
javascript/src/api/operational_webhook_endpoint.ts
javascript/src/api/statistics.ts
javascript/src/index.ts
javascript/src/request.ts
javascript/src/util.ts
tools/bump_version.js

Part of https://github.com/svix/monorepo-private/issues/9598.

js: Replace OpenAPI generator http code with our own

---

kotlin/lib/src/main/kotlin/Authentication.kt
kotlin/lib/src/main/kotlin/BackgroundTask.kt
kotlin/lib/src/main/kotlin/EventType.kt
kotlin/lib/src/main/kotlin/Integration.kt
kotlin/lib/src/main/kotlin/OperationalWebhookEndpoint.kt

A bunch of manual changes were unfortunately still required, in particular because Kotlin has some path parameters backwards, which would be a rather nasty breaking change if we fixed it.
```json
{
"file-generated-at": "2025-01-30T13:42:23.808674168+00:00",
"git-rev": "de9e055e589b036eb3ec562c96ca86c83dc91b74",
"openapi-codegen-version": "0.1.0",
"openapi.json-sha256": "316e0fad86746b428a23d871e6148b12e35ac955a9fc57945e2b29a4a43da7c1"
}
```

kotlin: Pull in some changes from codegen

---

javascript/src/request.ts

Missed / forgot this when carrying over request-making logic from the internal openapi library.

js: Add authorization header for requests

---

javascript/src/request.ts

js: don't add query param when value is an empty array

---

ChangeLog.md
go/message_attempt.go

Reduce the diff between generated code and what's currently committed.

go: Add dedicated options type for ListAttemptedDestinations

---

python/svix/models/event_type_import_open_api_out_data.py

@svix-jplatte [here](https://github.com/svix/svix-webhooks-private/blob/dec537950635d73531734c2980811163191c4d32/server/svix-server/src/v1/endpoints/event_type/mod.rs#L720) is where this field is defined

python: Add special case where the server does not send a camelCase field

---

javascript/src/index.ts
javascript/src/request.ts

Closes https://github.com/svix/svix-webhooks/issues/1652.

js: Support setting a request timeout

---

rust/src/models/background_task_out.rs
rust/src/models/connector_in.rs
rust/src/models/connector_kind.rs
rust/src/models/environment_in.rs
rust/src/models/integration_in.rs
rust/src/models/integration_out.rs
rust/src/models/integration_update.rs
rust/src/models/message_attempt_trigger_type.rs
rust/src/models/message_status.rs
rust/src/models/mod.rs
rust/src/models/status_code_class.rs
rust/src/models/template_out.rs

Follow-up to https://github.com/svix/svix-webhooks/pull/1695, last prep PR for including the new openapi-codegen in CI.

rust: Regenerate model files

---

lib-openapi.json

Big diff due to the updates in ID descriptions it seems

Update OpenAPI spec and regenerate libs

---

.github/workflows/bridge-release.yml
.github/workflows/server-release.yml

Breaking changes in v4: https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
I think that shouldn't affect us

Update actions/upload-artifact to v4

---

csharp/Svix.Tests/SvixClientTests.cs
csharp/Svix.Tests/WiremockTests.cs

This is not currently a problem here. But in some other libs, if `iterator` is null this code will panic.
Add tests to me catch any regression

Add tests for ListResponseApplicationOut

---

.github/workflows/release.yml
dist-workspace.toml

ref: https://github.com/actions/runner-images/issues/11101
> The Ubuntu 20.04 Actions runner image will begin deprecation on 2025-02-01 and will be fully unsupported by 2025-04-01

ci: Update to ubuntu-22.04

---

.github/workflows/javascript-release.yml

When this workflow is triggered by the [Mega Releaser](https://github.com/svix/svix-webhooks/actions/workflows/mega-releaser.yml), `github.event.pusher` is empty (see https://github.com/svix/svix-webhooks/actions/runs/13396336811/job/37416216605). This adds a fallback value so it doesn't fail. 
The value doesn't really matter because it's only needed to run `yarn version`, not actually used to publish the package.

Fix Javascript release workflow

---

.github/workflows/release.yml
dist-workspace.toml

Sadly I have `allow-dirty = ["ci"]` or else dist will complain

Make homebrew action run under release environment

---

.github/workflows/cli-lint.yml
.github/workflows/rust-lint.yml
regen_openapi.sh
rust/src/api/message.rs
rust/src/models/mod.rs
rust/templates/api_extra/application_create.rs
rust/templates/api_extra/message.rs
rust/templates/api_extra/message_attempt_list_attempted_messages.rs
rust/templates/api_extra/message_expunge_content.rs
rust/templates/api_resource.rs.jinja
rust/templates/api_summary.rs.jinja
rust/templates/component_type.rs.jinja
rust/templates/types/integer_enum.rs.jinja
rust/templates/types/string_enum.rs.jinja
rust/templates/types/struct.rs.jinja

I'm not back from vacation yet, but I had a free minute and wanted to get this branch that I had ready locally into a PR.
The first commit includes a typo that's carried over from the OpenAPI spec: `ExpungAllContentsOut` should be `ExpungeAllContentsOut`. Should be fixed separately.

Add rust lib regeneration to regen_openapi.sh

---

.github/workflows/javascript-release.yml

Context: We use `ref_type` to check if we are running on a branch or a tag If we are running on a branch (main) we will publish a pre-release version of the js lib If we running on a tag we publish the new "real" version
The problem happens when a workflow gets triggered using workflow_run, the `github.ref_type` is not preserved, And even if the Mega releaser had a  ref_type = 'tag' the js release workflow sees ref_type = 'branch' (https://github.com/orgs/community/discussions/27124)
To fix this, I check if `github.event.workflow_run.head_branch` starts with 'v' (v1.58.0), this tells me if this workflow was triggered workflow_run

ci: Fix issue with svix next package publishing

---

javascript/tsconfig.json

Without this tsc will create a `src` subdir in our packages

js: Ignore eslint.config.mjs

---

.github/workflows/go-ci.yml
go/svix_http_client.go
go/svix_test.go

`math/rand/v2` was introduced in go 1.22.
Since we are not using any v2 specific features, there is no need to use v2
Also add go1.21 as a target in CI
ref: https://github.com/svix/svix-webhooks/issues/1745

go: Switch to `math/rand` from `math/rand/v2` #1745

---

.github/workflows/kotlin-release.yml

The `regen_openapi.sh` does not generate our kotlin lib anymore

ci: Remove regen_openapi.sh from kotlin release

---

.github/workflows/codegen.yml

Tested successfully: https://github.com/svix/svix-webhooks/actions/runs/13500955055/job/37718984950

ci: Add workflow to check for uncommitted codegen changes

---

tools/bump_version.js

The script reads the `.version` file to get the `<old_version>` It then uses the `<new_version>` from `argv[2]` to replace `<old_version>` with `<new_version>` for all of the files in `filesPaths`
There is a bug if for whatever reason the `<old_version>` in the target file does not match the `<old_version>` in `.version`
I added a quick check to see if the file was modified, if it was not exit with status 1

Fix bug in bump_version.js script

---

regen_openapi.sh
rust/templates/component_type.rs.jinja
rust/templates/types/struct.rs.jinja
rust/templates/types/struct_enum.rs.jinja
rust/templates/types/struct_fields.rs.jinja

Depends on https://github.com/svix/openapi-codegen/pull/76.

rust: Update codegen templates to support struct enums

---

javascript/src/mockttp.test.ts
javascript/src/models/appPortalAccessIn.ts
javascript/src/models/connectorIn.ts
javascript/src/models/messageAttemptOut.ts
javascript/src/models/messageIn.ts

In the case of `MessageAttemptOut`, If there is no `msg` field then the `_fromJsonObject` is called on `undefined`. This causes a runtime panic.
The solution is to do a quick null check before calling `_fromJsonObject`
Depends on: https://github.com/svix/openapi-codegen/pull/77

js: Fix issues causing `_fromJsonObject` to panic at runtime

---

regen_openapi.sh

Accidentally included in #1756. Since the ruby lint workflow didn't trigger, we didn't catch the breakage.

Remove accidentally-committed early exit from regen_openapi.sh

---

.github/workflows/codegen.yml
javascript/templates/api_extra/application_create.ts
javascript/templates/api_extra/background_task_list.ts
javascript/templates/api_extra/endpoint_patch_headers.ts
javascript/templates/api_extra/endpoint_update_headers.ts
javascript/templates/api_extra/message.ts
javascript/templates/api_resource.ts.jinja
javascript/templates/component_type.ts.jinja
javascript/templates/component_type_summary.ts.jinja
javascript/templates/types/integer_enum.ts.jinja
javascript/templates/types/string_enum.ts.jinja
javascript/templates/types/struct.ts.jinja
javascript/tsconfig.json
regen_openapi.sh

One tiny change from the templates currently in https://github.com/svix/openapi-codegen: `DateTime` query parameters  are hardcoded to accept `null` (they were broken since a recent PR correctly changed `Date | null` => `Date` in JS type translation).

js: Add new codegen templates

---

python/templates/component_type.py.jinja
python/templates/types/struct.py.jinja
python/templates/types/struct_enum.py.jinja
python/templates/types/struct_fields.py.jinja

Tested with the ingest source API that this generates the expected code. Once we commit that, we should also have a (de)serialization test. I'm fairly certain I did the pydantic stuff right, but who knows.
We should also update `component_type_summary` since struct enums are separate types that we should export from the `models` module, but that can be a separate PR.

python: Update codegen templates to support struct enums

---

csharp/Svix.Tests/WiremockTests.cs
go/svix_http_client_test.go
java/lib/src/test/com/svix/test/WiremockTests.java
javascript/src/mockttp.test.ts
kotlin/lib/src/test/com/svix/kotlin/WiremockTests.kt

Add test cases for `#` in a url param
Python/Rust will be in a separate PR
ref: https://github.com/svix/monorepo-private/issues/9996

Add url encoding test for C#,Go,Java,Kotlin and Typescript

---

rust/src/api/mod.rs
rust/src/api/operational_webhook.rs
rust/templates/api_resource.rs.jinja

We are going to deprecate the `svix.operational_webhook_endpoint()` accessor in favor of `svix.operational_webhook().endpoint()` down the line.
The new file was generated using https://github.com/svix/openapi-codegen/pull/86. I'm not updating the git rev in this PR though because that PR is not yet merged, and because the other templates we use in CI have not yet been updated. Luckily we don't currently error when there are unused left-over files, though maybe we should do so down the line.

rust: Add OperationalWebhook resource

---

go/svix_http_client.go

Fixes a regression with our new Go lib, we used to return a `*svix.Error`.

go: Return a pointer to an error

---

go/application.go
go/authentication.go
go/background_task.go
go/endpoint.go
go/event_type.go
go/integration.go
go/message.go
go/message_attempt.go
go/models.go
go/models/expunge_all_contents_out.go
go/models/ingest_endpoint_headers_in.go
go/models/ingest_endpoint_headers_out.go
go/models/ingest_endpoint_in.go
go/models/ingest_endpoint_out.go
go/models/ingest_endpoint_secret_in.go
go/models/ingest_endpoint_secret_out.go
go/models/ingest_endpoint_update.go
go/models/list_response_ingest_endpoint_out.go
go/operational_webhook_endpoint.go
go/statistics.go
openapi-templates/go/api_extra/application_create.go
openapi-templates/go/api_resource.go.jinja
openapi-templates/go/component_type.go.jinja
openapi-templates/go/component_type_summary.go.jinja
openapi-templates/go/types/integer_enum.go.jinja
openapi-templates/go/types/string_enum.go.jinja
openapi-templates/go/types/struct.go.jinja
regen_openapi.sh

Pull in Go templates from the `openapi-codegen` repo
Also pull in latest changes from `lib-openapi.json`
For now `regen_openapi.sh` for Go is disabled in CI
If I leave the templates in the `go` folder, `go build` will try to compile the `api_extra` files
So I am placing the templates in `openapi-templates/go`.
Once merged I will go around the other libs and move their templates to the `openapi-templates` dir

go: Pull in change from latest codegen

---

ChangeLog.md
java/lib/src/main/java/com/svix/api/Message.java
java/lib/src/main/java/com/svix/models/MessageIn.java
java/lib/src/test/com/svix/test/WiremockTests.java
java/lib/src/test/resources/__files/ExpectedMsgCreateBody.json
java/lib/src/test/resources/__files/ExpectedMsgCreateBody2.json
java/lib/src/test/resources/__files/ExpectedMsgCreateBodyWithHeaders.json
java/templates/api_extra/message.java
java/templates/api_extra/message_create_body.java
java/templates/api_resource.java.jinja
java/templates/types/struct.java.jinja
kotlin/lib/src/main/kotlin/Message.kt
kotlin/lib/src/main/kotlin/models/MessageIn.kt
kotlin/lib/src/test/com/svix/kotlin/BasicTest.kt
kotlin/lib/src/test/com/svix/kotlin/WiremockTests.kt
kotlin/templates/api_extra/message.kt
kotlin/templates/api_extra/message_create_body.kt
kotlin/templates/api_resource.kt.jinja
kotlin/templates/types/struct.kt.jinja

Switch to type of `MessageIn.payload` to a string, this allows customers to send pre-serialized json string
fixes: https://github.com/svix/svix-webhooks/issues/1779

java/kotlin: Switch the type of `MessageIn.payload` to a string

---

go.mod

This bug was introduced in https://github.com/svix/svix-webhooks/commit/b8c5b8cf8a685bd8546b3bc28c948781e1e6fbc2 (v1.57.0) and fixed in https://github.com/svix/svix-webhooks/commit/58f9f543fad3dffb8ac3e555220ff346b4cbd779 (v1.61.1).

go: Retract versions with silent error handling breakage

---

javascript/src/mockttp.test.ts
javascript/src/request.ts

For some reason on we were not sending the correct content-type in our js lib
The server then responds with
```
Expected request with `Content-Type: application/json`
```
Then json parsing of the returned error fails, and we crash at runtime.
Other endpoints like `v1.application.create` and `v1.message.create`, do not return this error when they receive a request without a content-type (or with an incorrect content-type)
fixes: https://github.com/svix/svix-webhooks/issues/1799

js: Send content type on request

---

.github/workflows/typos.yml
.typos.toml

cc @svix-mman re #1794 I think you should make `ser` an allowed word the same way as `typ` here.

ci: Upgrade typos

---

python/templates/types/struct_fields.py.jinja

We've got some field-less object types in the next version of our API spec.

python: Support field-less object types

---

rust/tests/it/model_serialization.rs

rust: Make model serialization test non-async

---

server/Cargo.lock

A few updates were excluded to avoid duplicating heavy dependencies.
Most notably, this includes an upgrade to ring that fixes [RUSTSEC-2025-0009](https://rustsec.org/advisories/RUSTSEC-2025-0009).

server: Update most dependencies

---

deny.toml

Together with https://github.com/svix/svix-webhooks/pull/1807, should make CI green.

Silence new unmaintained RUSTSEC

---

server/svix-server/src/v1/endpoints/endpoint/recovery.rs

The intent of the recovery loop seems to be to recover up to the `RECOVERY_LIMIT` in increments of `BATCH_SIZE`, but the limit arg is currently set to `RECOVERY_LIMIT`.
There also seems to be a typo in how the loop breaks, which could cause an excessive number of messages to be recovered: `num_done > RECOVERY_LIMIT` instead of `num_done >= RECOVERY_LIMIT` (equal should also break the loop).
This change should result in a more reasonable load per request on external resources (i.e., db & queue) as seemingly originally intended. However, it will likely make the recovery process slower as the number of messages to recover approaches the limit; what was 1 loop will now be up to 100, at the limit.  
Set limit to `BATCH_SIZE` and stop when `num_done >= `RECOVERY_LIMIT`.

server: Run recover in batches

---

codegen.toml

Does not affect anything
https://github.com/svix/monorepo-private/issues/10071 will add the endpoints that are currently excluded

Enable codegen for svix-cli

---

codegen.toml
javascript/src/api_internal/environment.ts
javascript/src/models/borderRadiusConfig.ts
javascript/src/models/borderRadiusEnum.ts
javascript/src/models/customColorPalette.ts
javascript/src/models/customStringsOverride.ts
javascript/src/models/customThemeOverride.ts
javascript/src/models/environmentSettingsOut.ts
javascript/src/models/fontSizeConfig.ts
regen_openapi.py

This operation was disabled because of a limitation on the codegen side
The limitation is now fixed

js: Enable v1.environment.get-settings

---

codegen.toml

This is a nice to have when codegen has problems and you are trying to iterate as you work through the issues.

Codegen: allow staged during cargo fix

---

codegen.toml
svix-cli/Cargo.toml
svix-cli/src/cmds/api/events_public.rs
svix-cli/src/cmds/api/mod.rs
svix-cli/src/main.rs

Adds support for using `v1.events-public.consumer` and `v1.events-public.consumer-seek`, but gated behind a `svix_beta` cargo feature.

CLI: add support for Polling Endpoint Consumers

---

.github/workflows/bridge-ci.yml
bridge/Cargo.lock
bridge/svix-bridge-plugin-kafka/src/input.rs
bridge/svix-bridge-plugin-kafka/tests/it/kafka_consumer.rs
bridge/svix-bridge-plugin-queue/src/lib.rs
bridge/svix-bridge-plugin-queue/tests/it/gcp_pubsub_consumer.rs
bridge/svix-bridge-plugin-queue/tests/it/rabbitmq_consumer.rs
bridge/svix-bridge-plugin-queue/tests/it/redis_stream_consumer.rs
bridge/svix-bridge-plugin-queue/tests/it/sqs_consumer.rs
bridge/svix-bridge-types/Cargo.toml
bridge/svix-bridge-types/src/lib.rs
bridge/svix-bridge/src/config/mod.rs
bridge/svix-bridge/src/config/tests.rs
bridge/svix-bridge/src/webhook_receiver/mod.rs

This diff updates bridge's `PollerInput` to be based on the newer stream API exposed by Polling Endpoints.

Bridge: update to use new rust lib, refactor poller input

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/core/types/mod.rs
server/svix-server/src/lib.rs
server/svix-server/src/v1/utils/mod.rs
server/svix-server/src/worker.rs

Drop the direct dependency on `once_cell` as equivalent functionality was released in `std` for Rust 1.80 (July 25, 2024). 
Eventually this will hopefully lead to 1 less dependency, however for now `once_cell` still remains as an indirect dependency since it is used widely in the ecosystem.
Replace usage of `once_cell::sync::Lazy` with `std::sync::LazyLock`.

server: Replace usage of once_cell with equivalent from std

---

javascript/.gitignore

This directory should be removed from existing cloned of the repo.

Remove src/openapi from javascript/.gitignore

---

ruby/lib/svix/svix.rb

I missed this in https://github.com/svix/svix-webhooks/pull/1847.

ruby: Add ingest resource to svix Client

---

.github/workflows/bridge-release.yml
bridge/Dockerfile

Bridge now depends on svix SDK using a path dependency

bridge: Fix dockerfile

---

.github/workflows/bridge-ci.yml
.github/workflows/rust-lint.yml
.github/workflows/server-ci.yml
bridge/Cargo.lock
bridge/svix-bridge/Cargo.toml
server/svix-server/Cargo.toml

It has happened from time to time that dependencies have gone unused but we didn't notice. This should fix that once and for all :)
Add [`cargo-machete`](https://github.com/bnjbvr/cargo-machete#readme) to CI.

ci: Check for unused dependencies

---

python/svix/models/ingest_source_in.py
python/svix/models/ingest_source_out.py
python/templates/types/struct_enum.py.jinja

`match` was introduced in python 3.10, and we support python >= 3.6

python: Remove match statement in favor of if-elif-else

---

python/requirements.txt

We are using ModelWrapValidatorHandler, which was introduced in 2.10
Also add maximum versions because it seems wrong that we don't have them.

python: Fix minimum version for pydantic

---

python/requirements.txt

In https://github.com/svix/svix-webhooks/pull/1869, I accidentally changed the version requirement of setuptools to an ancient version. Everything <70 is affected by a security issue, so bump the minimum version to that and remove the upper bound again.

python: Raise minimum version for setuptools, remove maximum version

---

bridge/Cargo.lock
server/Cargo.lock
svix-cli/Cargo.lock

Latest tokio version contains a fix for an unsoundness: https://rustsec.org/advisories/RUSTSEC-2025-0023
Same for the openssl crate: https://rustsec.org/advisories/RUSTSEC-2025-0022

Upgrade tokio, openssl

---

svix-cli/Cargo.toml
svix-cli/src/cmds/login.rs
svix-cli/src/main.rs

Adds a selector when using `svix login` to log in using the dashboard. 
**Demo:**
https://github.com/user-attachments/assets/ec5a6480-723b-4111-a9bb-4c14f090071a

svix-cli: Add interactive login

---

bridge/.config/nextest.toml

Maybe this will help with the kafka tests.
I checked a successful test run and it only took 12s, but I think there's still a chance that this will be of use.

bridge: Wait longer before aborting tests

---

go/svix_http_client.go

go: Do a nil check before debugging the response

---

go/application.go
go/authentication.go
go/background_task.go
go/endpoint.go
go/environment.go
go/errors.go
go/event_type.go
go/ingest.go
go/ingest_endpoint.go
go/ingest_source.go
go/integration.go
go/internal/error.go
go/internal/svix_http_client.go
go/management.go
go/management_authentication.go
go/message.go
go/message_attempt.go
go/message_poller.go
go/operational_webhook.go
go/operational_webhook_endpoint.go
go/statistics.go
go/svix.go
openapi-templates/go/api_extra/application_create.go
openapi-templates/go/api_extra/authentication_expire_all.go
openapi-templates/go/api_resource.go.jinja

This is done in preparation for the new internal API client
In Go, the `internal` package has special semantics. https://pkg.go.dev/cmd/go#hdr-Internal_Directories
So we can define public  method for our SDK to consume, but external packages wont be able to import the internal package
For example this is the error I get when trying to import the internal package in the TF provider
```
package github.com/svix/terraform-provider-svix
main.go:10:3: use of internal package github.com/svix/svix-webhooks/go/internal not allowed
```
This is technically a breaking change, because the `svix.SvixHttpClient` struct will no longer be available 
However, this is not an issue. Since there is no use in defining the `svix.SvixHttpClient` by hand, because the only use case it has is to be part of the …

Move `SvixHttpClient` to internal package

---

codegen.toml
go/internalapi/internalapi.go
go/internalapi/management.go
go/internalapi/management_environment.go
go/internalapi/management_environment_settings.go
go/models/border_radius_config.go
go/models/border_radius_enum.go
go/models/custom_color_palette.go
go/models/custom_strings_override.go
go/models/custom_theme_override.go
go/models/environment_model_in.go
go/models/environment_model_out.go
go/models/environment_model_update.go
go/models/environment_region.go
go/models/environment_type.go
go/models/font_size_config.go
go/models/list_response_environment_model_out.go
go/models/settings_internal_in.go
go/models/settings_internal_out.go
regen_openapi.py

Create new Go internal API client
This client only has the limited set of operations needed for the terraform plugin
note: This is branched from https://github.com/svix/svix-webhooks/pull/1884, I will rebase on main once https://github.com/svix/svix-webhooks/pull/1884 is  merged

Create new internal Go lib

---

bridge/Dockerfile
server/Dockerfile
svix-cli/Dockerfile

Upgrade our Dockerfile's to the latest stable Rust toolchain (the only officially-supported one).

Bump Rust toolchain to 1.86

---

go/internalapi/internalapi.go

go: Use debug arg in `InternalSvix`

---

go/internal/svix_http_client.go

Also fix bug where GET request would send `null` as the body

go: Set `Content-type` on put requests

---

go/models/background_task_status.go
go/models/background_task_type.go
go/models/border_radius_enum.go
go/models/connector_kind.go
go/models/endpoint_disabled_trigger.go
go/models/environment_region.go
go/models/environment_type.go
go/models/ingest_source_in.go
go/models/ingest_source_out.go
go/models/message_attempt_trigger_type.go
go/models/message_status.go
go/models/ordering.go
go/models/status_code_class.go
openapi-templates/go/types/integer_enum.go.jinja
openapi-templates/go/types/string_enum.go.jinja
openapi-templates/go/types/struct_enum.go.jinja

This also lets me know what are the valid options for the enum. (because I can check the map keys)

go: Add map that can create the enum value from the underlying literal

---

server/svix-server/src/cfg.rs
server/svix-server/src/core/operational_webhooks.rs

This PR addresses issue #1138  "Handling of operational webhooks server name" which was identified after users experienced problems configuring and troubleshooting operational webhooks in local development environments.
The current implementation of operational webhooks has two key issues:
1. The server URL provided in `SVIX_OPERATIONAL_WEBHOOK_ADDRESS` is not validated or sanitized before use, leading to problems when users provide URLs with trailing slashes or incorrect formats.
2. When operational webhooks fail to deliver with a 404 error, the system logs a generic "Operational webhooks are enabled but no listener set for {org_id}" message, without distinguishing between different failure scenarios (e.g., incorrect URL format, missing application, or missing endpoint).
These issues …

Add URL validation to operational server webhooks

---

.github/workflows/csharp-lint.yml

This will help with borked CI in https://github.com/svix/svix-webhooks/pull/1906

Ci: pin csharpier to 0.30.6 

---

go/internalapi/internalapi.go
go/svix.go

This allows users of the go lib to suffix the `user-agent` with whatever custom string they chose
This will be used in the terraform provider, to indicate that requests are coming from the provider
The providers user agent will looks like this
`svix-libs/1.64.1/go/tf-provider-v0.1.1`

go: Add `SetUserAgentSuffix`

---

bridge/svix-bridge/src/webhook_receiver/mod.rs

There is no health enpoint in svix bridge so this PR adds a health endpoint to svix bridge
Work in progress

feat: svix bridge-health-endpoint

---

csharp/Svix/Svix.csproj

This results in the fowling fields added to the generated `Svix.nuspec` file (the file is generated when release CI runs `dotnet build --configuration Release Svix`)
```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
<metadata>
+ <license type="expression">MIT</license>
+ <licenseUrl>https://licenses.nuget.org/MIT</licenseUrl>
+ <projectUrl>https://github.com/svix/svix-webhooks/tree/main/csharp</projectUrl>
+ <repository type="git" url="https://github.com/svix/svix-webhooks.git" commit="da87aa3647219021fc5b60733e6c042fb75f2bfc" />
</metadata>
</package>
```
Closes https://github.com/svix/svix-webhooks/issues/1911

csharp: Add nuget package metadata

---

ChangeLog.md
csharp/Svix/SvixClient.cs
csharp/Svix/Utils.cs

The baseUrl will be generated from the token
This makes the C# lib more consistent with the other SDKs

csharp: `SvixOptions` is now optional when initializing a new `SvixClient`

---

.github/workflows/csharp-lint.yml
csharp/Svix.Tests/RetryScheduleTests.cs
csharp/Svix.Tests/Svix.Tests.csproj
csharp/Svix.Tests/WebhookTest.cs
csharp/Svix.Tests/WiremockTests.cs
csharp/Svix/Models/BackgroundTaskFinishedEvent.cs
csharp/Svix/Models/EndpointCreatedEvent.cs
csharp/Svix/Models/EndpointCreatedEventData.cs
csharp/Svix/Models/EndpointDeletedEvent.cs
csharp/Svix/Models/EndpointDeletedEventData.cs
csharp/Svix/Models/EndpointDisabledEvent.cs
csharp/Svix/Models/EndpointDisabledEventData.cs
csharp/Svix/Models/EndpointEnabledEvent.cs
csharp/Svix/Models/EndpointEnabledEventData.cs
csharp/Svix/Models/EndpointHeadersOut.cs
csharp/Svix/Models/EndpointMessageOut.cs
csharp/Svix/Models/EndpointUpdatedEvent.cs
csharp/Svix/Models/EndpointUpdatedEventData.cs
csharp/Svix/Models/EventTypeImportOpenApiIn.cs
csharp/Svix/Models/MessageAttemptExhaustedEvent.cs
csharp/Svix/Models/MessageAttemptExhaustedEventData.cs
csharp/Svix/Models/MessageAttemptFailingEvent.cs
csharp/Svix/Models/MessageAttemptFailingEventData.cs
csharp/Svix/Models/MessageAttemptRecoveredEvent.cs
csharp/Svix/Models/MessageAttemptRecoveredEventData.cs
csharp/Svix/Models/PollingEndpointMessageOut.cs
csharp/Svix/Svix.csproj
regen_openapi.py

Ci will fail because I am waiting for https://github.com/svix/openapi-codegen/pull/108 before I can update the codegen image
All of the changes to the `*.cs` files were created from running 
```bash
cd csharp
csharpier format .
```

csharp: Bump csharpier to v1.0.1

---

regen_openapi.py

Latest change https://github.com/svix/openapi-codegen/pull/109
Rubyfmt is not compiled from source each time

Bump codegen image

---

codegen.toml

We use `sed` to do a quick text replace as part of the libs codegen
Macos ships a BSD `sed` and (most) linux distros ship a GNU `sed`, they are not exactly 1-1 compatible 
This PR makes the `sed` command work on both GNU/BSD sed

Make sed command work both on macos/linux

---

ChangeLog.md
codegen-templates/javascript/types/macros.ts.jinja
javascript/src/models/apiTokenCensoredOut.ts
javascript/src/models/apiTokenOut.ts
javascript/src/models/endpointDisabledEventData.ts
javascript/src/models/endpointMessageOut.ts
javascript/src/models/environmentOut.ts
javascript/src/models/listResponseApiTokenCensoredOut.ts
javascript/src/models/listResponseApplicationOut.ts
javascript/src/models/listResponseBackgroundTaskOut.ts
javascript/src/models/listResponseEndpointMessageOut.ts
javascript/src/models/listResponseEndpointOut.ts
javascript/src/models/listResponseEventTypeOut.ts
javascript/src/models/listResponseIngestEndpointOut.ts
javascript/src/models/listResponseIngestSourceOut.ts
javascript/src/models/listResponseIntegrationOut.ts
javascript/src/models/listResponseMessageAttemptOut.ts
javascript/src/models/listResponseMessageEndpointOut.ts
javascript/src/models/listResponseMessageOut.ts
javascript/src/models/listResponseOperationalWebhookEndpointOut.ts
javascript/src/models/messageEndpointOut.ts
javascript/src/models/pollingEndpointOut.ts
javascript/src/models/recoverIn.ts
javascript/src/models/replayIn.ts

It's a bug! Actually produces invalid data as far as I can tell, as `new Date(null)` of course produces a valid date, rather than raising an exception...
Only call `new Date` on non-null data. The other change (first commit) is a drive-by improvement.

js: Fix handling of optional dates in response bodies

---

.github/workflows/bridge-ci.yml

The upstream change was reverted.

Remove cmake hack again

---

composer.json
php/src/Exception/WebhookSigningException.php
php/src/Exception/WebhookVerificationException.php
php/src/Webhook.php

Officially [supported versions](https://www.php.net/supported-versions) are currently 8.1 - 8.4.

php: Bump minimum version to 8.0

---

server/svix-server/tests/it/e2e_auth.rs
server/svix-server/tests/it/e2e_endpoint.rs
server/svix-server/tests/it/e2e_message.rs
server/svix-server/tests/it/utils/common_calls.rs
svix-cli/src/cmds/login.rs

Had to modify some tests for raw-payload (https://github.com/svix/svix-webhooks/issues/1927) + got some local clippy lints. This frontloads taking care of those unrelated improvements (and some more I found), so the next PR will have a smaller diff.

Some refactors

---

go/internal/svix_http_client.go
go/svix_http_client_test.go
go/svix_test.go

Some customers are seeing HTTP 400 responses from our load balancer, only with the Go SDK and only with HTTP/2.0.
Disable HTTP/2.0 for the Go SDK.

go: Disable HTTP/2.0

---

server/svix-server/src/db/models/messagecontent.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/tests/it/e2e_message.rs

Ensure messagecontent expiration is set

---

php/src/Webhook.php
php/tests/WebhookTest.php

Currently a notice will be thrown because of the invalid array access after splitting the signature. Would an exception be better here? signalling unexpected data from svix?
I ran into this while testing Svix integration in our app, and throwing random test data at it. I understand this data should come from Svix, but it seems like it should be handled gracefully anyway.
If the signature in the header doesn't at least appear well formatted, skip it.

[PHP] Handle Badly Formatted Signatures

---

bridge/Cargo.lock
csharp/Svix.Tests/WiremockTests.cs
csharp/Svix/SvixHttpClient.cs
csharp/justfile
go.mod
go.sum
go/internal/svix_http_client.go
go/svix_http_client_test.go
java/lib/src/main/java/com/svix/SvixHttpClient.java
java/lib/src/test/com/svix/test/WiremockTests.java
javascript/package.json
javascript/src/mockttp.test.ts
javascript/src/request.ts
javascript/yarn.lock
kotlin/lib/src/main/kotlin/SvixHttpClient.kt
kotlin/lib/src/test/com/svix/kotlin/WiremockTests.kt
kotlin/lib/src/test/resources/__files/ApplicationOut.json
python/svix/api/common.py
python/tests/test_httpretty.py
ruby/lib/svix/svix_http_client.rb
ruby/spec/webmock_tests_spec.rb
rust/Cargo.toml
rust/src/request.rs
rust/tests/it/wiremock_tests.rs
svix-cli/Cargo.lock

... If the user of the SDK did not already add an idempotency key
Closes: https://github.com/svix/monorepo-private/issues/10619

Automatically send an idempotency key on all requests

---

csharp/Svix.Tests/WiremockTests.cs
csharp/Svix/SvixHttpClient.cs
go/internal/svix_http_client.go
go/svix_http_client_test.go
java/lib/src/main/java/com/svix/SvixHttpClient.java
java/lib/src/test/com/svix/test/WiremockTests.java
javascript/src/mockttp.test.ts
javascript/src/request.ts
kotlin/lib/src/main/kotlin/SvixHttpClient.kt
kotlin/lib/src/test/com/svix/kotlin/WiremockTests.kt
python/svix/api/common.py
python/tests/test_httpretty.py
ruby/lib/svix/svix_http_client.rb
ruby/spec/webmock_tests_spec.rb
rust/src/request.rs
rust/tests/it/wiremock_tests.rs

No need to send this on requests where the server won't use the `idempotency-key` at all

Only send `idempotency-key` on post requests

---

server/Cargo.lock
server/svix-server/Cargo.toml
server/svix-server/src/core/cryptography.rs
server/svix-server/src/core/idempotency.rs
server/svix-server/src/core/message_app.rs
server/svix-server/src/core/types/mod.rs
server/svix-server/src/core/webhook_http_client.rs
server/svix-server/src/error.rs
server/svix-server/src/expired_message_cleaner.rs
server/svix-server/src/metrics/redis.rs
server/svix-server/src/queue/mod.rs
server/svix-server/src/queue/redis.rs
server/svix-server/src/v1/endpoints/auth.rs
server/svix-server/src/v1/endpoints/message.rs
server/svix-server/src/worker.rs
server/svix-server/tests/it/e2e_endpoint.rs
server/svix-server_derive/src/aide.rs

Closes https://github.com/svix/svix-webhooks/issues/258.
I've gone over the server code and replaced the most obvious parts with unnecessary allocations with no or less allocating counterparts. I was really bothered with how signatures string are generated, so I payed more attention to their function, I think there's still a room for improvement, but it'll need more changes all over the server codebase. For now, let's start from this.
I've also updated `base64` to the latest version. The current version doesn't have needed for this PR function to calculate an encoded string length.
Review commit by commit.

server: Reduce allocations

---

dist-workspace.toml

The one dist is trying to use was just removed: https://github.com/actions/runner-images/issues/12045

Upgrade to a supported runner for Windows releases

---

go/internal/svix_http_client.go
go/internal/svix_http_client_test.go

- I am occasionally seeing the Sentry error 
```
Post "<svix-server-url>": http: ContentLength=2461 with Body length 0
```
in our Sentry as a result of an error with the Golang Svix Client.
When reading through the code it seems like this behaviour is caused when calling executeRequestWithRetries when a retry occurs and the body, which is a ReadCloser is read once on the initial call, there's nothing left in the stream, and then a retry results in the above error.
- preserve the request body at the start of executeRequestWithRetries
- set it on initial try and on subsequent retries
You can verify this behaviour by running the tests against the current code and observing the failure as below, and then applying the changes and checking the tests pass.

fix(go): fix execute with retry empty body bug

---

bridge/Dockerfile
server/Dockerfile
svix-cli/Dockerfile

Fixes issue where user had endpoint with certificate signed by a CA that was missing
This was the missing CA [crt.sh?q=4267304690](https://crt.sh/?q=4267304690)

Bump version of `ca-certificates`

---

codegen/codegen.toml
regen_openapi.py

Codegen used to not support excluding files from generation, so we had some `rm commands`. I am now replacing the `rm` commands with the codegen's builtin `--exclude-op-id`
Happy to discuses if we even want to remove these api endpoints

Remove `rm` commands from codegen. use the builtin `--exclude-op-id`

---

ChangeLog.md
bridge/svix-bridge/src/http_output.rs

It is a good practice to include a user-agent. Some services even block requests without a user-agent.

bridge: Add default user-agent to http output

---

csharp/Svix.Tests/WiremockTests.cs
go/svix_test.go
java/lib/src/main/java/com/svix/Utils.java
java/lib/src/test/com/svix/test/WiremockTests.java
javascript/src/mockttp.test.ts
kotlin/lib/src/main/kotlin/SvixHttpClient.kt
kotlin/lib/src/test/com/svix/kotlin/WiremockTests.kt
python/tests/test_httpretty.py
ruby/spec/webmock_tests_spec.rb
rust/tests/it/wiremock_tests.rs

If the server responds with extra unknown keys, ignore them.
Java and Kotlin, this involves adding a setting to the deserializer "object thingy" 
For the rest, we already ignore unknown keys. So I added some tests.

libs: Ignore unknown keys

---

javascript/yarn.lock

This resolves GHSA-xffm-g5w8-qvg7 by bumping eslint from 9.20 to 9.33. `yarn run eslint` still passes.

deps(js): bump eslint

---

bridge/Dockerfile
svix-cli/Dockerfile

This PR pins `ca-certificates` to latest version and fixes the bridge/cli dockerfiles
I will open another PR to replace all of the `;` with `&&`

 Pin latest ca-certificates and fix the bridge/cli dockerfile 

---

bridge/Dockerfile
svix-cli/Dockerfile

Just like we do everywhere else.

Use fully-qualified image names in bridge/Dockerfile, svix-cli/Dockerfile

---

svix-cli/Dockerfile

This converts the `svix-cli/` Dockerfile to use the newer Dockerfile v1 features (specifically, requiring at least Docker 1.2, introduced in 2020), with things like heredocs and cache mounts. This is the same as svix/svix-webhooks#2023, but for `cli`.

docker: convert cli dockerfile to use v1 syntax

---

server/.dockerignore
server/Dockerfile
server/scripts/launch-svix-server

This converts the `server/` Dockerfile to use the newer Dockerfile v1 features (specifically, requiring at least Docker 1.2, introduced in 2020), with things like heredocs and cache mounts. This is the same as svix/svix-webhooks#2023, but for `server`.
In addition to the aforementioned changes, this also makes `CMD` a separate bash script instead of a multiline heredoc; this doesn't make that much of a difference in OSS (`ps` is less ugly, but whatever) but will let us greatly clean up the private version.

docker: convert server dockerfile to use v1 syntax

---

server/svix-server/src/v1/endpoints/auth.rs

… instead of returning a useless dummy link.
The page hasn't been deployed yet, keeping this in draft until it is.
Part of https://github.com/svix/monorepo-private/issues/11098.

Link to new app portal OSS docs page in app-portal-access response

---

rust/Cargo.toml

wiremock 0.6.5 was released yesterday; it bumps its MSRV to 1.88.0 (without setting the `rust-version` key in Cargo.toml). I don't really want to bump our MSRV to 1.88.0, so pin `< 0.6.5` for now.
I sent https://github.com/LukeMathWalker/wiremock-rs/pull/172 upstream to fix that issue.

deps(dev): pin wiremock < 0.6.5

---

.github/workflows/csharp-lint.yml
.github/workflows/go-ci.yml
.github/workflows/go-lint.yml
.github/workflows/java-lint.yml
.github/workflows/javascript-lint.yml
.github/workflows/kotlin-lint.yml
.github/workflows/python-lint.yml
.github/workflows/python-tests.yml
.github/workflows/ruby-lint.yml
.github/workflows/rust-lint.yml

We moved the `lib-openapi.json` to `codegen/lib-openapi.json`

ci: Use correct path for `lib-openapi.json` trigger

---

.github/workflows/cli-lint.yml
svix-cli/Cargo.lock

It was out of sync with Cargo.toml (breaking the docker release for the CLI).
Update CI to check for this.

Fix svix-cli/Cargo.lock

---

ChangeLog.md
go/message_ext.go
go/svix_test.go

go: Send eventType on messages created with `NewMessageInRaw`

---

codegen/templates/rust/types/struct_enum.rs.jinja
rust/src/models/ingest_source_in.rs
rust/src/models/ingest_source_out.rs

New clippy lint on beta is making CI unhappy.
Silence the lint, it's not worth following for generated code (we'd have to add couple extra template conditionals).

Silence clippy lint in generated code

---

codegen/templates/javascript/types/struct.ts.jinja
codegen/templates/javascript/types/struct_enum.ts.jinja
javascript/biome.jsonc
javascript/src/KitchenSink.test.ts
javascript/src/models/adobeSignConfigOut.ts
javascript/src/models/airwallexConfigOut.ts
javascript/src/models/checkbookConfigOut.ts
javascript/src/models/docusignConfigOut.ts
javascript/src/models/easypostConfigOut.ts
javascript/src/models/githubConfigOut.ts
javascript/src/models/hubspotConfigOut.ts
javascript/src/models/ingestSourceIn.ts
javascript/src/models/ingestSourceOut.ts
javascript/src/models/pandaDocConfigOut.ts
javascript/src/models/portIoConfigOut.ts
javascript/src/models/rutterConfigOut.ts
javascript/src/models/segmentConfigOut.ts
javascript/src/models/shopifyConfigOut.ts
javascript/src/models/slackConfigOut.ts
javascript/src/models/stripeConfigOut.ts
javascript/src/models/svixConfigOut.ts
javascript/src/models/vapiConfigOut.ts
javascript/src/models/veriffConfigOut.ts
javascript/src/models/zoomConfigOut.ts

Review this PR commit by commit. each commits fixes a different rule 
2. [Fix `lint/correctness/noUnusedFunctionParameters`](https://github.com/svix/svix-webhooks/pull/2072/commits/0fd10198caff546cda41486f31785eeb17adc9cc), renamed params from `<param>` to `_<param>`  
3. [Fix `lint/style/noNonNullAssertion`](https://github.com/svix/svix-webhooks/pull/2072/commits/b0b86dabb550fea74b50fe7dff94264351bf02d0), Remove some not null assertions from the tests
4. [Fix(ignore) `lint/suspicious/noImplicitAnyLet`](https://github.com/svix/svix-webhooks/pull/2072/commits/c71fb196ccd7cd9a69c80fee8b0cb1f3fc6d11a9): Ignore this warning (since this code is generated, I am comfortable with ignoring the type system) 
5. [Fix(ignore) `lint/suspicious/noEmptyInterface`](https://github.com/svix/svix-webhooks/pu …

ts: Fix all outstanding biome lint rules

---

.github/workflows/python-release.yml

Instead of using the `TWINE_PASSWORD`, Tom added support for oidc/trusted publishing.
The `TWINE_PASSWORD` was also removed. So this is now the only way to publish to our pypi package.

Replace the `TWINE_PASSWORD` with trusted publishing
